### PR TITLE
BZ# 1642623 - Fix permission related display issues

### PR DESCRIPTION
**Pull request by chalettu**
Fix for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1642623
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label hammer/yes

### CODE REVIEW

**Comment by AllenBW** [comment]
@chalettu any chance we can get a ss of this in action?

**Comment by chalettu** [comment]
Before
before
After
after

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit baa3b1cc7f37fb9446b51c86e946e7d5c9d790d0
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Thu Oct 25 13:35:24 2018 -0400

    Merge pull request #1484 from chalettu/sui-permissions-cleanup
    
    BZ# 1642623 - Fix permission related display issues
    
    (cherry picked from commit 04236dbc6f5f92201b58bc40f627a47b94004bcf)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1642623
```

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit dcec4398dbb739e2040eda63aea1c3281a9a6a88
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Thu Oct 25 13:35:24 2018 -0400

    Merge pull request #1484 from chalettu/sui-permissions-cleanup
    
    BZ# 1642623 - Fix permission related display issues
    
    (cherry picked from commit 04236dbc6f5f92201b58bc40f627a47b94004bcf)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1649419
```

**Comment by AllenBW** [comment]
@simaishi  Its all good, just needed to be restarted <3

**Comment by simaishi** [comment]
@AllenBW Thanks Allen. I restarted once, but I should have done it a few more times!

**Comment by AllenBW** [comment]
ARG REALLY!!! 😩 yah it's been known to be a 🐻 at times 🤗

**Pull request merged**
