### PR TITLE
[GAPRINDASHVILI] BZ#1601587 - Fixed issue with dialogs that causes duplicate values

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug

### CODE REVIEW

**Comment by chalettu** [comment]
This is the SUI implementation that fixes the bug addressed here, https://github.com/ManageIQ/ui-components/pull/316

**Comment by simaishi** [comment]
@chalettu @AllenBW Are we not updating `yarn.lock`?

**Comment by AllenBW** [comment]
Ooooo good point, we ought to update that as well, @chalettu yah want me to drop in?

**Comment by chalettu** [comment]
Repushed branch with the yarn.lock file updates

**Pull request merged**
