### PR TITLE
[Changelog] Update for Hammer-5 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@AllenBW as time permits, can you review/merge.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 85cbcb69f5425a06d923beeb223f33fe94b72ac7
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Mon Apr 22 10:14:24 2019 -0400

    Merge pull request #1539 from JPrause/hammer5_cl
    
    [Changelog] Update for Hammer-5 release
    
    (cherry picked from commit ba65b584973b12ff487c9710ba2bec3cf2403370)
```

**Pull request merged**
