### PR TITLE
Changed Catalog menu title

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143721973

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label catalogs
@miq-bot add_label fine/yes

**Comment by chriskacerguis** [comment]
Since the security issues existed before this, going to merge.

**Comment by chriskacerguis** [comment]
No UX needed, just a bug fix for the proper nomenclature.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 56bd9a06cad70632cbcb58a2ba0cd162afd0b537
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Apr 17 19:24:55 2017 -0500

    Merge pull request #676 from chalettu/service-catalog-title
    
    Changed Catalog menu title
    (cherry picked from commit 68c5e5947bf360556b42307f7047fd1faf9f72b7)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1442902
```

**Pull request merged**
