### PR TITLE
Service Dialog - Element visibility on condition is not working 

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/141443927.

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label catalog

**Comment by chalettu** [comment]
@miq-bot add_label catalogs

**Comment by chalettu** [comment]
@miq-bot add_label euwe/yes

**Comment by simaishi** [comment]
@chalettu `client/app/core/dialog-field-refresh.service.js` doesn't exist in Euwe. Please create an Euwe-specific PR (referencing this one) or suggest other PRs to backport.

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/pull/580

**Pull request merged**
