### PR TITLE
Created Report details component and pages

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/142087865.  This PR is for a detail page that shows details about a report and allows for queueing and downloading a report

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/no
@miq-bot add_label enhancement
@miq-bot add_label reports

**Comment by chriskacerguis** [comment]
NSP seems to be having issues posting status back; I redid the integration but it doesn't have any way to resubmit.

**Comment by chalettu** [comment]
report-details

**Comment by chriskacerguis** [comment]
I tagged the report explore as fine/yes so the report things needs to be fine.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 801673ecc24a449408c27630491cdf7c71cce090
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Mar 29 13:47:17 2017 -0500

    Merge pull request #613 from chalettu/report-details
    
    Created Report details component and pages
    (cherry picked from commit 5f7912d2ae0bd94dcb95f2b1e77f54b345ce7d55)
```

**Pull request merged**
