### PR TITLE
[EUWE] Change My Requests subsections from tabs to secondary nav

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This PR removes the tabs from the My Requests section and adds secondary nav items "Requests" and "Order History"

Jira Story: https://patternfly.atlassian.net/browse/CFUX-142

(cherry-picked and resolved conflicts for euwe branch)

Backport of #270 

@chriskacerguis @chessbyte

### CODE REVIEW

**Comment by dtaylor113** [comment]
LGTM

**Comment by jeff-phillips-18** [comment]
@chessbyte @chriskacerguis  I have another PR (breadcrumb updates) for euwe that depends on this PR going in first. Does it look like this PR will get put in for 4.2 (deadline soon(?

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 it's up to @chessbyte to merge Euwe things.

**Comment by chessbyte** [comment]
Euwe Backport of #270

**Pull request merged**
