### PR TITLE
PT#139371937 create snapshot

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/139371937

## Action Shots (updated to reflect latest)
image
image
image

### CODE REVIEW

**Comment by abellotti** [comment]
@AllenBW, the "memory" parameter in the API is a boolean. i.e. include physical memory in the snapshot to create or not.  The UI screenshots above did not imply a boolean.

/cc @imtayadeway

**Comment by chriskacerguis** [comment]
@AllenBW a few UI thoughts in the attached screenshot.
164c9b8c-f84e-11e6-8333-cace289d179c

**Comment by AllenBW** [comment]
@chriskacerguis what icon would you like for inactive snapshots?

**Comment by AllenBW** [comment]
Thanks for that @abellotti :+1:

**Comment by chriskacerguis** [comment]
Here's what I was thinking (please excuse HORRIBLE photoshopping work).  Where it says primary, it should be "Active".  Just a thought...not saying it's right or wrong.

85a249cc-f8db-11e6-989a-7365b037967b

**Comment by AllenBW** [comment]
its beautiful! totally down to do it as a column but don't see the point of an icon, would seem to serve no function (and therefor shouldn't exist) @chriskacerguis thoughts?

**Comment by chriskacerguis** [comment]
@AllenBW I think that the icon is pretty :)

**Pull request merged**
