### PR TITLE
Doesn't time out when session timeout is reached

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143874847

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label blocker
@miq-bot add_label fine/yes

**Comment by chalettu** [comment]
@miq-bot add label global / authentication

**Comment by chalettu** [comment]
@miq-bot add_label global / authentication

**Comment by chriskacerguis** [comment]
CC seems stuck, merging.

**Comment by AllenBW** [comment]
👍

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 431eb1cdd52cd0f17bca1df2ba41ce99036b34f2
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue May 2 14:23:11 2017 -0500

    Merge pull request #731 from chalettu/session-timeout
    
    Doesn't time out when session timeout is reached
    (cherry picked from commit b114b90a26e63c4ead172c4c72e93fe565579c5c)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1443166
```

**Pull request merged**
