### PR TITLE
[Finishes #149501873] Added ui-components Dialog to SUI

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label fine/no
@miq-bot add_label catalogs / dialogs
@miq-bot add_label enhancement

### CODE REVIEW

**Comment by chalettu** [comment]
No UX review required.  Just adding our common dialog component into Service UI

**Comment by chriskacerguis** [comment]
@chalettu did this get reviewed in the ui-components repo?

**Comment by chalettu** [comment]
@chriskacerguis this did get reviewed in ui-components.

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1502309

**Pull request merged**
