### PR TITLE
Various tweaks to allow js minification for prod build

### PR DESCRIPTION
**Pull request by jjlangholtz**
Enable the `ng-strict-di` directive on `html` so that exceptions are
thrown when dependency injection is not handled properly.

Swap the babel plugin ng annotation tool with a loader variant. The
babel-focused version was missing several annotations which prevented
the build bundle from working properly.

Lock ngProgress to the latest version (released on GH but not npm). The
old version we are currently does not handle dependency injection
correctly and therefore cannot be minified.

https://github.com/VictorBjelkholm/ngProgress/issues/116

### CODE REVIEW

**Comment by jjlangholtz** [comment]
https://www.pivotaltracker.com/story/show/137196541

@AllenBW
@miq-bot add_label euwe/no, enhancement

**Comment by chriskacerguis** [comment]
@jjlangholtz can you please fix the conflict?

**Comment by AllenBW** [comment]
Thems some quick responses tex 🥇

**Comment by chriskacerguis** [comment]
Indeed...but now tests are failing 🤕

**Pull request merged**
