### PR TITLE
BZ#1602108 - Changed Retire services to a modal instead of confirmation

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label enhancement

### CODE REVIEW

**Comment by chalettu** [comment]
Screenshot of update
demo_retire_again

**Comment by chalettu** [comment]
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1602108

**Comment by AllenBW** [comment]
@chalettu would yah mind posting what it look like when we have 20 items selected? 

Just wanta make sure we're not creating more problems than we're looking to solve...

**Comment by chalettu** [comment]
Here is a demo of what it looks like when selecting 50 services at once to retire
demo_2

**Comment by chalettu** [comment]
@serenamarie125 , do you think this UI interaction for this modal is appropriate.  When you try to retire a lot of services at once in SUI, we list them all and make them scrollable.  Do you think we should have a threshold where we should change this?  Let us know your thoughts.

**Pull request merged**
