### PR TITLE
[EUWE] BZ#1505546-Adds support for `supports_vnc_console` decorators

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1505546

WIP for the time being need this in: https://github.com/ManageIQ/manageiq/pull/16377

### CODE REVIEW

**Comment by AllenBW** [comment]
cc @jntullo

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis  Merged https://github.com/ManageIQ/manageiq/pull/16377. This is ready?

**Comment by AllenBW** [comment]
@simaishi yeah!! was just about to mention to yah, this is g2g!

**Comment by simaishi** [comment]
@AllenBW Thanks!
@chriskacerguis Please approve if it's ok to merge

**Pull request merged**
