### PR TITLE
[GAPRINDASHVILI] Update @manageiq/ui-components to 1.0.16 for gaprindashvili

### PR DESCRIPTION
**Pull request by himdel**
Contains:

ManageIQ/ui-components#258
ManageIQ/ui-components#265

Cc @chalettu

### CODE REVIEW

**Comment by AllenBW** [comment]
bz here: https://bugzilla.redhat.com/show_bug.cgi?id=1531677

**Comment by JPrause** [comment]
@himdel are we good to merge. :+1:

**Comment by AllenBW** [comment]
@JPrause not quite... almost... almost....

:point_right: [February 21, 2018 1:35 PM](https://gitter.im/ManageIQ/manageiq/ui?at=5a8dbc0da2194eb80d957e15)

**Comment by chalettu** [comment]
@AllenBW , you can remove the WIP part.  This is good to go.  My other PR we are working on is apparently unrelated.  I tested and validated this one and it is good to go.

**Comment by AllenBW** [comment]
If good for nothing else, I sure can WIP unWIP it 😏

**Comment by chalettu** [comment]
Looks good to me.

**Comment by syncrou** [comment]
BZ that is resolved once this is merged: https://bugzilla.redhat.com/show_bug.cgi?id=1548562

**Comment by JPrause** [comment]
@AllenBW can this be merged at this time?

**Comment by AllenBW** [comment]
@JPrause yeah! its assigned to @simaishi

**Pull request merged**
