### PR TITLE
Dashboard is missing information on Orders

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/144790887

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes
@miq-bot add_label dashboard

**Comment by chriskacerguis** [comment]
@chalettu can you please address the Travis fail?

**Comment by AllenBW** [comment]
@chriskacerguis Woah, this should not have been merged, we removed the requests explorer and associated states, if anything adding orders info to the dashboard should have been done (theres a pt out for it) but this reads what was intentionally removed

**Comment by chriskacerguis** [comment]
@chalettu please add screenshot.  I merged this too quickly.

**Comment by chalettu** [comment]
dashboard

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1449783

**Comment by chriskacerguis** [comment]
@simaishi this has become a blocker FYI.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 8b2b2929b05464c9bcaef5622123280305d86ef8
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed May 3 17:44:16 2017 -0500

    Merge pull request #738 from chalettu/dashboard-orders
    
    Dashboard is missing information on Orders
    (cherry picked from commit da44d75d00e44e8dac72954ce80c64f72d26847e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1449792
```

**Pull request merged**
