### PR TITLE
Created ability for dynamic dialogs to be sorted

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143594667

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label euwe/yes
@miq-bot add_label fine/yes
@miq-bot add_label catalogs

**Comment by simaishi** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1436720

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit ebaa4116894094dce1db19401fa30fbe61884ee2
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 12 14:55:27 2017 -0500

    Merge pull request #671 from chalettu/dynamic-dialog-sort
    
    Created ability for dynamic dialogs to be sorted
    (cherry picked from commit 544f2607cf0be049ac4272a7f81e1bbd78a1e27a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1442168
```

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 12a2c9272f2d2ebd09628710947526fb3489b48f
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 12 14:55:27 2017 -0500

    Merge pull request #671 from chalettu/dynamic-dialog-sort
    
    Created ability for dynamic dialogs to be sorted
    (cherry picked from commit 544f2607cf0be049ac4272a7f81e1bbd78a1e27a)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1442169
```

**Comment by simaishi** [comment]
@chalettu please take a look at Travis failure: https://travis-ci.org/ManageIQ/manageiq-ui-service/builds/235372522

```
client/app/services/dialog-field-refresh.service.js
  line 58  col 59  'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').  (W119)
```

**Comment by simaishi** [comment]
@chalettu @chriskacerguis just want to make sure this isn't forgotten 😄  Please fix Travis failure for Euwe.

**Comment by chalettu** [comment]
@chriskacerguis I have a fix for this travis issue. Its merely upset that we are using es6 syntax and JShint isn't currently configured to allow for it.  Do you want me to put in a PR to allow our jshint linter to allow es6 syntax?

**Comment by chriskacerguis** [comment]
that works.

**Comment by chalettu** [comment]
Added https://github.com/ManageIQ/manageiq-ui-service/pull/805 to get linting to work properly.

**Pull request merged**
