### PR TITLE
BZ#1549239 Changed how breadcrumb shows up on catalog order page

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1549239

### CODE REVIEW

**Comment by chalettu** [comment]
Screenshot of Service Catalog order page 
service catalog

**Comment by chalettu** [comment]
Screenshot of Reorder service page
reorder

**Comment by AllenBW** [comment]
@chalettu Was meaning here: https://github.com/ManageIQ/manageiq-ui-service/blob/master/client/app/states/orders/explorer/explorer.state.js#L11

cuz ya go from explorer to details view... title changing is kinda jarring...

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ffd0c72f2367ac461b1a97df8827d320943114ad
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Thu Mar 1 09:55:26 2018 -0500

    Merge pull request #1392 from chalettu/my-orders-breadcrumb
    
    BZ#1549239 Changed how breadcrumb shows up on catalog order page
    (cherry picked from commit 3cf36ee479171cf736f87f2eb7c05a844e501660)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1554370
```

**Pull request merged**
