### PR TITLE
Fix for Bugzilla 1371291: Tag Control Fld. in SUI - Convert array of tag ids to csv string

### PR DESCRIPTION
**Pull request by dtaylor113**
This PR addresses https://github.com/ManageIQ/manageiq-ui-service/pull/295#issuecomment-257620187.

In SUI, when a service catalog is added to the Shopping Cart, this PR converts an array of tag ids to a comma separated string.

@chriskacerguis @serenamarie125 @gmcculloug

### CODE REVIEW

**Comment by gmcculloug** [comment]
Tested the fix locally.  Looks good, thanks.  👍

**Comment by gmcculloug** [comment]
Added `darga/yes` flag to match PR #295.

@chessbyte Both PRs #295 and #314 need to be backported to darga to resolve the associated blocker BZ https://bugzilla.redhat.com/show_bug.cgi?id=1376519.

**Comment by chessbyte** [comment]
Darga BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1376519

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git log -1
commit 9f3847c4be402955767f223db8414a4643208ada
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Nov 2 09:35:06 2016 -0500

    Merge pull request #314 from dtaylor113/fix-for-bugzilla-1376519
    
    Fix for Bugzilla 1371291: Tag Control Fld. in SUI - Convert array of tag ids to csv string
    (cherry picked from commit 956014919f9a2dd6874e8c6f8c87a6af8be0d3b4)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1376519
```

**Comment by chessbyte** [comment]
Euwe BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1392070

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log -1
commit 015d0c1ef61ba197e2904e1dcd46b912b67805d0
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Nov 2 09:35:06 2016 -0500

    Merge pull request #314 from dtaylor113/fix-for-bugzilla-1376519
    
    Fix for Bugzilla 1371291: Tag Control Fld. in SUI - Convert array of tag ids to csv string
    (cherry picked from commit 956014919f9a2dd6874e8c6f8c87a6af8be0d3b4)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1392070
```

**Pull request merged**
