### PR TITLE
BZ#1589409 - Support for disabling Dashboard

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
Screenshot of what it looks like if you don't have access to the Dashboard.  
demo_screenshot

**Comment by AllenBW** [comment]
closes https://bugzilla.redhat.com/show_bug.cgi?id=1589409

**Comment by serenamarie125** [comment]
I'm not sure of the RBAC model for the SUI, but I wonder if utilizing something like this might make more sense than only handling a single use case:
- if user access to 1 or more of the nav items, navigate to the first navigation item by default
- if user access to none of the nav items, don't let them in ( i think we previously handled this case )

@chalettu @AllenBW @Loicavenel @ohadlevy thoughts?

**Comment by serenamarie125** [comment]
I think that makes sense @chalettu but you should def get the 👍from either Ohad or Loic first!

**Comment by AllenBW** [comment]
Oh oh yeah so if a user can view say, the service catalog, and *ONLY* the service catalog, thats the page they should be pushed to 😋

**Comment by chalettu** [comment]
Updated the logic to go down the list of pages a user has access to and pick the firsts one they can access and sends them there .  So if a person tries to go to a page they do not have access to, they will be redirected to the first menu item they do have access to.

**Comment by AllenBW** [comment]
So I jumped in with a few users, ones that only had the service catalog role enabled then my orders enabled, the role looking a lil like this...

screen shot 2018-06-20 at 8 07 08 am


And for both users, when attempting to login, ended up with this...
screen shot 2018-06-20 at 8 07 52 am

**Comment by chalettu** [comment]
@AllenBW , I tried reproducing the error you are seeing with the role you had pictured above and  can't seem to reproduce it.  Did you close your browser out and try fresh after saving the role changes?  We cache permissions so if you didnt log out first of SUI, sometimes it causes weird things to happen.

**Comment by AllenBW** [comment]
@chalettu yeah tried it across a number of browsers, bounced the miq instance between changes, same result. Gonna do a box bounce and see if that changes anything 🤷‍♂️

**Comment by AllenBW** [comment]
Yeah bounced the box, still see it, furthermore this is what yah get when working from master, only have the "Service Catalog" and "Desktop" lnav tab
screen shot 2018-06-20 at 11 08 23 am

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 307c96833fe66b7bfccb66ea7ced8c767182b412
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Wed Jun 20 11:27:49 2018 -0400

    Merge pull request #1446 from chalettu/dashboard-permissions
    
    BZ#1589409 - Support for disabling Dashboard
    (cherry picked from commit ae385823137b78b78b1ea6b8abdee77b0b9b2ac4)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1595454
```

**Pull request merged**
