### PR TITLE
BZ#1568574 - Fixed issue with custom button details dynamic field refresh

### PR DESCRIPTION
**Pull request by chalettu**
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1568574.
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by AllenBW** [comment]
@chalettu looks like travis demands a test update

**Comment by chalettu** [comment]
Yeah.  Just saw it and I am updating and retesting it locally.  Slashing the / from a few tests

**Comment by chrispy1** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit c482dfeec80d04c07563c50d2aad3ef327434276
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Wed Apr 18 17:07:18 2018 -0400

    Merge pull request #1423 from chalettu/custom-button-refresh-issue
    
    BZ#1568574 - Fixed issue with custom button details dynamic field refresh
    (cherry picked from commit 43580fc6e2e3126dd2e64d6899b2c162987eaefc)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1569551
```

**Pull request merged**
