### PR TITLE
Change explorer default limit to 10 items

### LINKED ISSUE #1147: Set 10 as the default for all list views
Set 10 as the default for all list views

### PR DESCRIPTION
**Pull request by AllenBW**
closes #1147 

## after 1900 x 1200 resolution
screen shot 2017-10-25 at 1 39 08 pm
screen shot 2017-10-25 at 1 39 01 pm
screen shot 2017-10-25 at 1 38 54 pm

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW could you please post the load times for the page with 20 vs. 10 items?

**Comment by AllenBW** [comment]
@chriskacerguis which page, each page?

**Comment by AllenBW** [comment]
### service explorer `api/services` load times 10: 941 ms

screen shot 2017-10-26 at 8 24 39 am

### service explorer `api/services` load times 20: 5.35s 

screen shot 2017-10-26 at 8 22 35 am

@chriskacerguis

**Comment by Loicavenel** [comment]
it does not seem linear, what about 50? 60?

**Comment by ohadlevy** [comment]
> it does not seem linear, what about 50? 60?
sounds like a N+1 API calls? how many API calls do we do per service ?

**Comment by AllenBW** [comment]
We do a single api call to get the services, ya wanta see time for a 50 to 60 service call?

**Comment by ohadlevy** [comment]
@AllenBW in that case, I would guess its a N+1 problem on the api call itself?

**Comment by AllenBW** [comment]
@ohadlevy yeaaaaaaah seems to be? @imtayadeway is checkin' it out 😍 🏓

**Comment by serenamarie125** [comment]
@ohadlevy @chriskacerguis @Loicavenel let's be aware of how we are affecting the user experience.  I understand there are performance issues, but changing to a default of 10 items per page is only going to help the performance issue the first time they look at a few.

Do we in SUI have the ability to change the page size across the app?  I don't think so, but we should.

By making a change like this, users will need to change the page size every time they come to a view.  So sure the time for the view to initially load may be quicker, but they likely are then going to change the page size, and then have to wait anyways.  From what we have heard from customers to date, typically 50 is the size they want.  

If we have to make this change due to performance, I would request that we at a minimum consider a user setting to set the default page size, so that users can change the default.

**Comment by chriskacerguis** [comment]
@serenamarie125 

> Do we in SUI have the ability to change the page size across the app?

No.  I would think that would be in a "My Settings" page, which I don't think we have (but, I agree with you, that would be helpful to be able to do)

> From what we have heard from customers to date, typically 50 is the size they want.

Why is that?  To quote @ohadlevy "are they searching with Ctrl + F"?  To me it seems that 50 items on the page is a lot of data for the human eye to process.  Just wondering if reducing would be better overall.  Disclaimer: I am totally not a UX expert...just asking questions :)

**Comment by Loicavenel** [comment]
In Ops UI, you can go to My Settings and change how many Items you see in List view across all the pages.

 I am not fully against the 10 by default but if the user wants to browse all the services then select 100, the performance issue will be still there.
We can always think about a better filtering to avoid this long list scrolling (Can we define all possible filtering???) but many users will always do it this way...

**Comment by chriskacerguis** [comment]
@Loicavenel Not sure we have an API to get that setting (I still think having a local settings in the SUI would be a good thing).  That said, ultimately, this is an API issue...you are correct, all we are doing is trying to help any way we can.  Regarding the filtering, that's a UX thing, and so I'll differ to @serenamarie125 

All that said, I'm wondering if we should just hold off on this PR, until @imtayadeway finishes he work on the API.

Thoughts @Loicavenel @ohadlevy @serenamarie125 ?

**Comment by chriskacerguis** [comment]
Thinking about this, I think we should wait and let @imtayadeway do his mojo.

**Pull request closed without merging**
