### PR TITLE
Add support for the VMRC remote consoles for VMware VMs

### PR DESCRIPTION
**Pull request by skateman**
Resolving https://github.com/ManageIQ/manageiq/issues/18718 by exposing the protocol as a param when asking the API for a remote console.

Depends on:
https://github.com/ManageIQ/manageiq/pull/19097
https://github.com/ManageIQ/manageiq-api/pull/642
https://github.com/ManageIQ/manageiq-providers-vmware/pull/429

@miq-bot add_label pending core, hammer/no, changelog/yes
@miq-bot assign @himdel 
@miq-bot add_reviewer @AllenBW

### CODE REVIEW

**Comment by himdel** [comment]
LGTM,
but I think this also needs a spec fix:

```
client/app/services/consoles.service.spec.js
16:    Consoles.open('12345')
28:    Consoles.open('12345').then((data) => {
37:    Consoles.open('12345').then((data) => {
56:    Consoles.open('12345').then((data) => {
75:    Consoles.open('12345').then((data) => {
93:    Consoles.open('12345').then((data) => {
112:    Consoles.open('12345').then((data) => {
132:    Consoles.open('12345').then((data) => {
152:    Consoles.open('12345').then((data) => {
```

none of those calls are probably being tested right, given the second param is now required.

**Comment by skateman** [comment]
Need to verify with PM about ivanchuk/yes or not, but this can go in.
@miq-bot rm_label pending core

**Comment by skateman** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 71ee4eb8e6eea8ad0426407ce79645d5a4bbd731
Author: Martin Hradil <mhradil@redhat.com>
Date:   Thu Aug 8 14:46:28 2019 +0200

    Merge pull request #1570 from skateman/vmrc-support
    
    Add support for the VMRC remote consoles for VMware VMs
    
    (cherry picked from commit 6c4b17c3d01210aa65ef0f99a50cc34ca71da90e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1740691
```

**Pull request merged**
