### PR TITLE
PT 134032873 - View Requests

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/134032873
https://www.pivotaltracker.com/story/show/135551091

This pr accomplishes the following and closes the two pt tickets above: 
> Allow an admin to view all requests that need approve (and add views / filters to view old approved / rejected requests)

> Need to have pagination to the My Requests page http://localhost:3001/ui/service/requests/requests)

TODO (in other prs):
* approve requests from requests list
* reject requests from requests list

requests

@chrisarcand @dtaylor113

### CODE REVIEW

**Comment by dtaylor113** [comment]
Hi @AllenBW, it would be great to see a screenshot of this change :smile:

**Comment by AllenBW** [comment]
screen shot 2016-12-08 at 1 35 43 pm

super early, but just because I like you @dtaylor113  :-) 🌮

**Comment by AllenBW** [comment]
@miq-bot remove_label wip
@miq-bot add_label euwe/no, enhancement

**Comment by AllenBW** [comment]
@miq-bot remove_label wip

**Comment by chriskacerguis** [comment]
Manually removing WIP tag...something seems to be wrong with MIQ Bot.

**Comment by chriskacerguis** [comment]
waiting for Travis to finish, then will merge.

**Comment by chriskacerguis** [comment]
@AllenBW can you please address tests?

**Comment by AllenBW** [comment]
@chriskacerguis yah! decided against making that change quite yet...

**Pull request merged**
