### PR TITLE
Updated the attribute for stdout for Ansible services in SUI

### PR DESCRIPTION
**Pull request by chalettu**
PV story https://www.pivotaltracker.com/story/show/142309107

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/yes
@miq-bot add_label enhancement
@miq-bot add_label services

**Comment by chalettu** [comment]
@AllenBW can you review this one?

**Comment by AllenBW** [comment]
@chalettu  if ya can hold off till tomorrow, id like to swap my dbs for the one that has stdout jazz, get some solid affirmative on this 🤘

**Comment by chalettu** [comment]
Perfectly fine by me.   No rush here.   Please let me know when you have this magical db installed and tested.  Thanks in advance

**Comment by AllenBW** [comment]
🙇‍♀️ **IT WILL BE SO**

**Comment by AllenBW** [comment]
Confirming this is gonna take a few seconds, service with output that worked before, doesn't work presently (despite being connected to vpn and all that jazz, working to get it going, please stand by, **THIS HAS MY HIGHEST PRIORITY** :godmode: 👍

**Comment by AllenBW** [comment]
@chalettu implement the above changes and **YOU TOO** can gaze upon this glory
image

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit e70254000226122de10e91fd7154a6847fa34e05
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu Mar 30 11:30:17 2017 -0500

    Merge pull request #614 from chalettu/ansible-std-out-endpoint
    
    Updated the attribute for stdout for Ansible services in SUI
    (cherry picked from commit fc3fa2045f6ff33c8323682bbe08d4ec98fe4c2e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1437652
```

**Pull request merged**
