### PR TITLE
Create Mock API

### PR DESCRIPTION
**Pull request by chalettu**
This PR is to create a simple mock api server that can be used by e2e testing or by local frontend development

### CODE REVIEW

**Comment by Fryguy** [comment]
Out of curiosity, had you reviewed any of these projects?

  * [Nock-VCR](https://github.com/carbonfive/nock-vcr) (JavaScript/Node)
  * [Sepia](https://github.com/linkedin/sepia) (JavaScript/Node)
  * [VCR.js](https://github.com/elcuervo/vcr.js) (JavaScript)
  * [yakbak](https://github.com/flickr/yakbak) (JavaScript/Node)

cc @chriskacerguis

**Comment by chalettu** [comment]
I hadn't seen those before.  They look interesting.  Node has a sea of modules and these didn't come up when looking for something to mock an existing API.   I could potentially look at them and see if they fit well for what we are doing.

**Comment by Fryguy** [comment]
@chriskacerguis I'm surprised this was merged with cloudforms in the data still.  Is that a bug in ManageIQ itself in that it's returning cloudforms, or was the mock data generated from cloudforms as opposed to manageiq.

**Comment by chalettu** [comment]
@Fryguy the data I put in the mocks came directly from me just running manageiq locally.

**Comment by Fryguy** [comment]
@chalettu Can you please open an issue or make a PR on manageiq?  That data should not be in there.

**Comment by Fryguy** [comment]
Oh I see...it's actually the name of a service that is in the sample data that you used.

**Pull request merged**
