### PR TITLE
Update jquery for master

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/n/projects/1914499/stories/136378431

@chriskacerguis

### CODE REVIEW

**Comment by simaishi** [comment]
Will be backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/pull/401

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis https://github.com/ManageIQ/manageiq-ui-service/pull/401 is closed.  Do we still need to backport this?

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis - do we need this in euwe?

**Comment by chriskacerguis** [comment]
yes.

**Comment by simaishi** [comment]
Since #401 is closed... what will be the replacement?  Since this PR contains `yarn`, I'd assume you'll create a separate Euwe PR?

**Comment by chriskacerguis** [comment]
I don't know why it was closed.  @AllenBW can you please reopen?

**Comment by simaishi** [comment]
@AllenBW https://github.com/ManageIQ/manageiq-ui-service/pull/401 should be re-opened?

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/pull/554

**Pull request merged**
