### PR TITLE
[WIP] added hound CI file

### PR DESCRIPTION
**Pull request by chriskacerguis**
added hound CI file

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu please review

**Comment by chessbyte** [comment]
@chriskacerguis what is Hound CI?  /cc @Fryguy

**Comment by chessbyte** [comment]
Setting WIP until we can discuss with Jason.

**Comment by chessbyte** [comment]
@chriskacerguis you cannot merge PRs that you create.  That defeats the purpose of review by someone else.  So, re-assigning to @Fryguy

**Comment by chriskacerguis** [comment]
@chessbyte hound is a SASS / ESLinter.  We have no bots that do that, and it was brought up that it would be best to NOT have travis do the linting.  @Fryguy and I have talked in the past (1st Mahwah trip about Hound).

**Pull request closed without merging**
