### PR TITLE
[EUWE] Bz 1471158 - HTML5 Console Does Not Display From SSUI VMWare

### PR DESCRIPTION
**Pull request by chalettu**
Backport of GH PR https://github.com/ManageIQ/manageiq-ui-service/pull/685 to EUWE release. 

BZ https://bugzilla.redhat.com/show_bug.cgi?id=1471158

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label euwe/yes

**Comment by chriskacerguis** [comment]
@chalettu can you fix the Travis issue?

**Comment by chalettu** [comment]
@chriskacerguis I could spend some time on it but from what I looked at it yesterday, it is not due to any code change that was introduced.  This is a issue with some of the gulp dependencies being upgraded and meant to work with a newer version of node than we have stuck with for this release.  Let me know if you want me to invest time in trying to fix it.

**Comment by chalettu** [comment]
@chriskacerguis , Travis build issue has now been resolved.

**Comment by chriskacerguis** [comment]
@chalettu well done!

@simaishi this is good to go, whenever you are ready!

**Pull request merged**
