### PR TITLE
Added ./images to dev serve path, updated all offensive image paths

### LINKED ISSUE #316: Profile images not found
Hi, 
when creating a profile the image is not loading (404). The profile image is referenced as:
https://hostname/self_service/assets/images/providers/vendor-vmware_cloud.svg
is should be referenced as
https://hostname/self_service/images/providers/vendor-vmware_cloud.svg

without the assets.

I am testing on euwe-RC1.

### PR DESCRIPTION
**Pull request by AllenBW**
Ends up a few paths hardcoded for dev env slipped through, those have been removed and updated to paths that work for dev and prod

screen shot 2016-11-04 at 8 44 59 am
screen shot 2016-11-04 at 8 42 52 am
screen shot 2016-11-04 at 8 42 30 am
screen shot 2016-11-04 at 8 42 19 am

closes #316

@chriskacerguis 🌮
@dtaylor113  I promise blueprints hasn't been broken 🔒 📿 
@evertmulder can you confirm this to be a satisfactory solution?

### CODE REVIEW

**Comment by AllenBW** [comment]
@miq-bot add_label euwe/yes

**Comment by chessbyte** [comment]
Euwe Backport conflict:
```sh
$ git cherry-pick -e -x -m 1   1bcb7c6 
error: could not apply 1bcb7c6... Merge pull request #318 from AllenBW/bug/316-profile-images-not-found
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

$ git status
On branch euwe
Your branch is up-to-date with 'upstream/euwe'.
You are currently cherry-picking commit 1bcb7c6.
  (fix conflicts and run "git cherry-pick --continue")
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by us:   client/app/components/blueprints/blueprint-canvas/_blueprint-canvas.sass
	both modified:   client/app/services/profiles-state.service.js
	both modified:   client/app/states/designer/blueprints/editor/_editor.sass
	both modified:   client/app/states/services/details/details.html
	deleted by us:   server/utils/serviceApp.js
	deleted by us:   tests/profiles/profiles-details.directive.spec.js

$ git diff
```

```diff
diff --cc client/app/services/profiles-state.service.js
index c11cbd8,ef78684..0000000
--- a/client/app/services/profiles-state.service.js
+++ b/client/app/services/profiles-state.service.js
@@@ -5,65 -5,60 +5,86 @@@
        .factory('ProfilesState', ProfilesStateFactory);
  
    /** @ngInject */
 -  function ProfilesStateFactory(CollectionsApi, EventNotifications, sprintf) {
 +  function ProfilesStateFactory(CollectionsApi, EventNotifications, sprintf, $q) {
      var profileState = {};
  
++<<<<<<< HEAD
 +    profileState.providersInfo = [
 +      {
 +        keyword: 'amazon',
 +        title: 'Amazon EC2',
 +        image: 'assets/images/providers/vendor-amazon.svg',
 +      },
 +      {
 +        keyword: 'azure',
 +        title: 'Azure',
 +        image: 'assets/images/providers/vendor-azure.svg',
 +      },
 +      {
 +        keyword: 'google',
 +        title: 'Google Compute Engine',
 +        image: 'assets/images/providers/vendor-google.svg',
 +      },
 +      {
 +        keyword: 'openstack',
 +        title: 'OpenStack',
 +        image: 'assets/images/providers/vendor-openstack_infra.svg',
 +      },
 +      {
 +        keyword: 'vmware',
 +        title: 'VMware vCloud',
 +        image: 'assets/images/providers/vendor-vmware_cloud.svg',
 +      },
 +    ];
++=======
+     var providerTypes = {
+       amazon: 'Amazon EC2',
+       azure: 'Azure',
+       google: 'Google Compute Engine',
+       openstack: 'OpenStack',
+       vmware: 'VMware vCloud',
+       unknown: 'Unknown',
+     };
+     var providerImages = {
+       amazon: 'images/providers/vendor-amazon.svg',
+       azure: 'images/providers/vendor-azure.svg',
+       google: 'images/providers/vendor-google.svg',
+       openstack: 'images/providers/vendor-openstack_infra.svg',
+       vmware: 'images/providers/vendor-vmware_cloud.svg',
+       unknown: 'images/providers/vendor-unknown.svg',
+     };
+ 
+     var providerTypeKeys = ['amazon', 'azure', 'google', 'openstack', 'vmware'];
++>>>>>>> 1bcb7c6... Merge pull request #318 from AllenBW/bug/316-profile-images-not-found
  
 -    function getProviderKey(typedObject) {
 -      var key;
 +    profileState.getProviderType = function(typedObject) {
 +      var providerType = 'Unknown';
  
        if (typedObject) {
 -        key = providerTypeKeys.find(function(nextKey) {
 -          return typedObject.type.toLowerCase().indexOf(nextKey) >= 0;
 +        var info = profileState.providersInfo.find(function(providerInfo) {
 +          return typedObject.type.toLowerCase().indexOf(providerInfo.keyword) >= 0;
          });
 +        if (info) {
 +          providerType = info.title;
 +        }
        }
  
 -      if (!key) {
 -        key = 'unknown';
 -      }
 -
 -      return key;
 -    }
 -
 -    profileState.getProviderTypes = function() {
 -      var returnTypes = [];
 -
 -      angular.forEach(providerTypeKeys, function(key) {
 -        returnTypes.push(providerTypes[key]);
 -      });
 -
 -      return returnTypes;
 +      return providerType;
      };
  
 -    profileState.getProviderType = function(typedObject) {
 -      return  providerTypes[getProviderKey(typedObject)];
 -    };
 +    profileState.getProviderTypeImage = function(provider) {
 +      var providerImage = 'assets/images/providers/vendor-unknown.svg';
 +
 +      if (provider) {
 +        var info = profileState.providersInfo.find(function(providerInfo) {
 +          return provider.type.toLowerCase().indexOf(providerInfo.keyword) >= 0;
 +        });
 +        if (info) {
 +          providerImage = info.image;
 +        }
 +      }
  
 -    profileState.getProviderTypeImage = function(typedObject) {
 -      return  providerImages[getProviderKey(typedObject)];
 +      return providerImage;
      };
  
      profileState.sort = {
diff --cc client/app/states/designer/blueprints/editor/_editor.sass
index bd1a4e7,eabca9a..0000000
--- a/client/app/states/designer/blueprints/editor/_editor.sass
+++ b/client/app/states/designer/blueprints/editor/_editor.sass
@@@ -204,13 -219,13 +204,17 @@@
  
      .canvas
        //border: 2px solid brown
++<<<<<<< HEAD:client/app/states/designer/blueprints/editor/_editor.sass
 +      width: 1396px
 +      height: 756px
 +      background-image: url('/client/assets/images/blueprint-designer/canvas-dot-grid.png')
++=======
+       background-image: url('../images/blueprint-designer/canvas-dot-grid.png')
++>>>>>>> 1bcb7c6... Merge pull request #318 from AllenBW/bug/316-profile-images-not-found:client/app/components/blueprints/blueprint-editor/_blueprint-editor.sass
        background-repeat: repeat
 -      height: 756px
 -      width: 1396px
  
      .canvas-in-connection-mode
-       background-image: url('/client/assets/images/blueprint-designer/canvas-dot-grid-disabled.png')
+       background-image: url('../images/blueprint-designer/canvas-dot-grid-disabled.png')
        background-repeat: repeat
  
      a
diff --cc client/app/states/services/details/details.html
index f9129b8,66917cc..0000000
--- a/client/app/states/services/details/details.html
+++ b/client/app/states/services/details/details.html
@@@ -203,9 -202,8 +203,13 @@@
                    <i class="fa fa-html5 fa-lg"></i>
                  </button>
                  <button class="btn btn-default open-console-button" ng-if="item['supports_cockpit?'] && item.power_state == 'on'" tooltip="{{'Open Cockpit console for this VM'|translate}}" tooltip-placement="left">
++<<<<<<< HEAD
 +                  <img src="/client/assets/images/cockpit.png"></img>
++=======
+                   <img src="images/cockpit.png">
++>>>>>>> 1bcb7c6... Merge pull request #318 from AllenBW/bug/316-profile-images-not-found
                  </button>
 +              </span>
              </div>
            </div>
          </div>
* Unmerged path client/app/components/blueprints/blueprint-canvas/_blueprint-canvas.sass
* Unmerged path server/utils/serviceApp.js
* Unmerged path tests/profiles/profiles-details.directive.spec.js
```

**Comment by chriskacerguis** [comment]
@AllenBW can you please address?

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/pull/333

**Pull request merged**
