### PR TITLE
BZ#1527053 - Fixed issue with adding to cart not working

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1527053
I will need to create follow on PR's for Fine

### CODE REVIEW

**Comment by chalettu** [comment]
Screenshot of Fix 
add_to_cart_demo

**Comment by himdel** [comment]
LGTM, removes the last use of `serviceTemplate`.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 80120059c292807addbbdfd2526103ead4be7393
Author: Martin Hradil <himdel@seznam.cz>
Date:   Wed Dec 20 18:02:25 2017 +0100

    Merge pull request #1347 from chalettu/add_to_cart_fix
    
    BZ#1527053 - Fixed issue with adding to cart not working
    (cherry picked from commit eebcdc254000d68a75985ed8fa8b2f88510b2a0d)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1530798
```

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-ui-service/pull/1348

**Pull request merged**
