### PR TITLE
Minor fixes for I18N and status icon display in services list.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This fixes an issue brought up in #270 as well as a small icon
placement issue I found in the services list while testing the same.

@chriskacerguis @himdel 

@miq-bot add_label euwe/no

### CODE REVIEW

**Comment by himdel** [comment]
@jeff-phillips-18 not like this.

You really need to `N_()` the string **literal**, not any variable .. literal. You can do `__(foo)` when that foo is either a literal already or is a variable which has come from `N_("literal")`.

So you really need to fix *all* the *callers* of `createFilterField` and `createSortField` and put the `N_` there. Then (but only then) the body of those functions can indeed use `__(variable)`.

**Comment by jeff-phillips-18** [comment]
@himdel ah, I see. Thanks, I will fix it.

**Comment by himdel** [comment]
Thanks! this looks right :)

**Comment by himdel** [comment]
Just adding a note here for clarity.. 

This is correctly `euwe/no`, but *technically* it's `euwe/backported` because these changes were part of https://github.com/ManageIQ/manageiq-ui-service/pull/276 .

**Pull request merged**
