### PR TITLE
[Changelog] Update for Sprint 116

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@AllenBW could you review as time permits.

**Comment by JPrause** [comment]
@h-kataria do you know who can review/merge.

**Comment by JPrause** [comment]
@himdel can you review/merge as time permits.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 712b28d230a21ba820cefc1f48ac041e23be6691
Author: Martin Hradil <mhradil@redhat.com>
Date:   Wed Jul 31 15:29:43 2019 +0200

    Merge pull request #1564 from JPrause/sprint116a_cl
    
    [Changelog] Update for Sprint 116
    
    (cherry picked from commit 6a7118793ae8880b018f7ccf037f7e2634de2a5f)
```

**Pull request merged**
