### PR TITLE
Show only stack name for Orchestration Stack

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143350197

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/yes
@miq-bot add_label bug
@miq-bot add_label services

**Comment by chriskacerguis** [comment]
No UX changes.

**Comment by simaishi** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1439862

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 089fdcd8d30c418b95b83510ece9214bbadabde1
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Fri Apr 7 17:26:15 2017 -0500

    Merge pull request #656 from chalettu/show-stack-name
    
    Show only stack name for Orchestration Stack
    (cherry picked from commit 8f8431b8cf65aca33c762734567a6140948965f4)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1440579
```

**Pull request merged**
