### PR TITLE
Left align various elements in explorer views

### PR DESCRIPTION
**Pull request by jjlangholtz**
https://www.pivotaltracker.com/story/show/143875833

@miq-bot add_label fine/yes, bug, services, orders, ux/review

Services Explorer:
screen shot 2017-04-19 at 12 57 54 pm

Orders Explorer:
screen shot 2017-04-19 at 12 57 47 pm

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@ManageIQ/core-ux Could you please confirm that this is what you were looking for?

**Comment by serenamarie125** [comment]
@jjlangholtz left alignment looks great!  I'm not sure if this is an effect of this PR, but the vertical line between the filter & sort components doesn't look centered between components.  Can you take a peak at that if it's a result of this PR?  Thank you!

**Comment by chriskacerguis** [comment]
@serenamarie125 I think that I have seen that elsewhere, so I don't think it is part of this PR.  That said, I have made a new story: https://www.pivotaltracker.com/story/show/143970777

**Comment by chriskacerguis** [comment]
@serenamarie125 you ok with merge, since we have another ticket for the other alignment issue?

**Comment by jjlangholtz** [comment]
@serenamarie125 Thanks!

> the vertical line between the filter & sort components doesn't look centered between components.

Good 👀! checked it out and that was introduced in this PR. Should be fixed now.

screen shot 2017-04-19 at 2 21 10 pm

**Comment by chriskacerguis** [comment]
@serenamarie125 how does that alignment work?

**Comment by serenamarie125** [comment]
lol @jjlangholtz.  Who says that 👀 get worse with 👵 haha!

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 1619be7bc7298475cf8e2f69308dcd01c1787c39
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 19 14:24:27 2017 -0500

    Merge pull request #690 from jjlangholtz/fix-explorer-left-alignment-issues
    
    Left align various elements in explorer views
    (cherry picked from commit 6e8287ea194cd7930a876597706b65f8ff76ef1d)
```

**Pull request merged**
