### PR TITLE
[WIP] Display Request Workflow for MiqProvisionRequest type of requests

### PR DESCRIPTION
**Pull request by AparnaKarve**
Workflow tabs use the `workflow` object returned by the `api/requests/<id>?attributes=workflow
` API (https://github.com/ManageIQ/manageiq/pull/13254)

Progress so far...

`Request`, `Purpose`, `Catalog`, `Environment` and `Hardware`  tab in both UIs

Classic UI:
screen shot 2017-01-05 at 10 37 17 am

screen shot 2017-01-11 at 10 50 34 am

screen shot 2017-01-16 at 3 41 59 pm

screen shot 2017-01-19 at 4 06 38 pm

screen shot 2017-01-25 at 4 15 32 pm

SUI:
screen shot 2017-01-05 at 11 13 52 am

screen shot 2017-01-11 at 10 50 59 am

screen shot 2017-01-16 at 3 39 26 pm

screen shot 2017-01-19 at 4 08 31 pm

screen shot 2017-01-25 at 4 15 21 pm

https://www.pivotaltracker.com/n/projects/1914499/stories/136994131

### CODE REVIEW

**Comment by AparnaKarve** [comment]
@miq-bot add_label wip

**Comment by chriskacerguis** [comment]
@serenamarie125 can you please take a look at the UX here?

**Comment by chriskacerguis** [comment]
@AparnaKarve could you please provide an update on where things are with this?

**Comment by AparnaKarve** [comment]
@chriskacerguis 
Short update: 
4 tabs (Request, Purpose, Catalog, Environment) are done out of a total of 8.
Work very much in progress.

Long update: 
One of the reasons why this is so time-consuming is because some tabs were in need of some API enhancements. 
So far 5 API enhancement PRs were created for this story --
https://github.com/ManageIQ/manageiq/pull/13254
https://github.com/ManageIQ/manageiq/pull/13379
https://github.com/ManageIQ/manageiq/pull/13441
https://github.com/ManageIQ/manageiq/pull/13497
https://github.com/ManageIQ/manageiq/pull/13574

For the remaining tabs, I do not think we need any more API enhancements.
But remember that this is just displaying the Workflow information. The next step would be `Edit`ing it, and at that point I'm expecting to add more API enhancements to populate the dropdowns etc.

**Comment by AparnaKarve** [comment]
One more API PR in the works that is required for this PR -- https://github.com/ManageIQ/manageiq/pull/13672

**Comment by AllenBW** [comment]
@AparnaKarve so long as we git this in in under year, you have nothing to 😊 about 😆

**Pull request closed without merging**
