### PR TITLE
PT#149703867 standardjs/eslint swap

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/149703867

What just happened? https://standardjs.com/rules.html

## A ss to demonstrate error reporting is as normal, browser and server console still show offending code
screen shot 2017-08-25 at 11 44 07 am

## A ss showing we still build and run correctly (notice that url), ALSO super important 😆 
screen shot 2017-08-25 at 12 06 51 pm

### CODE REVIEW

**Comment by Fryguy** [comment]
cc @martinpovolny @dclarizio @himdel Just wanted you to be aware of the proposed "rules" changes here that may not be consistent with the OPs UI.

**Comment by AllenBW** [comment]
@Fryguy yep did!  and posted the pr 👍 😆 💘

**Comment by chriskacerguis** [comment]
@AllenBW could you tweak the code coverage a bit?

**Comment by AllenBW** [comment]
@chriskacerguis I do not believe that should be done in this pr, If we end up wanting to roll the linting change back we would be decreasing code coverage.

**Comment by chriskacerguis** [comment]
Spoke to @AllenBW and I agree with your above comment.

**Pull request merged**
