### PR TITLE
Revert "Merge pull request #793 from eclarizio/BZ1439761"

### PR DESCRIPTION
**Pull request by chalettu**
This reverts commit f248880fce83dc2fa23571156271ecd740970d4f, reversing
changes made to 23c1ebbe6e9b1de5bca052702a2d5e5ca022132b.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu for posterity sake, can you please add some comments as to why we are doing this?

**Comment by chalettu** [comment]
We are temporarily removing this PR because of issues we discovered post merge that were shortcircuiting our unit tests from running and we discovered some possibilities for optimizing approach for this functionality that removes the dependency on jquery.   Will have this functionality resubmitted soon .

**Comment by AllenBW** [comment]
OOOO OOO do the alt click on the timestamp in gitter channel!! then we can link the convo...

**Comment by AllenBW** [comment]
:point_up: [May 30, 2017 5:43 PM](https://gitter.im/ManageIQ/manageiq-ui-service?at=592de7985e34568d5ea83380)

context

**Pull request merged**
