### PR TITLE
PT#140975359 secure headers

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/140975359

no visual changes, requires no ss

### CODE REVIEW

**Comment by martinpovolny** [comment]
@AllenBW, @chriskacerguis: gentleman, given the Pivotal task references my name, I'd appreciate a ping at least.

But to the point: I understand that on an appliance the app is running from staticaly served precompiled assets. Is that right?

If so I don't see how this is going to help. Can you explain, please?

I emphasize that I have not looked into the issue and, please, correct me if I am wrong, but my first thought is that this needs to be done on the Apache side.

**Comment by martinpovolny** [comment]
I am trying to understand what you actually did.

Seems the headers are being added for the javascript server serving the SUI assets in dev-mode. Right?

Seems to me that only this line: 

https://github.com/ManageIQ/manageiq-ui-service/pull/603/commits/71447caf4be36dee0665a42a735ce1c170284664#diff-9e4a215b4f5f613a802fa43d8ab35270R22 is really relevant for the topic of this PR. 

The rest seems to be refactoring/cleanup is that correct?

Based on recent talks about 100% test coverage I wonder if there's any test coverage for this. I'd love to learn how this is done with the stack of this project.

**Comment by chriskacerguis** [comment]
@martinpovolny - This was a follow up task from the email chain where we were discussing security issues with secure_headers.  From the email:

> Action item: I am afraid that we do not have an equivalent for the secure_headers for the assets of SUI. We should add that!

Regarding a few other things, yes you are correct any security headers need to be added by Apache (as everything is served out of that in production).  However, due to the concerns for security, we added the secure headers to be added when running in "dev" mode.

Regarding the title, I agree, I think that this is an older ticket and "newer" tickets have the correct title.

I'll let @AllenBW talk more specifically about the code itself.

**Comment by AllenBW** [comment]
Hi @martinpovolny :wave: We only use app.js when deploying to heroku, so this won't help at any other time, but then again sui doesn't "control itself" any other time :laughing:  You are correct that line and adding the dependency to the app are the primary changes, rest is refactoring.  Not sure what ya mean by test coverage for this, if helmet operates as expected?

**Comment by martinpovolny** [comment]
@AllenBW : on test coverage: I don't know, I hoped to learn that here :-D

Would be insterested in reading a test for that and learn something new!

Please, ping me in a PR where you are going to deal with the appliance part of the action item. I'll really appreciate that!

**Comment by chriskacerguis** [comment]
@martinpovolny will do!  RE: Testing, are you looking for something specific?  We can point you do some PR's with testing if that is what you are looking for.  Happy to help in any way we can, just let me know.

**Pull request merged**
