### PR TITLE
PT#139486261 - Update angular patternfly

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/139486261

### Major work performed
- Switch all attribute directives to component forms, i.e `<div pf-list-view>` to `<pf-list-view>`
- Find and replace usage of `pf-datepicker` which was also removed in angular-patternfly 4
- Upgrade application code to use lodash 4
- rework pf-select
- replace customScope with $ctrl.customScope
- correct form implementations, they're off in places
- Audit usage of each converted component, in a short time of testing found a few issues with pf-list-view customScope not working as expected

### GIF of exploring each of the changes (I tried to retire something that isn't retierable, excuse this thing that looks like a bug, not related to the pf4 jump)
ang-pf4

### CODE REVIEW

**Comment by AllenBW** [comment]
Ok mildly bad news, kinda blocked by a bug atm, [documented here](https://github.com/patternfly/angular-patternfly/issues/478) working on work arounds...

**Comment by AllenBW** [comment]
Never mind the above, we're good https://github.com/patternfly/angular-patternfly/pull/479

**Comment by AllenBW** [comment]
I'm pulling off wip on this... reasonably satisfied it'll go the distance... but will likely require a little bit of merge work once https://github.com/ManageIQ/manageiq-ui-service/pull/792 makes it in

**Comment by chriskacerguis** [comment]
@himdel @h-kataria would love some feedback, if you have a minute.

/cc @dclarizio @chessbyte @Fryguy

**Comment by AllenBW** [comment]
Working on getting some gif's up of minor visual changes brought by pf4

**Comment by chriskacerguis** [comment]
@serenamarie125 for your review

**Comment by chriskacerguis** [comment]
@Loicavenel FYSA

**Comment by AllenBW** [comment]
Related to this pr... I made this over here... https://github.com/patternfly/angular-patternfly/pull/481/files

**Comment by serenamarie125** [comment]
From what i see, this looks great visually - thanks for doing this :)  
I'm cc'ing @jeff-phillips-18 so he can take a look as well

**Comment by chriskacerguis** [comment]
@serenamarie125 not a problem! :)

**Pull request merged**
