### PR TITLE
[EUWE] BZ#1527578 Tooltip on Retire button

### PR DESCRIPTION
**Pull request by chalettu**
Fix for tooltip on retire button blocking the click of options
@miq-bot add_label bug
@miq-bot add_label euwe/yes

### CODE REVIEW

**Comment by chalettu** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1527578

**Comment by AllenBW** [comment]
@chalettu would yah mind posting a gif or ss of the action?

**Comment by chalettu** [comment]
retire_tooltip
SS of fix

**Comment by chalettu** [comment]
The travis failure is a npm related issue not a issue with the PR itself.

**Comment by AllenBW** [comment]
Yeah travis on euwe is kinda... 🙅‍♂️  will merge once it's done failing 😆

**Comment by chalettu** [comment]
Does @simaishi do the merging for these PR's that need to be backported?

**Comment by AllenBW** [comment]
bahaha yeah gooooooood call assigned

**Comment by simaishi** [comment]
@chalettu @AllenBW What need to be done to fix Travis for Fine branch? Is it just matter of re-running or something need to be changed?  If it's failing in npm, no test ran, right?

**Comment by AllenBW** [comment]
@simaishi Yeah its been something up with dependencies...  rerunning wont make it happy, something will have to be dug into :-/

**Comment by chalettu** [comment]
@simaishi I was able to get the build to go green and finish running its test.  We had to lock some versions of certain packages down.

**Comment by simaishi** [comment]
@chalettu That's great - thank you!

**Pull request merged**
