### PR TITLE
Add tests to client/app/services/poweroperations.service.js

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/145296611

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/no
@miq-bot add_label test

**Comment by chriskacerguis** [comment]
@chalettu since you have changed actual code, and not just tests, can you please post a quick video gif showing the power operations still work?

**Comment by chalettu** [comment]
poweroperations

**Comment by chriskacerguis** [comment]
confirmed no UX changes, just a refactor and code test.  Merging.

**Pull request merged**
