### PR TITLE
[FINE] BZ#1392096 - Update translations

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1392096
Pulled from the latest zanata

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW can you please take a look at the Travis fail?  Also, bitHound seems upset too.

**Comment by AllenBW** [comment]
@chriskacerguis remember this is into fine, before @jjlangholtz did those cleanups, bithound is gonna complain bout all da files i didn't touch 😆

**Comment by chriskacerguis** [comment]
@simaishi All good for merge.

**Comment by simaishi** [comment]
BZ for 'fine' branch: https://bugzilla.redhat.com/show_bug.cgi?id=1448079

**Pull request merged**
