### PR TITLE
[EUWE] Adjust show/hide cockpit attribute gate to supports_cockpit?

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1471158

#1132

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@simaishi this is good to merge (you can ignore the NSP fail)

**Comment by chriskacerguis** [comment]
@AllenBW do we need to ask the server for that decorator?

**Comment by AllenBW** [comment]
@chriskacerguis already done https://github.com/AllenBW/manageiq-ui-service/blob/1c89bad866695a5cf39d68296832155a5f874cf5/client/app/states/services/details/details.state.js

as part of the work in #1132

**Comment by chriskacerguis** [comment]
@AllenBW thanks.  just checking :)

**Pull request merged**
