### PR TITLE
Refactor custom button component

### PR DESCRIPTION
**Pull request by jjlangholtz**
Initial refactoring of existing custom button support. Convert the `CustomButtonDirective` into a component and reduce complexity. Add some initial unit tests and remove most of the existing functionality that was not working.

@miq-bot add_label services, fine/yes, enhancement

### CODE REVIEW

**Comment by chriskacerguis** [comment]
No UX changes.

**Comment by chriskacerguis** [comment]
@jjlangholtz is there a PT with this?

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit bb593ca145eb51ac332399e98983957fe27f674b
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Apr 3 16:56:11 2017 -0500

    Merge pull request #630 from jjlangholtz/refactor-custom-button-component
    
    Refactor custom button component
    (cherry picked from commit 86e22ee56905eaec8bbb1602e3b6b906e001a308)
```

**Comment by jjlangholtz** [comment]
https://www.pivotaltracker.com/story/show/142773333

**Pull request merged**
