### PR TITLE
Adds csp to sui

### PR DESCRIPTION
**Pull request by AllenBW**
Tested this on dev and built, no irregular behavior or surprise errors cropped up.

- `connect-src` required for notifications served via websocket

Wondering if this should be backported, no idea, its a security thing, should backport to at least fine fairly *fine* 😏

### CODE REVIEW

**Comment by AllenBW** [comment]
cc @martinpovolny  lemme know if ya think a directive or source value is in need of changing!

**Comment by AllenBW** [comment]
@martinpovolny the reason we require `'unsafe-eval' 'unsafe-inline'` is app is bootrapped by: https://github.com/manageiq/manageiq-ui-service/blob/5f7b28f1e1b841a5d34729e183c89fa36464eea9/client/index.ejs

**Comment by himdel** [comment]
Any reason for the whitespace changes? :)

(Other than misconfigured editor, the file was clearly using 2 spaces per indent level, now it's using 4 with squashed head & body.)

**Comment by himdel** [comment]
Umm.. I'll just let you play with the editor config until the actual change becomes visible in the diff ;)

**Comment by himdel** [comment]
@martinpovolny I think I'll need your help here, I have no idea what the implications of this CSP are.

(Until the formatting is fixed, looks like this is the only change:

```diff
+  <meta http-equiv="Content-Security-Policy"
+        content="default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src * data: 'unsafe-inline'; font-src 'self' data:; connect-src *;">
```

**Comment by AllenBW** [comment]
Formatting is at two spaces per indent unsure what you desire to be fixed?

**Comment by himdel** [comment]
Well... ook, I'll put it like this.. :) 

Here's two screenshots. Tell me, which one is easier to review?

csp-evil

or 

csp-good

**Comment by AllenBW** [comment]
Well sure, but the formatting of the whole file needed to be updated to be two spaces, i suppose that work coulda been broken out in two commits for readability.. but it had to be done either way

**Comment by himdel** [comment]
@AllenBW Aah, well, I definitely won't stop you from trying to make the code cleaner :+1: 

*But* if you could do it in a commit of its own the next time.. :)

**Comment by AllenBW** [comment]
@himdel @martinpovolny as this has been sitting for a month, gonna close it, keep the branch around just in case... we want to... 

🐙 🍍 🍔

**Comment by martinpovolny** [comment]
@AllenBW : I have been falling behind with review since my PTO and then finally taking time to do some React and Angular. Sorry for that.

Please, reopen. I'll test it and merge. We can do further fixes in follow up PRs.

Thx!

**Comment by martinpovolny** [comment]
@himdel : I think that the rules can be more strict. But that might need some extra work. Let's merge this and improve it in follow-up PRs when there's time for that.

Please, merge this one, I can't do it (I am not in the magic file). Thx!

Thanks, @AllenBW

**Pull request merged**
