### PR TITLE
Updated the calculation for Chargebacks

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label  gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1509367

**Comment by chriskacerguis** [comment]
@chalettu BZ?

**Comment by AllenBW** [comment]
@chalettu can we get a ss of this working?

**Comment by chalettu** [comment]
screenshot Here is a screenshot of an appliance that is using the updated calculation

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 7f5e95e365d3b3a4b2cd697dc430837ac98ef702
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Nov 15 15:49:09 2017 -0600

    Merge pull request #1244 from chalettu/chargeback-reports
    
    Updated the calculation for Chargebacks
    (cherry picked from commit 1cc53100afe10958bdc65a8c869657b23cf76660)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1514260
```

**Pull request merged**
