### PR TITLE
moved Mock API to NPM

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143978893

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label enhancement
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
@chriskacerguis @chalettu `Fine` branch still has mock_api directory. Since we're moving to NPM for `Fine`, would you rather create an Euwe PR that also clean up those extra things?

**Comment by chriskacerguis** [comment]
@chalettu thoughts?

**Comment by simaishi** [comment]
@chalettu please let me know what need to be done here.. If I should just backport this (without removing extra files no longer needed), can you still confirm this PR should be backported as is?  There has been no mock api related changes backpoted to `fine` branch, so I want to make sure everything will work with current `fine` branch + this PR.

**Comment by chalettu** [comment]
@simaishi It should be fine to go ahead and backport this PR and 708 to Fine Branch.  Don't bother with 695 as 708 is newer.  The mock api files are fine to go ahead and leave in this branch .  They won't harm anything

**Comment by simaishi** [comment]
@chalettu Thanks for the confirmation.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 23fbb866fdbbd400f71cf83c966f5fac564531fd
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 19 14:43:27 2017 -0500

    Merge pull request #694 from chalettu/mock-api-npm
    
    moved Mock API to NPM
    (cherry picked from commit 9ca3b3e4235d0975b484349546471b2458e60f0e)
```

**Pull request merged**
