### PR TITLE
[EUWE] [Fixes #151305890] Retiring soon filter not inclusive of certain services

### PR DESCRIPTION
**Pull request by chalettu**

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label euwe/yes

**Comment by AllenBW** [comment]
@chalettu can ya link the bz?

**Comment by chalettu** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1492867

**Comment by chalettu** [comment]
@chriskacerguis I reran the build and now everything is green.

**Comment by chriskacerguis** [comment]
Ready to go @simaishi

**Pull request merged**
