### PR TITLE
[Changelog] Update for Ivanchuk Beta1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@himdel as time permits, can you review/merge.

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 83865ae080f2121cb32c1b4b4e8af4c2c3a0cd5c
Author: Martin Hradil <mhradil@redhat.com>
Date:   Wed Jul 31 16:36:00 2019 +0200

    Merge pull request #1569 from JPrause/ivanb1_cl
    
    [Changelog] Update for Ivanchuk Beta1
    
    (cherry picked from commit e8b82be8829d71372e6469480f848717533b81d9)
```

**Pull request merged**
