### PR TITLE
Fix for Bugzilla 1376519: Tag Control fields not working in SUI - Set single or multiple selection

### PR DESCRIPTION
**Pull request by dtaylor113**
A tag can be single or multiple select:

image

https://bugzilla.redhat.com/show_bug.cgi?id=1376519

@chriskacerguis @serenamarie125

### CODE REVIEW

**Comment by gmcculloug** [comment]
@dtaylor113 Tested this change and the control does allows you to select multiple tags but only one tag makes it onto the queue.

To test I setup a button as part of a service template.  Once the service is provisioned and available in `My Services` I ran the custom button to show the dialog with the tag field.

When running from the Classic UI I see the two selected tags in the `MiqQueue` table `args` column:
`Array::dialog_tag_dept: Classification::8,Classification::9`

Running the same thing from the Service UI I get:
`Array::dialog_tag_dept: Classification::9`

Not sure where this is getting lost at the moment.  Might need @abellotti to help on the API side.

**Comment by gmcculloug** [comment]
Added blocker flag for the darga release.

@dtaylor113 Tracked down the issue with @abellotti.  The UI is passing an array of IDs, which seems completely reasonable, but the backend is expecting a comma separated string.

The Classic UI has a field value of "8,9,11" which gets parsed by `.to_s.split(",")` and three tags are passed.  When the SUI passes them as an array it ends up with something like this:
```
irb(main):001:0> [8,9,11].to_s.split(",")
=> ["[8", " 9", " 11]"]
```
and only tags 9 and 11 are loaded.

See here [app/models/dialog_field_tag_control.rb#L75](https://github.com/ManageIQ/manageiq/blob/7746cc0f1906731095c541d47c25cbf9ad0cbe11/app/models/dialog_field_tag_control.rb#L75)

Can we get a followup PR to pass the values as a comment separated string?

**Comment by chessbyte** [comment]
Euwe BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1371291

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log -1
commit c350f3974b1fa47dfde43fa79062c987b4c1a435
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu Oct 27 09:07:20 2016 -0500

    Merge pull request #295 from dtaylor113/fix-tag-control-fields
    
    Fix for Bugzilla 1376519: Tag Control fields not working in SUI - Set single or multiple selection
    (cherry picked from commit 499724f5deb47f2199b7e86368130b779340a58e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1371291
```

**Comment by dtaylor113** [comment]
I can look into this tomorrow.

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git log -1
commit 42cdf0bc1d1d7f854a67c8a57ce5571c548d9ee6
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu Oct 27 09:07:20 2016 -0500

    Merge pull request #295 from dtaylor113/fix-tag-control-fields
    
    Fix for Bugzilla 1376519: Tag Control fields not working in SUI - Set single or multiple selection
    (cherry picked from commit 499724f5deb47f2199b7e86368130b779340a58e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1376519
```

**Pull request merged**
