### PR TITLE
List all services

### PR DESCRIPTION
**Pull request by AllenBW**
## Does not include (work left to do in other prs): 
* Configuration, Policy, Life cycle buttons (and functionality) 
* Propose a (more so) permanent solution for a footer toolbar

## Includes (what it does)
* new list view fields and layout that scale with browser viewport 
* Adds pagination and limit functionality (tests for pagination component)
* Load screen component
* Power state component
* Update badge count query, no longer requests extraneous info
* Update Collections api to handle additional functionality
* General refactoring and deduplication
* Lots of 🌮 🌮 🌮 

https://www.pivotaltracker.com/story/show/133840391

## The Good Stuff
list

### Smaller
screen shot 2016-11-22 at 4 00 16 pm

### Smallest
screen shot 2016-11-22 at 4 00 36 pm

**Hey you beautiful 🍑s would appreciate a look, thoughts, suggestions, inputs**
@chriskacerguis @jjlangholtz @himdel @serenamarie125 @jntullo @chalettu

### CODE REVIEW

**Comment by AllenBW** [comment]
screen shot 2016-11-16 at 8 22 29 pm

where we got to today

**Comment by AllenBW** [comment]
## Todays Progress
* Refactored powerstate to be a component
* Added pagination component (it works, this is super :taco)
* Added card view to table
* General cleanup to explorer component
* Identified api bug where the limit request supersedes the available items in the offset

screen shot 2016-11-17 at 5 19 30 pm
screen shot 2016-11-17 at 5 18 52 pm
screen shot 2016-11-17 at 5 18 26 pm

**Comment by serenamarie125** [comment]
@AllenBW what is Service Explorer and why is it in the UI :)  And where's the pagination component from - it needs a little UX <3, but I'm assuming this is not specific to the Service UI?

**Comment by AllenBW** [comment]
@serenamarie125 Service explorer is what i'm calling the existing list view when one adds a bottom toolbar, pagination,  and parity functionality with ops ui(all those *do thing* buttons)

Pagination component was hand rolled for this, is modular in execution and easily ported to elsewhere; styling isn't completely done (one of a few reasons why the pr is still a WIP) specific feedback on design is  most appreciate 

The pivotal ticket has the specifics of tasks outstanding for this  🌮

**Comment by chriskacerguis** [comment]
@AllenBW going to let this sit for 24 hours for comments.

**Comment by AparnaKarve** [comment]
@AllenBW I haven't tried this out yet, but the screenshots look really awesome! 👍 

I noticed that the 'Start' button that starts the service is no longer visible in the list. 
Is it now included under the kebab menu for space saving reasons?
If so, the `enableButtonForItemFn` function is not applicable anymore.
And we now need to manage the enabled/disabled state of the Start button in `updateMenuActionForItemFn`.

Could you also include a screenshot of the expanded kebab menu? Thanks.

**Comment by AllenBW** [comment]
@AparnaKarve ss as requested! 
screen shot 2016-11-23 at 6 51 42 am
very much a 👾 reason

**Comment by jntullo** [comment]
that's some nice pagination @AllenBW

**Comment by AparnaKarve** [comment]
@AllenBW One question on the above screenshot...
I'm assuming that Service has an "Unknown" Power state...
So for an Unknown Power state, we need to enable only the Start button. 
Stop and Suspend should be grayed out.

I understand that the primary focus of this PR is Pagination so I'm fine fixing this in a follow-up, smaller PR.

**Comment by AllenBW** [comment]
@AparnaKarve all good to do it here!  Please find attached updated ss, good catch and if it hasn't been said already, thank you **SO MUCH** for looking and calling out 🔴 🎏 
screen shot 2016-11-23 at 2 58 41 pm

**Comment by AparnaKarve** [comment]
> good catch and if it hasn't been said already, thank you SO MUCH for looking and calling out 🔴 🎏

Anytime @AllenBW. My pleasure! 😄

**Comment by himdel** [comment]
@AllenBW nice work :) One thing I notice, you probably shouldn't be updating the `pot` file in this PR. (Unless something changed @mzazrivec ?)

**Pull request merged**
