### PR TITLE
[FINE]Reword supports_launch_cockpit for correct supports_cockpit

### PR DESCRIPTION
**Pull request by AllenBW**
This was closed by accident previously.. same as the below pr

https://github.com/ManageIQ/manageiq-ui-service/pull/1166

Master PR: https://github.com/ManageIQ/manageiq-ui-service/pull/1165

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@simaishi ready to go, could you please merge ASAP?

**Comment by chriskacerguis** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1505546

**Comment by simaishi** [comment]
@AllenBW This PR fixes [BZ1505545](https://bugzilla.redhat.com/show_bug.cgi?id=1505545) and [BZ1506806](https://bugzilla.redhat.com/show_bug.cgi?id=1506806) (those are Fine/5.8.z BZ) ?

**Comment by AllenBW** [comment]
@simaishi I'll fix BZ1506806

**Comment by simaishi** [comment]
Talked with @AllenBW This PR fixes https://bugzilla.redhat.com/show_bug.cgi?id=1506806, but also needed for https://bugzilla.redhat.com/show_bug.cgi?id=1505545

**Pull request merged**
