### PR TITLE
BZ#1446405-Update skinning documentation

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1446405
https://www.pivotaltracker.com/story/show/144545827

Indicate how to change 404 and order details logo

### CODE REVIEW

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 70b4c1291d3807aa6ff3ac2f69db32b068fd5201
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Sat Apr 29 16:07:49 2017 -0500

    Merge pull request #727 from AllenBW/BZ/#1446405
    
    BZ#1446405-Update skinning documentation
    (cherry picked from commit e147a2f5f4f5d7a0483351378834c693071aa7c3)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1447051
```

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis this change is requested to be backported to Euwe branch. Would that be a problem?

**Comment by AllenBW** [comment]
@simaishi nope!  they picked a good one to backport with one exception, euwe has an additional mention of the image https://github.com/manageiq/manageiq-ui-service/blob/6a3dc554677c1294f4662112aff29e0b20ebe1af/client/app/states/requests/orders/orders.html#L14

SOOOOO to catch all maybe we should do a euwe specific pr? @chriskacerguis thoughts?

**Comment by chriskacerguis** [comment]
Yeah, I think a euwe specific one makes sense.

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/pull/817

**Pull request merged**
