### PR TITLE
Removed Task for eslint and sasslint from Test

### PR DESCRIPTION
**Pull request by chalettu**
As requested, I removed the listing tasks from the test Gulp task.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 @dtaylor113 @martinpovolny @himdel I asked Chris to remove the linting from the build system, and instead let Hound CI handle that.  thoughts?

**Comment by dtaylor113** [comment]
What does that mean for the build process?  Build Will pass, PR will show
errors?

**Comment by AparnaKarve** [comment]
So essentially with this PR `gulp test` and `gulp testonly` now do the same thing, which is to validate the PhantomJS specs. Would that be correct?

**Comment by chriskacerguis** [comment]
So the build process will work as follows:

Travis - Runs unit tests and integration (phantomJS) tests
CodeClimate - Code Security, test coverage, and various dup and linting checks
Hound - Will provide comments in your PR about issues (similar to how the MIQ bot works)

So, Travis will only fail if there is a unit / integration test fail.

**Comment by himdel** [comment]
<3 Loving this :)

**Comment by jeff-phillips-18** [comment]
Will there be a way to run the lint tests locally?

**Comment by himdel** [comment]
@jeff-phillips-18 `gulp eslint` ;) .. also `gulp sasslint` for sass... (Or `gulp vet` for both)

**Comment by jeff-phillips-18** [comment]
👍

**Comment by jeff-phillips-18** [comment]
Looks like 'Hexadecimal colors should not be used' was just added. Any idea why? What is the rub on using hex?

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 not following, I don't see anything like that is this PR?

**Comment by jeff-phillips-18** [comment]
@chriskacerguis Correct. It was added in #284 . Sorry. I can add this as an issue when I put up the PR to attempt to fix existing warnings (now errors).

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 ahhh...cools.  Sorry, I need more ☕️ 

Not sure, if it wasn't there, and now it is (I think Allen just added the file), feel free to do a PR where you change the .sass-lint.yml and we can talk / discuss 😄

**Comment by AparnaKarve** [comment]
We have 2 identical tasks now:
```
  gulp.task('test', ['templatecache'], task('test', {singleRun: true}));
  gulp.task('testonly', ['templatecache'], task('test', {singleRun: true}));
```
Any reason to keep them both? Like I said above, we could remove `gulp testonly`

**Comment by AllenBW** [comment]
@chriskacerguis @jeff-phillips-18 totally rolled with recommended values from sass-lint, we use hex everywhere so down for continuing to use hex everywhere

Side note colors in the sass should be defined in one place and referenced by name everywhere else .
`_colors.sass` for hex values `_app_colors.sass` adds functional names to the colors, these functional names should be the only reference we make, if you need a color, add a color, but at **all costs** avoid plopping in yet another color to hunt down.

**Comment by chriskacerguis** [comment]
@chalettu see https://github.com/ManageIQ/manageiq-ui-service/pull/291#issuecomment-256395415

**Pull request merged**
