### PR TITLE
Moved Eslint loaders back into Production dependencies

### PR DESCRIPTION
**Pull request by chalettu**
Fixes issue with web pack build failing

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes

**Comment by chriskacerguis** [comment]
This seems to work, but it is not using the correct version of Node (this is using 6.9.1)

**Comment by chriskacerguis** [comment]
Where is web pack failing?

**Comment by chalettu** [comment]
Webpack is failing build for production due to the PR we put in yesterday that split out deps from dev-dependencies.  We have a follow on PV ticket that will make it to where we can move eslint out of our production build process as it is only needed for test and dev.

**Comment by simaishi** [comment]
@chalettu While backporting this, I noticed manageiq-api-mock was added to package.json when I backported https://github.com/ManageIQ/manageiq-ui-service/pull/639. Sorry, but there was no conflict for that and I didn't notice..  I removed it in this backport.  Can you please verify package.json in `fine` branch is good?

Fine backport details:

```
$ git log -1
commit 2bd5c9e22f4c964041fcc955a7fbe550537e4f4a
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Thu Apr 6 18:31:39 2017 -0400

    Merge pull request #648 from chalettu/build-fix
    
    Moved Eslint loaders back into Production dependencies
    (cherry picked from commit 98f9733b9275dd493b7e3713dff7e63c57cb02c6)
```

**Pull request merged**
