### PR TITLE
BZ#1598893 - Updated URL for custom buttons dialogs

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
fix for BZ # https://bugzilla.redhat.com/show_bug.cgi?id=1598893

**Comment by chalettu** [comment]
Screenshot of the fix working as expected. sc

**Comment by jvlcek** [comment]
@chalettu LGTM 👍

**Comment by JPrause** [comment]
@miq-bot add_label blocker

**Comment by JPrause** [comment]
@chalettu would this also need to be backported to hammer,..if yes, can you add the hammer/yes label.

**Comment by chalettu** [comment]
This got merged into master before hammer was cut so I don't believe it needs a hammer backport. @JPrause

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit bf5bb0e7e782b909ea6e8a6cbac7e14fd026e289
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Fri Aug 10 17:16:11 2018 -0400

    Merge pull request #1467 from chalettu/custom-button-details-url
    
    BZ#1598893 - Updated URL for custom buttons dialogs
    
    (cherry picked from commit b1cb62ed39127adb52c6ce8c1b6a100a722c26c1)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1646605
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1646604
```

**Pull request merged**
