### PR TITLE
BZ 1442383 - Self Service UI does not properly select defaults for dynamic drop downs

### PR DESCRIPTION
**Pull request by chalettu**
PV - https://www.pivotaltracker.com/story/show/143965445

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes
@miq-bot add_label euwe/yes
@miq-bot add_label catalogs

**Comment by chriskacerguis** [comment]
@chalettu travis fails

**Comment by chalettu** [comment]
@chriskacerguis travis fixed

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 1e30d397c40ad1070cdc76430f0d6d787bfdc55f
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 19 13:42:42 2017 -0500

    Merge pull request #692 from chalettu/dynamic-dropdown-defaults
    
    BZ 1442383 - Self Service UI does not properly select defaults for dynamic drop downs
    (cherry picked from commit 17895f25cd8a4acef3bec05376100c76d075657c)
```

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 131b79fc4f13033d6fa298c367bcd263928363d7
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Apr 19 13:42:42 2017 -0500

    Merge pull request #692 from chalettu/dynamic-dropdown-defaults
    
    BZ 1442383 - Self Service UI does not properly select defaults for dynamic drop downs
    (cherry picked from commit 17895f25cd8a4acef3bec05376100c76d075657c)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1444062
```

**Pull request merged**
