### PR TITLE
Fix for kebab menu getting cut off on shorter list of items

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/140250535. 

Fixes kebab menu getting cut off on shorter lists.

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label euwe/no

**Comment by AllenBW** [comment]
@chalettu can we get a ss of the fix in action? how does this react when you change the viewport height?

**Comment by chalettu** [comment]
kebab-menu

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1430058

**Pull request merged**
