### PR TITLE
Self-service UI doesn't time out when session timeout is reached

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/n/projects/1914499/stories/143874847

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1435459

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes

**Comment by chalettu** [comment]
@miq-bot add_label authentication

**Comment by isimluk** [comment]
🚀 💥 🤣

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit c418f8399363a3dd2c8237c5fadd45d59932b001
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Apr 18 10:33:13 2017 -0500

    Merge pull request #678 from chalettu/token-header
    
    Self-service UI doesn't time out when session timeout is reached
    (cherry picked from commit cd8ee12778a370843435bcd5674d88932c200ae1)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1443166
```

**Pull request merged**
