### PR TITLE
Created task that allows you to start ManageIQ server from a gulp task

### PR DESCRIPTION
**Pull request by chalettu**
This new task allows you to specify an env variable to start MIQ
services.

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@himdel @martinpovolny does this work for you two?

**Comment by chriskacerguis** [comment]
@chalettu Can you add some usage info to the readme?

**Comment by chalettu** [comment]
@chriskacerguis I updated the readme to reflect how to configure and use the new gulp task.  Please let me know if you would like any revisions to the wording.

**Comment by martinpovolny** [comment]
Cool, thanks, this surely works for me. I see a bit of disconnect between the variables `MANAGEIQPORT` and `PROXY_HOST`, but it works.

**Comment by himdel** [comment]
Thanks, much better! :)

I wonder if the new task should fail if it fails to start manageiq, .. but, up to you :).

**Comment by chriskacerguis** [comment]
@chalettu I like @himdel suggestions of failing if it can't start MIQ, can you make that happen?

**Comment by chriskacerguis** [comment]
@chalettu ping ^

**Comment by chalettu** [comment]
I looked into it and since its an ongoing process I didnt find an easy way to bubble back up a failure to the gulp task.  If anyone has a solid example of that type of pattern available I would be more than happy to modify it to support this feature.

**Comment by himdel** [comment]
@chalettu Yeah, I was wondering about it too, and maybe the only way to do that would be to start, timeout for a bit, and then check if it's still running .. which doesn't sound that clean, so idk.. It's the halting problem all over again :)

**Pull request merged**
