### PR TITLE
[FINE] Ensure session descruction on anything but successful login

### PR DESCRIPTION
**Pull request by AllenBW**
#1061 for `fine`! 

You'll notice its not *EXACTLY* the same, cuz there were a number of changes between the two versions, accomplishes the same task

### CODE REVIEW

**Comment by simaishi** [comment]
@chriskacerguis I assume the node security error can be ignored?

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis ^ ping

**Comment by AllenBW** [comment]
Oh!  yeah @simaishi no worries about that, want me to merge it in?

**Comment by simaishi** [comment]
@AllenBW thanks, just wasn't sure if it's ok to ignore that error.

**Pull request merged**
