### PR TITLE
Updated service reconfigure to use dialog component

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label enhancement
@miq-bot add_label fine/no

### CODE REVIEW

**Comment by AllenBW** [comment]
@chalettu I knoooooow this updating old work, but can we get ss of before and after here?

**Comment by chalettu** [comment]
reconfigure

**Comment by chalettu** [comment]
@chriskacerguis , got testing to go back up a little bit.

**Comment by chalettu** [comment]
@AllenBW , I added a SS as requested.

**Pull request merged**
