### PR TITLE
 Dupilcate of #775 for master - Ensures ansible service displays vm resources

### PR DESCRIPTION
**Pull request by AllenBW**
Identical to #775 except for master (where as #775 was for fine)

Because this is identical to #775 no ss (they're over there)

apologies for the formatting noise

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu can you please review and add feedback?

**Comment by chriskacerguis** [comment]
This should be a fine/no

**Comment by simaishi** [comment]
As per my comment in #775, please still mark the 'master' PR as 'yes' even if you need a separate PR for Fine.

**Comment by chriskacerguis** [comment]
@simaishi will do!

**Comment by chriskacerguis** [comment]
UX approved #775, this is the same UX change...going to merge.

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-ui-service/pull/775

**Pull request merged**
