### PR TITLE
Added ability to hide toasts based on RBAC

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label enhancement
@miq-bot add_label fine/no

### CODE REVIEW

**Comment by chalettu** [comment]
GH Issue https://github.com/ManageIQ/manageiq-ui-service/issues/1052
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1496233

**Comment by chalettu** [comment]
This PR is dependent on https://github.com/ManageIQ/manageiq/pull/16107 getting merged

**Comment by Loicavenel** [comment]
@chalettu @chriskacerguis are we using the Role section we are implementing?

**Comment by chalettu** [comment]
illustration
@Loicavenel , this is where in Classic UI you would go to enable/disable notifications

**Comment by Loicavenel** [comment]
Ok, we are good. thx

**Comment by chalettu** [comment]
@Loicavenel , FYI.  All the PR's for allowing SUI to define its own Product features like above illustration were all merged as of yesterday.  Now we can build on that functionality for any features you want to enable to be disabled granularly.  Note: I just put in a PR for the notification permission this morning so that particular permission isn't merged yet but should be soon.

**Comment by Loicavenel** [comment]
@chalettu can you share the structure or we have only Notification and App Launcher for now?

**Comment by chalettu** [comment]
@Loicavenel , the structure pictured above is all we have defined to date.   We wanted to start incrementally.  Now that we have the plumbing in place, I think you and @chriskacerguis can sit down and decide on a master list we would like to add.

**Comment by AllenBW** [comment]
Probably should start by remapping all rbac that relied on existing product features... one of the many applicable places https://github.com/AllenBW/manageiq-ui-service/blob/master/client/app/core/rbac.service.js#L22

**Comment by Loicavenel** [comment]
@chalettu I did provide a doc about a proposed structure.. https://drive.google.com/open?id=10p69nnTT7dG0hnCBCJkcapjlxVd08J0A2QRX054B_08

**Comment by chriskacerguis** [comment]
@Loicavenel could we put that tree in this ticket?

**Comment by Loicavenel** [comment]
Sure. then people can review it.

**Pull request merged**
