### PR TITLE
Update translation .pot

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/144103713

Part one of two, second part will be to upload compiled translations.... stay tuned!

### CODE REVIEW

**Comment by simaishi** [comment]
There are lots conflicts.. Not sure if this is supposed to be backported??  We had a Fine PR (https://github.com/ManageIQ/manageiq-ui-service/pull/670) for this file not too long ago.

**Comment by simaishi** [comment]
cc @mzazrivec

**Comment by AllenBW** [comment]
@simaishi lets not backport this one, i want to do another cut with the requests removed as that will be a large chunk of translations no longer necessary, should I remove the fine/yes tag?

**Comment by simaishi** [comment]
@AllenBW No problem, removed the flags.

**Pull request merged**
