### PR TITLE
Adjust specs so they work using act

### PR DESCRIPTION
**Pull request by Fryguy**

### CODE REVIEW

**Comment by Fryguy** [comment]
@kavyanekkalapu This didn't seem to solve it.  Can you take a look?  I added this in because the original travis.yml had chrome beta installed, but it's possible we don't need this.

**Comment by Fryguy** [comment]
Closing this as I don't think it fixes anything.

**Comment by Fryguy** [comment]
This PR is needed for act support, so reopening and repurposing a little.

**Comment by Fryguy** [comment]
@kavyanekkalapu Please review.

**Review by kavyanekkalapu — APPROVED** [review]

**Pull request merged**
