### PR TITLE
update sass package for s390x

### PR DESCRIPTION
**Pull request by Minal-Mahor**
Hi @Fryguy ,
update sass version to 1.34.0 in order to resolve following error:
```
ERROR in ./assets/sass/styles.sass
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
    ╷
369 │ $navbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !default;
    │                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss 369:42  @import
  node_modules/patternfly/dist/sass/_patternfly.scss 7:9                           @import
  client/assets/sass/_patternfly.sass 9:9                                          @import
  client/assets/sass/styles.sass 5:9                                               root stylesheet
    at processResult (/root/BUILD/manageiq-ui-service/node_modules/webpack/lib/NormalModule.js:582:19)
    at /root/BUILD/manageiq-ui-service/node_modules/webpack/lib/NormalModule.js:675:5
    at /root/BUILD/manageiq-ui-service/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /root/BUILD/manageiq-ui-service/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/root/BUILD/manageiq-ui-service/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /root/BUILD/manageiq-ui-service/node_modules/sass-loader/dist/index.js:54:7
    at Function.call$2 (/root/BUILD/manageiq-ui-service/node_modules/sass/sass.dart.js:90547:16)
    at _render_closure1.call$2 (/root/BUILD/manageiq-ui-service/node_modules/sass/sass.dart.js:79617:12)
    at _RootZone.runBinary$3$3 (/root/BUILD/manageiq-ui-service/node_modules/sass/sass.dart.js:27035:18)
    at _FutureListener.handleError$1 (/root/BUILD/manageiq-ui-service/node_modules/sass/sass.dart.js:25563:19)
 @ ./app.js 91:0-36

1 ERROR in child compilations
webpack 5.4.0 compiled with 2 errors in 169689 ms
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

### CODE REVIEW

**Comment by Fryguy** [comment]
I can't yarn install with this PR as is. Seems CI is having the same issue.

**Comment by Minal-Mahor** [comment]
> I can't yarn install with this PR as is. Seems CI is having the same issue.

set yarn version to 1.22.18 for s390x platform

**Comment by Fryguy** [comment]
This PR still fails.  I'm not sure why, but using yarn 3 on MacOS or Linux (CI is linux), it just fails: https://github.com/ManageIQ/manageiq-ui-service/runs/6471232342?check_suite_focus=true

**Comment by Minal-Mahor** [comment]
> This PR still fails. I'm not sure why, but using yarn 3 on MacOS or Linux (CI is linux), it just fails: https://github.com/ManageIQ/manageiq-ui-service/runs/6471232342?check_suite_focus=true

CI is running on x86_64 platform where yarn is set to 3.0.2. do we need to change yarn version for x86 architecture?

**Comment by Fryguy** [comment]
> CI is running on x86_64 platform where yarn is set to 3.0.2. do we need to change yarn version for x86 architecture?

No, the purpose of this change is that 1.22.18 should only apply to s390x until you figure out why yarn 3 is failing on s390x.  Other arches should use the latest.

**Pull request merged**
