### PR TITLE
Webpack 5

### PR DESCRIPTION
**Pull request by himdel**
Updates SUI to webpack 5.4, dropping a couple of obsolete plugins/loaders.

The bulk of the change is a change in how importing html files work - previously it would return an url for use in component definition, and create a corresponding entry in angular's `$templateCache`; now, it returns a the content in a string, which can be passed as the component template directly.

Also updates novnc to current version, to prevent `'return' outside of function [vendor/noVNC/utils/parse.js:38,2]`.

And drops yarn.lock for consistency with ui-classic (and to prevent all the commits full of yarn.lock).

And karma-webpack doesn't work with webpack5, running webpack before tests and using the built output works.

Closes #1691
Closes #1692
Closes #1695

### CODE REVIEW

**Comment by himdel** [comment]
@miq-bot remove_label wip

Works for me locally and travis is green, ready for reviews :)

**Comment by mzazrivec** [comment]
```
$ yarn build
yarn run v1.22.10
$ yarn build:git-hash && NODE_ENV="production" webpack --bail --progress --profile --config config/webpack.prod.js
$ node config/githash.js
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/milan/src/manage-iq/manageiq-ui-service/client/version/version.json'
```

**Comment by h-kataria** [comment]
> ```
> $ yarn build
> yarn run v1.22.10
> $ yarn build:git-hash && NODE_ENV="production" webpack --bail --progress --profile --config config/webpack.prod.js
> $ node config/githash.js
> internal/fs/utils.js:230
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, open '/home/milan/src/manage-iq/manageiq-ui-service/client/version/version.json'
> ```

/cc @himdel

**Comment by himdel** [comment]
Updated, sorry about the delay :)

I've just added a .gitkeep file to ensure the directory exists and the build can create the file again.

**Comment by Fryguy** [comment]
Gah sorry...this conflict was caused by #1694

**Comment by himdel** [comment]
Rebased on top of https://github.com/ManageIQ/manageiq-ui-service/pull/1694 :)

**Comment by Fryguy** [comment]
Backported to `lasker` in commit bf40a371144dba53193f4a3b8a5ef90184b60aff.

```text
commit bf40a371144dba53193f4a3b8a5ef90184b60aff
Author: Jason Frey <fryguy9@gmail.com>
Date:   Tue Feb 23 11:12:53 2021 -0500

    Merge pull request #1681 from himdel/webpack5
    
    Webpack 5
    
    (cherry picked from commit 8fbe42aa94f5c36993e0875ef828a1b0e6c11c75)
```

**Pull request merged**
