### PR TITLE
Wrong pending request count displayed in dashboard

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143824397

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes
@miq-bot add_label dashboard

**Comment by chriskacerguis** [comment]
@Fryguy PF lib has many security issues, do we merge or wait (this applies to pending PRs)?

**Comment by chriskacerguis** [comment]
Since the security issues existed before this, going to merge.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 381d2d063f23785536f5664d750ebebc0f268373
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Apr 17 19:23:59 2017 -0500

    Merge pull request #675 from chalettu/pending-request-count
    
    Wrong pending request count displayed in dashboard
    (cherry picked from commit 2d222ca9b2fd60991c6e747883971c258f1cedd1)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1443088
```

**Pull request merged**
