### PR TITLE
BZ#1498984-DB/LDAP User is not able to log into SSUI

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1498984

Reconfigure unsuccessful login attempt to purge user session
Delete X-Miq-Group header when purging session

### But show me the bulk goods 💐 
ldap

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW build fail.  Also, can you please add some tests (or improve what exists) :)

**Comment by simaishi** [comment]
@AllenBW Can you please create a separate PR for Fine branch? Cherry-pick isn't clean and the conflict is rather big, so it's better that conflict is resolved by you..  Thanks.

**Comment by AllenBW** [comment]
yes @simaishi this thing will be done!

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-ui-service/pull/1065

**Pull request merged**
