### PR TITLE
Add sass-lint guidelines, swaps warnings for errors

### LINKED ISSUE #282: Builds should fail on Linting warnings
In order to produce cleaned or standardized code I think that on linting errors (Sass lint, Eslint) and warnings Travis or CodeClimate (which ever does the check) should fail.

### PR DESCRIPTION
**Pull request by AllenBW**
Warnings don't fail our build, are rarely acknowledged, but errors will raise eyebrows

closes #282 

@chriskacerguis @himdel 

sorry everybody :-(  IT HAD TO BE DONE 😑

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Build failing due to changes.  @AllenBW do you want to address, or just let others?

**Comment by himdel** [comment]
@chriskacerguis , @AllenBW should we even still be running the linters as part of `gulp test`? Or rather, should we be running `gulp testonly` on travis instead? (So we'd use travis only for unit tests and codeclimate for linting.) WDYT?

**Comment by AllenBW** [comment]
@himdel I like this rather brilliant idea, only checking changed code for errors (saves the sanity of many), though flip side, ideally we don't want any code that would error in the repo, so having that almighty **check all teh things** kinda works out right now 🐑 🛡   

@chriskacerguis I can address, it'll take my mind off this webpack nonsense :shipit: or we can push linting solely to cc and distribute this burden amongst the many

**Comment by chriskacerguis** [comment]
@himdel GREAT idea.  In looking at things, using something like Hound CI would help here too.  @AllenBW make that happen.  

Great collaboration!

**Comment by chriskacerguis** [comment]
Closing this, going to use @himdel 's suggestion (and Hound CI)

**Comment by himdel** [comment]
@chriskacerguis .. we will still need the linter config even if we use CC or something for that, won't we? Meaning we probably do want the PR merged..?

**Comment by chriskacerguis** [comment]
@AllenBW is that the right file name?  .sass-lint.yml?  Should be it .scss-lint.yml

**Comment by AllenBW** [comment]
@chriskacerguis sass-lint is the correct name 🤘

**Comment by chriskacerguis** [comment]
Build fails due to sass linting errors (which this PR didn't cause).

**Pull request merged**
