### PR TITLE
BZ 1449362 - Refresh button in a dialog does not show in SUI

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/145218253

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label catalogs

**Comment by chalettu** [comment]
@miq-bot add_label blocker
@miq-bot add_label fine/yes

**Comment by AllenBW** [comment]
@chalettu can we get before and after ss?

**Comment by chalettu** [comment]
refresh_button
This is a demo of what it looks like if a field has show refresh button enabled on it.

**Comment by chriskacerguis** [comment]
bug fix, no UX review needed.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit fc1ea66915cc0749bda7620680952e212be8d9a2
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu May 11 07:09:01 2017 -0500

    Merge pull request #752 from chalettu/bz-1449362
    
    BZ 1449362 - Refresh button in a dialog does not show in SUI
    (cherry picked from commit 615c4cbfee97eb8e3ca0425c6e21f2a240b7912c)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1450096
```

**Pull request merged**
