### PR TITLE
Move all unit tests next to the units under test

### PR DESCRIPTION
**Pull request by jjlangholtz**
Lots of test file movement to move away from a parallel hierarchy to the
co-located pattern that is recommend in future angular versions.

A few dead files were removed and a few other files were renamed to keep
naming conventions consistent.

Going forward, unit tests should be placed at the same level as the
tested file with an identical filename except with a `.spec.js`
extension.

https://www.pivotaltracker.com/story/show/137095739

@miq-bot add_label euwe/no, refactoring

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@jjlangholtz welp, I'll wait until everything passes before I review ;)

**Comment by jjlangholtz** [comment]
Yeahhh forgot that we were ignoring eslint for tests...

**Comment by chriskacerguis** [comment]
@jjlangholtz so, FWIW - When we move to Angular2 all the tests will be redone, so I'd say let's keep it ignored for the time being.  @AllenBW thoughts?

**Comment by AllenBW** [comment]
@chriskacerguis yah that was my thought...

**Pull request merged**
