### PR TITLE
Update npm dependencies

### PR DESCRIPTION
**Pull request by himdel**
Fixes https://github.com/ManageIQ/manageiq-ui-service/issues/1672

Updates SUI to:
* webpack 4,
* angular 1.8.0,
* latest lodash,
* use `@pf3/select` instead of `bootstrap-select`, same as ui-classic,

Removes unused:
* react, redux, prop-types
* jest
* q, poppler, rxjs, request, merge

And fixes test failures caused by new chai complaining about nonexistent matchers.

and updates the minimum node/npm/yarn version to match ui-classic.

### CODE REVIEW

**Comment by himdel** [comment]
@miq-bot remove_label wip

**Comment by Fryguy** [comment]
This might backport strangely because of the yarn.lock, but we can deal with that when the time comes

**Comment by gtanzillo** [comment]
@h-kataria Please take a look and set to jansa/yesif ok to backport

**Comment by simaishi** [comment]
@himdel Can you create a separate PR for jansa branch? Minor conflicts on packages.json , but yarn.lock will need to be updated anyway.

**Comment by himdel** [comment]
Created https://github.com/ManageIQ/manageiq-ui-service/pull/1676 for jansa :)

**Comment by simaishi** [comment]
Backported to jansa via https://github.com/ManageIQ/manageiq-ui-service/pull/1676

**Comment by himdel** [comment]
Lightweight version of this for ivanchuk: https://github.com/ManageIQ/manageiq-ui-service/pull/1687

**Pull request merged**
