### PR TITLE
BZ#1523653-Replace patternfly-sass with patternfly's sass

### LINKED ISSUE #1329: Drop patternfly-sass in favor of sass within patternfly
https://github.com/patternfly/patternfly/commit/63e1e47f

patternfly-sass is no longer being maintained *BUT* there is now sass in `dist/sass` of patternfly! 🤗

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1523653
closes #1329

**Update** Ok so this is g2g save that outstanding pr in the patternfly repo, once a fix for that shows up we can merge this in

## Outstanding bugs with pffffffffsass (these should all be resolved before merging this in, hence wip)

* ~~https://github.com/patternfly/patternfly/issues/879 ❓ [ya don't see the cool little background on the login block](http://www.patternfly.org/pattern-library/application-framework/login-page/#/code) ‼️ https://github.com/patternfly/patternfly/pull/880~~ https://github.com/patternfly/patternfly/pull/883

### Using patternfly notification badges
screen shot 2017-12-08 at 10 01 24 am

### CODE REVIEW

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_label ux/review

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/review

**Comment by serenamarie125** [comment]
@miq-bot remove_label ux/approved

**Comment by AllenBW** [comment]
almost outta wip! almost! 🤔  will do!  🤗 🙇‍♀️ 🦁

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit ebdd839e29f01a30f42800b74e3696caa580403d
Author: Martin Hradil <himdel@seznam.cz>
Date:   Tue Dec 12 14:06:22 2017 +0000

    Merge pull request #1331 from AllenBW/enhancement/master/#1329-depreciate-patternfly-sass-use-patternflys-sass
    
    BZ#1523653-Replace patternfly-sass with patternfly's sass
    (cherry picked from commit 0db6896edea664c96bc8f348d98e3e6f313f7333)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1525082
```

**Pull request merged**
