### PR TITLE
BZ#1499692-Added Loading indicator to Dialogs

### PR DESCRIPTION
**Pull request by chalettu**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1499692

### CODE REVIEW

**Comment by AllenBW** [comment]
@chalettu can yah provide a status update on the what work is on progress for this one?

**Comment by chalettu** [comment]
We use dialogs in 3 places in SUI and so far in this PR I got 1 of the 3 places working where we use dialogs and its tests updated.  Still have custom button details and service reconfigure pages to go for fixing code and tests.

**Comment by chalettu** [comment]
@miq-bot add_label gaprindashvili/yes
@miq-bot add_label enhancement
@miq-bot add_label ux/review

**Comment by chalettu** [comment]
Screenshot of loading indicator for dialogs
loading_indicator

**Comment by Loicavenel** [comment]
@chalettu looks good to me..
@serenamarie125 Should we add more text to be more explicit? "Loading Dialog"

**Comment by serenamarie125** [comment]
I think the current text works fine! @AllenBW

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_label ux/review

**Comment by simaishi** [comment]
@chalettu @AllenBW The BZ has cfme-5.8.z flag. Is it ok to backport to Fine branch?

**Comment by AllenBW** [comment]
@simaishi are there any conflicts? This pr touches many files... if I was a betting person, would suspect there would be a few conflicts... 🤔

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 293a5fb5e20978c253d74e442035fd8f32142902
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Tue Dec 12 09:42:49 2017 -0500

    Merge pull request #1258 from chalettu/dialog-loading-fix
    
    BZ#1499692-Added Loading indicator to Dialogs
    (cherry picked from commit 8a64b773bb1a1a623c81463c1cc9adb93cd9b3d1)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1525091
```

**Comment by simaishi** [comment]
> are there any conflicts?

I ask if I should even attempt to backport first (as a fix could be something completely different for different branches) 😄 

I tried it now, all but 1 file is conflicting... marking as `fine/conflict`

```
Changes to be committed:

	modified:   client/app/states/catalogs/details/details.html

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   client/app/states/catalogs/details/details.state.js
	both modified:   client/app/states/catalogs/details/details.state.spec.js
	both modified:   client/app/states/services/custom_button_details/custom_button_details.html
	both modified:   client/app/states/services/custom_button_details/custom_button_details.state.js
	both modified:   client/app/states/services/custom_button_details/custom_button_details.state.spec.js
	both modified:   client/app/states/services/reconfigure/reconfigure.html
	both modified:   client/app/states/services/reconfigure/reconfigure.state.js
	both modified:   client/app/states/services/reconfigure/reconfigure.state.spec.js
```

**Comment by AllenBW** [comment]
@chalettu can you look into possibly making a separate fine pr for this?

**Comment by chalettu** [comment]
Yeah, I will start on it now that this one got merged.

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq-ui-service/pull/1341

**Pull request merged**
