### PR TITLE
Fixed dialog field dynamic refresh

### PR DESCRIPTION
**Pull request by chalettu**
This is the second part of https://github.com/ManageIQ/ui-components/pull/246.  In order to test out the fix for that PR, we had to fix field dynamic refresh in SUI and also bump ui-components to take in the fix from 246.
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by AllenBW** [comment]
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1539871

**Comment by AllenBW** [comment]
@chalettu any chance we can get a gif of this in action?

**Comment by chalettu** [comment]
dynamic_refresh

**Comment by AllenBW** [comment]
@chalettu bz reads:

> "Add to shopping cart" button remain disabled after refresh on some dialog fields in SUI.

any chance we can get a gif of this issue resolved?

**Comment by chalettu** [comment]
Here is a gif of the issue resolved
dynamic field refresh

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 13910e7528ffbf7c6ada5055db03d936b0c8b5cd
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Wed Feb 7 15:55:23 2018 -0500

    Merge pull request #1380 from chalettu/dynamic_dialog_field_refresh
    
    Fixed dialog field dynamic refresh
    (cherry picked from commit 6bf479c03afb666daa618078ed3f769eb532cb57)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1543180
```

**Pull request merged**
