### PR TITLE
BZ#1470868 PT#148992591  Adds filter alias to dashboard retirement buttons

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/148992591
https://bugzilla.redhat.com/show_bug.cgi?id=1470868

~Unmergable till https://github.com/ManageIQ/manageiq-ui-service/pull/873 makes it in~

retire-alias

@Loicavenel @serenamarie125 @chriskacerguis  please checkout wording, maybe change it to something else? 

🌮 💃 

can totally merge this one in now!

### CODE REVIEW

**Comment by AllenBW** [comment]
@chriskacerguis This can totally get in now! 💃

**Comment by chriskacerguis** [comment]
ping @Loicavenel @serenamarie125

**Comment by Loicavenel** [comment]
good for me

**Comment by serenamarie125** [comment]
@AllenBW There's not a lot of description here as to what you've done, so instead of me commenting on things which are unrelated to this PR, can you explain what has been changed with this PR?  (for example a colon is included in the retirement filter chips now, is that due to this PR)>

**Comment by AllenBW** [comment]
@serenamarie125 fulfilled the ask of the ref. Above you see the after, here is the before: 

screen shot 2017-08-29 at 5 14 52 pm

Colons were always there, can't really change them, but now we use words instead of long alpha numeric strings

**Comment by serenamarie125** [comment]
The fact that we can get directly from the dashboard to a filtered view for Retiring Soon & Not Retired makes me 😃 👍 

@AllenBW I've never seen a time based filter work like this ... is that what you've added?  

I'm just concerned with the fact that the filter chips/pills ( whatever we call them ) don't make much sense.  If this was there before, let me know and I will approve this PR and open an Issue.

**Comment by AllenBW** [comment]
@serenamarie125  Yeah this (from dashboard to filtered view) was there before, except it made even less sense (above screen shot) cuz the filter values couldn't be aliased (meaning we had to see the raw value).  If there is wording you would feel better communicates the three selections, `retiring soon`, `retired`, or `not retired`, would be glad to change it up!

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved
@miq-bot remove_label ux/review

**Pull request merged**
