### PR TITLE
Update nav wording and breadcrumbs for services/catalogs

### PR DESCRIPTION
**Pull request by jjlangholtz**
https://www.pivotaltracker.com/story/show/143533253
https://www.pivotaltracker.com/story/show/143533197

@miq-bot add_label fine/yes, bug, services, catalogs

### CODE REVIEW

**Comment by chriskacerguis** [comment]
No UX changes, just wording.

**Comment by chriskacerguis** [comment]
@jjlangholtz travis failed.

**Comment by chriskacerguis** [comment]
Updated per UX guidelines.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 6c78d5382c0e6080fe5f1c094c9b35d9206f3816
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Apr 11 16:09:48 2017 -0500

    Merge pull request #667 from jjlangholtz/update-nav-wording
    
    Update nav wording and breadcrumbs for services/catalogs
    (cherry picked from commit 02fc569fca9c1054a02204e5fd935854c5c0374b)
```

**Pull request merged**
