### PR TITLE
[EUWE] Enabled visibility to be conditional for Service dialog

### PR DESCRIPTION
**Pull request by chalettu**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1426255.  This is a back ported fix. 

Service Dialog - Element visibility on condition is not working in Self-Service portal

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label euwe/yes
@miq-bot add_label bug

**Comment by chalettu** [comment]
bz-screenshot
Screenshot of fix in action

**Comment by chalettu** [comment]
@simaishi , This PR addresses the hotfix you were working on.

**Comment by simaishi** [comment]
@chalettu can you reference the 'master' PR?

**Comment by chalettu** [comment]
The fix for this is on the Master branch is in PR https://github.com/ManageIQ/manageiq-ui-service/pull/574

The accompanying required fix for EUWE was in PR https://github.com/ManageIQ/manageiq-ui-service/pull/580

**Comment by simaishi** [comment]
https://github.com/ManageIQ/manageiq-ui-service/pull/574 only touches `client/app/core/dialog-field-refresh.service.js`.  So I'm trying to locate which master PR changed `client/app/components/dialog-content/dialog-content.html`...

**Comment by chalettu** [comment]
This file underwent a lot of changes between EUWE and master.  The changes that apply and fixed this PR don't have a corresponding PR in Master that is specific to this fix.

**Comment by simaishi** [comment]
OK, thanks for the clarification.  @chriskacerguis please approve if this is good to go.

**Pull request merged**
