### PR TITLE
[DARGA] Fixed bug with tooltip not displaying correctly

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143276293

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label darga/yes
@miq-bot add_label bug
@miq-bot add_label services

**Comment by chriskacerguis** [comment]
@simaishi look, I didn't merge it !!! ;)

**Comment by simaishi** [comment]
@chalettu Is this Darga only issue?  If not, please reference 'master' PR.

**Comment by chriskacerguis** [comment]
@simaishi yes, this looks to be Darga only.

**Pull request merged**
