### PR TITLE
Create global variable for version of Patternfly

### PR DESCRIPTION
**Pull request by chalettu**
This was added in support of https://github.com/ManageIQ/ui-components/pull/249 which deals with different elements based on patternfly version in UI-components repo. 
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1539862

### CODE REVIEW

**Comment by chalettu** [comment]
I am leaving this in WIP state until https://github.com/ManageIQ/ui-components/pull/249 gets merged and we can bump the ui-components version in the package.json file.

**Comment by chalettu** [comment]
Screenshot of what multiselect looks like when this variable is set properly 
multiselect

**Comment by AllenBW** [comment]
cc @simaishi 
before this pr gets merged, https://github.com/ManageIQ/ui-components/pull/249 needs to make it in, and we'll need to bump the sui version of ui -omponents

**Comment by himdel** [comment]
The ui-components change was released as `@manageiq/ui-components@1.0.10`, and `@manageiq/ui-components@1.1.0`.

Feel free to upgrade to either (the difference is just a few recent `gaprindashvili/no` PRs), but note that only 1.0.* can be backported to gaprindashvili.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 7119a75a8d23f87b313dffc8285b418fc5b23642
Author: Martin Hradil <himdel@seznam.cz>
Date:   Fri Feb 9 13:18:13 2018 +0100

    Merge pull request #1379 from chalettu/multiselect
    
    Create global variable for version of Patternfly
    (cherry picked from commit 0039298975fb02ab978fea1061924d1c1f5cc741)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1544039
```

**Pull request merged**
