### PR TITLE
Resource Details Page - ie: bulk cards, everything is a card

### LINKED ISSUE #931: Rework Resource Details Level page per the new UX design
I want to see most of the details on one page.  We will need to Update Resource page to new UX

screen shot 2017-09-11 at 11 04 01 am

screen shot 2017-09-11 at 11 54 51 am

**ToDo**
- [x] rename vm.details to be resource.details throughout app
- [ ] scaffold basic layout, transfer simple data into new layout
- [ ] add timeline and power state data
- [ ] add system metrics
- [ ] ensure unique url for resource-details state
- [ ] [Aggregate status cards](http://www.patternfly.org/pattern-library/cards/aggregate-status-card/) for 1st row info 
- [ ] info status cards for 1st row info (don't exist in pf)

** Stories Included **
- As a user, I want to see utilisation graph at the top of the Resource Details Level for last 30 days
- As a user, I want to see events at the top of the Resource Details Level for last 1 day

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497733

### PR DESCRIPTION
**Pull request by AllenBW**
https://docs.google.com/document/d/1kvWtq4xFX4Upqm5dfws8g6Z4OxBOzwjBH3hmIv608cc
https://bugzilla.redhat.com/show_bug.cgi?id=1497733
closes #931

## TODO
- [x] reformat retirement time date as per pm/ux guidance 

## Now with timeline power data (from the last 7 days)
resource-details

### i found something with custom attributes!
screen shot 2017-10-02 at 2 40 00 pm

## Keep in mind, db I have doesn't have hourly stats for metric rollups... (as in nowish)
resource-details

## UXD Mock
screen shot 2017-09-12 at 8 34 38 am

## Work done in support of this pr (moved from the needs list below)
- [x] *DEV*  identify the origin and implement timeline data, it might be event stream data... https://github.com/ManageIQ/manageiq-api/pull/65
- [x] *DEV* identify and implement provider imaging in first row first card
- [X] add support to ang-pf, custom tooltip on diskusage component https://github.com/patternfly/angular-patternfly/pull/618
- [X] https://github.com/ManageIQ/manageiq/pull/15808
- [x] #978 needs to be completed, unsustainable collections api service for metrics rollup jazz
- [x] ~~info status card, similar to http://www.patternfly.org/pattern-library/cards/aggregate-status-card/~~ oh look here it is! https://github.com/patternfly/angular-patternfly/pull/630 and https://github.com/patternfly/angular-patternfly/pull/632
- [x] https://github.com/ManageIQ/manageiq-ui-service/issues/1039
- [x] *UX* Updated first row to accommodate extended `ip_address` and `hostnames`
- [x] ~https://github.com/patternfly/angular-patternfly/issues/649 (for popover in info-status-cards)~

### CODE REVIEW

**Comment by AllenBW** [comment]
Update for today, finished off smart state analysis, did some more work on disk usage, began work on timeline, ran into trouble restoring a db with metric rollup info, will continue to troubleshoot that in the coming days

**Comment by AllenBW** [comment]
closes #931

**Comment by AllenBW** [comment]
@serenamarie125 wanted to touch base on the info status card mentioned in our last SUI/UXD Sync,   (used in the first two columns of the first row [in the mock for this work](https://docs.google.com/document/d/1kvWtq4xFX4Upqm5dfws8g6Z4OxBOzwjBH3hmIv608cc/edit#))

**Comment by serenamarie125** [comment]
Hey @AllenBW this card type has not yet been developed in PatternFly ... I think that contributing it back to PatternFly first would make a lot of sense, but unsure of your timeline?

**Comment by AllenBW** [comment]
During that meeting you had mentioned that there might be resources working on it? Was checking as I didn't want to duplicate efforts.

**Comment by serenamarie125** [comment]
@AllenBW we weren't able to get anyone on it

**Comment by AllenBW** [comment]
@serenamarie125 new question! ok **disk usage** tootip, my understanding is ya wanta display usage, title, and dev type?

**Comment by AllenBW** [comment]
Totally did something today!  Added custom tooltip to bar chart

**Comment by Loicavenel** [comment]
@AllenBW Average will make sense....

**Comment by AllenBW** [comment]
Today
* refactored utilization chart to support default value, custom units, added pf-empty-state component
* refactored resource details component, removed stale code/code cleanup
* added metrics rollup service, well kinda, got sidetracked with #978

**Comment by AllenBW** [comment]
Today
* more bug fixes, finished metric rollup service, finished Utilization Card
*

**Comment by AllenBW** [comment]
@serenamarie125 @Loicavenel @chriskacerguis  Original mock had a `timeline card with power activity`.  For this first past, I propose we stick to initial request implementation as implementing the newly updated `configurable timeline card` will substantially increase amount of effort required to complete this ask.

While we're on the topic of the `timeline card with power activity` I do not know what data to plot here (can't a resource in ops ui that returns any timeline results) and the attributes returned by metrics_rollup do not appear to apply ([as per the list here, no mention of power activity](https://github.com/ManageIQ/manageiq/pull/15695)).  Also unsure of who to ask about ☝️ , @jntullo ? @imtayadeway ? (apologies for being a 💊 , feel free to defer me to someone else)

For the time being, gonna shift my efforts to building out the `info status card` for angular-patternfly until the clarification requested above becomes available

**Comment by jntullo** [comment]
@AllenBW not sure what you want to plot, but there are various power activities available (depending on the resource). from the examples in my [PR](https://github.com/ManageIQ/manageiq/pull/15695), for a service:
`
assoc_ids: {:vms=>{:on=>[10000000003077, 10000000003090], :off=>[]}}
` 
shows the specific vms that are on and off, and the following attrs just show the counts for the service
```
derived_vm_count_on: 2,
 derived_host_count_on: 0,
 derived_vm_count_off: 0,
 derived_host_count_off: 0,
```

**Comment by AllenBW** [comment]
@jntullo Thanks for the quick reply!  I have no idea what I want (am supposed to) plot either, @serenamarie125 @Loicavenel does the above map to Power activity?

**Comment by Loicavenel** [comment]
@AllenBW I am not sure here, I will hope there is an API to get all events from a define resources... Can someone tell us how it works in OPS UI? because I can simply go there click on timeline, select Power and all is there...

I know Events are part of association of VMs

**Comment by AllenBW** [comment]
Didn't do anything much here today **BUT** did this https://github.com/patternfly/angular-patternfly/pull/630

**Comment by AllenBW** [comment]
screen shot 2017-09-21 at 4 58 15 pm
screen shot 2017-09-21 at 4 59 26 pm

began work on the info status cards...

**Comment by serenamarie125** [comment]
@AllenBW This is looking good with all this content coming!

The top row of status cards should all be the same height.  Right now i think the spacing in some of that is a bit off, so that may help.  Maybe we can chat through this tomorrow in our sync meeting

**Comment by AllenBW** [comment]
@serenamarie125 yeah! we can talk about it tomorrow, gonna need a pixel height if ya want them to all be the same, remember, the ip address and hostnames... there can be many... the case where that list gets stupid long might not be much of an edge... maybe if each card has a fixed height but you can scroll in it? 🤔 tomorrow tomorrow!

**Comment by Loicavenel** [comment]
one comment on my side. We have Timeline just for Power Event at this level, then we should may be put that in the Title and not just "Timeline"..

**Comment by AllenBW** [comment]
Last row pegged at 300px, the approx height of a  ss analysis card containing eight rows

**Comment by AllenBW** [comment]
@chriskacerguis gently touching base on the disk I/O info....

**Comment by chriskacerguis** [comment]
@AllenBW still waiting for reply from the appropriate teams...

**Comment by chriskacerguis** [comment]
@AllenBW @serenamarie125 per @blomquisg here is the things we are collecting:

> Amazon:
>  * CPU
>  * Disk [read bytes and write bytes]
>  * Network
> 
> Azure
>  * CPU
>  * Network
>  * Memory
>  * Disk [read bytes and write bytes]
>
> Google:
>  * CPU
>  * Disk [read bytes and write bytes]
>  * Network
> 
> Kube:
>  * CPU
>  * Memory
>  * Network
> 
> OpenStack
>  * CPU
>  * Memory
>  * Swap
>  * Disk [read bytes and write bytes]
>  * Network
> 
> OVirt:
>  * CPU
>  * Memory
>  * Disk [read bytes and write bytes]
> 
> VMWare:
>  * CPU
>  * Memory
>  * Disk [read bytes and write bytes]
> 
> Providers without metrics at all:
> 
> * Ansible
> * Foreman
> * Hawkular (they have "Live Metrics", so I don't really know what they have)
> * Lenovo
> * Nuage
> * SCVMM
> 
> the current usage is available but it's generally collected in inventory collection


Now, having said that, I'm not sure we are exposing the IO in the API.  @gtanzillo, @imtayadeway, or @jntullo is that something we expose?

**Comment by Loicavenel** [comment]
@chriskacerguis @blomquisg  I look in to OPS UI to validate what we see, aand there are some delta:

Amazon: Correct -> CPU in %, Network and Disk in Kb/second
Azure:  Correct -> CPU in %, Memory in MB, Network and Disk in Kb/second
Google: Correct -> CPU in %, Network and Disk in Kb/second
Kube:  Correct -> CPU in %, Memory in MB and Disk in Kb/second.. We don't use it today

OpenStack: CPU in %, Memory in MB, Network and Disk in Kb/second... I don't know what is Swap
Ovirt: There is more: CPU in MHz, Memory in MB, Network and Disk in Kb/second
Vmware: There is more here: CPU in MHz, Virtual CPU State in %, Memory in MB, Network and Disk in Kb/second

**Comment by AllenBW** [comment]
@chriskacerguis @Loicavenel awesome leg work tracking this down! List of info that we expose via metric rollup can be found https://github.com/ManageIQ/manageiq/pull/15695 and we have the following attributes that match accordingly: 

* cpu in % 👉 `cpu_usage_rate_average` ‼️ used for cpu utilization chart
* network 👉 `net_usage_rate_average` ‼️ used nowhere!!!! 
* mem 👉 `derived_memory_used`  ‼️ used for mem utilization chart
* disk storage  👉 `disk_usage_rate_average ` ‼️ used for storage utilization chart

Unable to identify anything from the aforementioned list that might indicate `Disk I/O`, unsure from where this ought to originate 😕

**Comment by Loicavenel** [comment]
@AllenBW I will suspect Disk usage rate is also Disk I/O. Do you have some sample data?

**Comment by chriskacerguis** [comment]
@AllenBW is there anything like read bytes and write bytes for disk?  Usage is the actual usage (e.g. 50 out of 100GB)

**Comment by AllenBW** [comment]
@Loicavenel i understood that to be amount of storage used at the time the metrics was collected, again, gents, the list is https://github.com/ManageIQ/manageiq/pull/15695  if you can find anything that might fit, please let me know, I was unable to identify anything that would resemble storage read or write

**Comment by chriskacerguis** [comment]
@AllenBW let's just plan to have a "no info available".  @blomquisg says it is there, but perhaps we don't have any test data??

@serenamarie125 @Loicavenel what do you think?  @blomquisg says it is there, but we can't find it.  Would you rather just have the "no info available" card until we sort this out (which seems like the easiest) or how you all like to work on a new layout and we can use that until we figure out where the data is?

**Comment by AllenBW** [comment]
@chriskacerguis @Loicavenel  or whoever wants to chime in, gonna need help identifying the attribute we care about (or detecting if **none of the above** is the correct response...)

The question, what we want to plot on event for timeline? Power Activity event stream...

```
{
  "attributes": [
    "availability_zone_id",
    "chain_id",
    "container_group_id",
    "container_group_name",
    "container_id",
    "container_name",
    "container_namespace",
    "container_node_id",
    "container_node_name",
    "container_replicator_id",
    "container_replicator_name",
    "created_on",
    "dest_ems_cluster_id",
    "dest_ems_cluster_name",
    "dest_ems_cluster_uid",
    "dest_host_id",
    "dest_host_name",
    "dest_vm_location",
    "dest_vm_name",
    "dest_vm_or_template_id",
    "ems_cluster_id",
    "ems_cluster_name",
    "ems_cluster_uid",
    "ems_id",
    "ems_ref",
    "event_type",
    "full_data",
    "generating_ems_id",
    "host_id",
    "host_name",
    "id",
    "is_task",
    "message",
    "middleware_deployment_id",
    "middleware_deployment_name",
    "middleware_server_id",
    "middleware_server_name",
    "physical_server_id",
    "source",
    "target_id",
    "target_type",
    "timestamp",
    "type",
    "username",
    "vm_location",
    "vm_name",
    "vm_or_template_id"
  ],
  "virtual_attributes": [
    "href_slug",
    "region_description",
    "region_number"
  ],
  "relationships": [
    "availability_zone",
    "container_group",
    "container_node",
    "container_replicator",
    "dest_host",
    "dest_miq_template",
    "dest_vm",
    "dest_vm_or_template",
    "ext_management_system",
    "generating_ems",
    "host",
    "middleware_server",
    "miq_template",
    "physical_server",
    "service",
    "target",
    "vm",
    "vm_or_template"
  ],
  "subcollections": [],
  "data": {}
}
```

Does any of the following appear to match? This list is the result of `OPTIONS http://localhost:3000/api/event_streams`

**Comment by chriskacerguis** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1497733

**Comment by Loicavenel** [comment]
@AllenBW I am not sure I get it, are you talking you taking about information to show when we click on a dot in the timeline?

**Comment by AllenBW** [comment]
@Loicavenel yep, talking about the points we want to plot on the timeline, I am struggling to identify what this data is, where it comes from.

**Comment by Loicavenel** [comment]
@AllenBW Timeline is already implemented in CF today, you can look here.. from API, you should have a list of events, each event should have a category to group them..

**Comment by AllenBW** [comment]
@Loicavenel yes, I have played with cf timeline extensively in pursuit of any info to help this along, sadly CF today does not use the for the timeline data, so it isn't much help to us at the moment

**Comment by AllenBW** [comment]
So with this call `GET http://localhost:3000/api/event_streams?filter%5B%5D=target_type%3DVmOrTemplate&filter%5B%5D=timestamp%3E2017-01-01&attributes=vm.power_state&expand=resources`

we can manage an response something along the lines of 
```
    {
      "href": "http://localhost:3000/api/event_streams/10000000028650",
      "id": "10000000028650",
      "event_type": "request_vm_poweroff",
      "message": "Policy resolved successfully!",
      "timestamp": "2017-06-02T21:22:10Z",
      "source": "POLICY",
      "created_on": "2017-06-02T21:22:10Z",
      "type": "MiqEvent",
      "target_type": "VmOrTemplate",
      "target_id": "10000000001078"
    },
```

or 

```
    {
      "href": "http://localhost:3000/api/event_streams/10000000029370",
      "id": "10000000029370",
      "event_type": "vm_poweroff",
      "message": "Policy resolved successfully!",
      "timestamp": "2017-06-02T22:56:20Z",
      "source": "POLICY",
      "full_data": {
        "source_event_id": "10000000029357"
      },
      "created_on": "2017-06-02T22:56:20Z",
      "type": "MiqEvent",
      "target_type": "VmOrTemplate",
      "target_id": "10000000001078"
    }
```

**Comment by Loicavenel** [comment]
@AllenBW and you get many events... not only the last one, correct?

**Comment by AllenBW** [comment]
@Loicavenel Many events, yep!

**Comment by chriskacerguis** [comment]
Another question that I had for @Loicavenel and @serenamarie125 if a person does not have the proper permissions for a specific dataset (i.e. a card) what should we show?

**Comment by chriskacerguis** [comment]
@serenamarie125 @Loicavenel disregard [this comment](https://github.com/ManageIQ/manageiq-ui-service/pull/910#issuecomment-333938439), @Loicavenel clarified how he would like the [RBAC setup here](https://github.com/ManageIQ/manageiq-ui-service/issues/1054) and it does not include such fine grained controls

**Comment by AllenBW** [comment]
@serenamarie125 
screen shot 2017-10-05 at 9 48 30 am

**Comment by AllenBW** [comment]
@Loicavenel aside from the top row, this is good for you to play with and give feedback on!

**Comment by AllenBW** [comment]
@serenamarie125 
screen shot 2017-10-06 at 10 02 31 am

Updated provider card for memory to be on new line (as per your feedback in ux document)

**Comment by AllenBW** [comment]
@chriskacerguis Removing WIP because this PR full fills original ask. (probably shouldn't merge quite yet tho...)

**Comment by AllenBW** [comment]
@serenamarie125 @chriskacerguis @Loicavenel building on last comment, as per SUI UX Design sync on thursday are currently waiting for:
1. high fidelity mocks for resource details component (this work)
2. mocks that reconfigure the first row to use a quad icon to make more space for large fields
3. mocks that reconfigure the first row to make more space for large fields without a quad icon

**Comment by serenamarie125** [comment]
@allenbw I updated the low fidelity in the design doc this morning and tagged yah.  You are correct in the high fidelity.  Someone will start that on Monday

**Comment by chriskacerguis** [comment]
@AllenBW could you please put a copy of the wireframe in this PR?

**Comment by serenamarie125** [comment]
Updated low fidelity design can be found here:
vmdetails

**Comment by serenamarie125** [comment]
@AllenBW I just realized that your implementation of the timeline card allows the ability to zoom and has the viewport.  This card should just have the timeline piece itself, showing the last 7 days.  As noted in the documentation, the user should be able to drill down to change the range or even add more items to the timeline in context of that VM.

**Comment by serenamarie125** [comment]
@AllenBW the cards in row 3 should have the same height

**Comment by AllenBW** [comment]
@serenamarie125 Cards in row 3 do indeed have the same height. As for the previous comment, event stream data for power events is being displayed over a 7 day period.  Sometimes you'll have events occur seconds apart sometimes hours. I can remove the timeline view on the bottom, but would not recommend removing the ability to zoom in and out of the graph, otherwise it becomes useless to the user when there is a great deal of events that occur very close in time

**Comment by AllenBW** [comment]
I just want to reiterate that @skateman can not promise the angular quad icon component for this release, hence my continue request for a solution that does not rely on that design element

**Comment by AllenBW** [comment]
Updated first row card layout as per google doc change
screen shot 2017-10-12 at 9 07 51 am

**Comment by Loicavenel** [comment]
@chriskacerguis After talking with Serena, couple of comments here.. A
- Timeline: We are looking at Power events, and I am not sure we will have so many of these events in the seconds apart. If this is the case, you will see a like a target that are indicating there are multiple points.. Then  you can click on it to enter is the full timeline view where you can zoom in and out.
- Why do you say you will not have Disk/IO. I look in our demo lab, there are some for vmware, Rhev, OpenStack, Amazon, Azure and Google. Now, on Vmware, Amazon it was flat..

**Comment by chriskacerguis** [comment]
@Loicavenel 

> We are looking at Power events, and I am not sure we will have so many of these events in the seconds apart.

I have seen that happen many times in my career, where severs will start to "flap".  Regardless, we can build it that way.  Please correct me if I am wrong, but didn't we decide to push the event UI to an errata release?

> Why do you say you will not have Disk/IO.  

We have looked over what we are getting back from the API, and we aren't seeing anything that is would be what we are looking for.

**Comment by AllenBW** [comment]
@Loicavenel access to the demo lab would be great!  As has been posted in the past in this pr, eventstreams nor metrics rollups has any data that resembles disk IO

As for power events, they can and do indeed occur seconds apart, when this functionality was built, the appliance used would usually have a request and than either a success or fail of that request( power operation) occur within such timeline.  As stated in the past for the first go of the resource details page there will not be any card drilldowns.  We can collapse closely related events into one, but need guidance from UX on the following topics:
1. What a multi event tooltip looks like
2. At what closeness interval should events be collapsed

**Comment by Loicavenel** [comment]
@chriskacerguis Understood from call today, you are block here on some design. Could you clarify?

**Comment by chriskacerguis** [comment]
@Loicavenel we are still awaiting answers from https://github.com/ManageIQ/manageiq-ui-service/pull/910#issuecomment-335283464

**Comment by serenamarie125** [comment]
@chriskacerguis here's the alternative for no Quad Icon.  Multiple IP addresses shouldn't be an issue.  
vmdetails
The larger icon is the OS icon - and a small power state icon is before the VM.

**Comment by serenamarie125** [comment]
@chriskacerguis as for the Disk IO, it's not my call if this is ok to remove.  But, if @Loicavenel is ok with it not being delivered, here's the design 
vmdetails - noquadicon -nodiskio

**Comment by chriskacerguis** [comment]
@serenamarie125 what do you mean by "Multiple IP addresses shouldn't be an issue."?

**Comment by serenamarie125** [comment]
@chriskacerguis the card will remain larger, regardless of the Quad Icon usage.  
I'm not sure what the issue is ... can you help us understand?

**Comment by chriskacerguis** [comment]
@serenamarie125 forgive me, not understanding (need more coffee).  A machine could have multiple IP addresses...or "worse" multiple IPv6 addresses.  How should be display those?

**Comment by chriskacerguis** [comment]
Lots of good discussion here :). So, just to make sure we are all on the same page, here is a summary of what we still need clarity on (as of this "post").

1. @Loicavenel Should we leave or keep the disk i/o card.  At present, we cannot find the data in the API.

2.  @serenamarie125 In the top card, there can be multiple IP addresses (they can get very, very long).  Do we just show the primary IP address, or do we show multiple.  If we just show the a single IP address, how does the end-user see all the IP addresses?  If we show multiple, how do we "scale" the card?  Just for reference, here is an IPv6 address `2001:db8:1234:0000:0000:0000:0000:0000` as you can see VERY big:

3.  @Loicavenel @serenamarie125 We will see power events seconds apart.  The proposed soltuion is to show a "target" then let the user click on that and go to the event UI.  That is something that got shifted to an eratta.  How should we handle this?  Should we just let the dots overlap until we get the event UI?  Do we add a zoom button until we get the event UI?  Please let us know?

4.  @serenamarie125 do you have a timeline for the hifi mocks that you stated you were working on?  I suspect those may help answer some questions.

/cc @chessbyte @ohadlevy

**Comment by Loicavenel** [comment]
@chriskacerguis 
1 - I will review that with Allen this Monday, I scheduled a call with it
2 - We worked on it with Serena, she is going to provide a design, we have a solution.
3 - In OpsUI, When you click on the target, it does list all the events below the timeline. Can we simply open a pop-up with all messages and date? we don't care about all the other information. @serenamarie125.. I did a test and even with Zoom-in I have cases where you cannot separate all events then we need to offer a click option on target.

**Comment by AllenBW** [comment]
🤘 🌮 💃

**Comment by serenamarie125** [comment]
Here's what I came up with for the IP Addresses, does this make sense?

ipaddressinfo

**Comment by chriskacerguis** [comment]
@serenamarie125 YES!  Love it!!!!  Much awesomeness.

**Comment by serenamarie125** [comment]
@chriskacerguis I'm not sure I understand your #3 ... what's been shifted to an errata ?

The TimelineView already handles multiple items in a very short time period by enlarging the icon, as well as providing a different tooltip.  Do you see that happening now ?

**Comment by serenamarie125** [comment]
@chriskacerguis re: #4, let me get you an ETA - I'm assuming sometime next week on the high fidelity.  The question is which version of the above do we want included in the high fidelity 😂

**Comment by AllenBW** [comment]
Ok... i have a minor concern about the ip address approach, whats say a user wants to copy one of those addresses?  As a tooltip they wouldn't be able too :-/

**Comment by chriskacerguis** [comment]
> whats say a user wants to copy one of those addresses?

@AllenBW @serenamarie125 maybe a modal instead?

**Comment by AllenBW** [comment]
@chriskacerguis If the vision for each card is to have a "deeper dive" yeah a modal would make sense, maybe indicate there are more than one... deeper dive lists the full Monte

**Comment by serenamarie125** [comment]
@AllenBW according to my PF guru @jeff-phillips-18 well, you can customize the tooltip, like we do with our charts you should be able to select and copy as well.  Please reach out to him with questions re: implementation

**Comment by AllenBW** [comment]
@serenamarie125 OH [then you mean a popover, not a tooltip](https://angular-ui.github.io/bootstrap/#!#popover)

yeah we could do a popover, tooltips are typically things only active on::hover where popovers have more flexibility with open and closing

**Comment by serenamarie125** [comment]
@AllenBW I would check with Jeff - for some reason i think it's actually the PF InfoTip, but not 100% sure

**Comment by AllenBW** [comment]
@serenamarie125 will do, couldn't find anything on http://www.patternfly.org/angular-patternfly/#/api

we'll do popover for it though

**Comment by jeff-phillips-18** [comment]
Popover/Info tip is likely the best way to go.

**Comment by serenamarie125** [comment]
@AllenBW Can we see what your current state looks with including data ?

**Comment by AllenBW** [comment]
@serenamarie125 the first post of this pr always has the current state

**Comment by AllenBW** [comment]
As for the data, sadly no one resource has it all, and some of it (timeline) I need a hand to get

**Comment by serenamarie125** [comment]
@chriskacerguis I hear there is an issue with the timeline.  I commented a few days ago, but haven't seen a response.  We do visualize multiple events in a small time period in a different way.  See the PF Timeline demo screenshot below:
screen shot 2017-10-16 at 11 16 43 am

**Comment by chriskacerguis** [comment]
@serenamarie125 sorry, I must have missed your comment.  So, yes, I understand the bullet with the "target" (not sure what else to call it) and popup.  My understanding is that when you click on the "target" (from the timeline on the My Services page) you go to the event page that looks like what you posted (https://github.com/ManageIQ/manageiq-ui-service/pull/910#issuecomment-336920168) however, (and this addresses your question) we will not have an event page...as that was moved to a later version (errata or next version...I'll leave it to @Loicavenel to decide), so what should we do if someone wants to see it?  Just leave it as shown (popup with "group of X events")?

**Comment by AllenBW** [comment]
@serenamarie125 @Loicavenel Working on the popover part presently, its not a quick implementation sadly, it requires observing and compiling the html block passed into the info status card... though maybe @jeff-phillips-18 you have experience with this? 

anywho, the power state has been consolidated (ss below)

screen shot 2017-10-16 at 11 53 20 am

**Comment by serenamarie125** [comment]
@chriskacerguis I think the confusion is around what was moved to a later version.  I am under the impression that what was moved was the ability to look at a service, and see the timeline of all associated VMs.

AFAIK, the ability to click View All on the Timeline card of the VM, should go to a timeline view for that specific VM.

**Comment by chriskacerguis** [comment]
@serenamarie125 Sure, I understand that...but, it was that "timeline view" that got pushed.  The story "As a user, I want to be able to open events UI of a resource at Service Level" got moved to the next version.

**Comment by chriskacerguis** [comment]
@serenamarie125 for your reference: https://github.com/ManageIQ/manageiq-ui-service/issues/942

**Comment by AllenBW** [comment]
We got a new mock! 

screen shot 2017-10-16 at 5 10 03 pm

So we did the following: 
* removed disk io
* swapped location of disk usage and smart state analysis
* resized utilization to be 60 40 with smart state analysis
* removed the 'created on' date from the utilization chart

* re added the slider to the timeline
* changed timeline icon from warning triangle to bullseye
* added 'last 7 days' to timeline

* added popover when there are more than 2 ip addresses (icon has color #0088ce)
* removed icons from compliance and retirement when there is a never status
* bolded the top line of the top row, second column card

screen shot 2017-10-16 at 5 13 55 pm

@Loicavenel @serenamarie125  Would you agree the above bullets accurately capture the work we discussed?  Did I forget anything?

**Comment by serenamarie125** [comment]
@AllenBW Yes to all points, except for the bullseye.  The timeline view should use filled in circles.  When multiple events occur in a small time period, the icon should change to the bullseye ( as shown in the [PatternFly demo](https://rawgit.com/patternfly/patternfly-timeline/master-dist/demo/) )

**Comment by serenamarie125** [comment]
Other items discussed were:

- Need to determine what date/time format to use for Retirement date.  Note that the Ops UI currently uses "mm/dd/yy hh:mm UTC" format.  Should we use the same for now @Loicavenel ?
- When there is no Retirement date set, do not show the icon, and use the "Never" label
- When there is no valid Compliance information, do not shown an icon nor tooltip, and use a "Never Verified" label

**Comment by AllenBW** [comment]
@serenamarie125 oh good catch on the date!  Yep, already have the wording for compliance and retirement, in keeping the conversation here ish posting @Loicavenel words from the doc, 

> mm/dd/yy is UK + USA.. most of EMEA is dd/mm/yy.. Can we not have something like 23 October 2017 or abreviated to 23 Oct 2017 hh:mm

@serenamarie125 ☝️ whichever you feel is best, will implement and that should finish off all of the asks (side note, dates everywhere should probably be reformatted if we wanta go with something that has letters in the label)

**Comment by AllenBW** [comment]
Retirement date format updated and also posted a few examples of two ip address and no ip addressses
screen shot 2017-10-17 at 10 05 59 am
screen shot 2017-10-17 at 10 04 42 am

**Comment by chriskacerguis** [comment]
This is some good 🌮

**Comment by AllenBW** [comment]
SO we got a new mock detailing ipaddress and hostname rows in card 1:1
screen shot 2017-10-18 at 2 06 39 pm


Totally implemented that thing! *quick note* you might notice both rows have the info icon, this is to show they work, when there is a single of either (hostname or ipaddress) no info icon and text is show
screen shot 2017-10-18 at 2 04 13 pm


@Loicavenel @serenamarie125

**Comment by chriskacerguis** [comment]
@AllenBW is this ready for @serenamarie125 to give final review?

/cc @Loicavenel

**Comment by AllenBW** [comment]
@chriskacerguis aside from coverage, yep! we're all good here

**Comment by AllenBW** [comment]
i don't want to cry 🐺 butttttt coveralls is reporting the coverage of this file fell, but in fact we have complete coverage 😭 
https://coveralls.io/builds/13780392/source?filename=client%2Fapp%2Fservices%2Fusage-graphs%2Fusage-graphs.component.js

**Comment by chriskacerguis** [comment]
@AllenBW ok.  Odd.

**Comment by chriskacerguis** [comment]
LGTM - Waiting for PM and UXD signoff.

/cc @Loicavenel @serenamarie125 @ohadlevy @chessbyte

**Comment by Loicavenel** [comment]
looks good for me

**Comment by serenamarie125** [comment]
@AllenBW if there is a single hostname, you should only display that hostname, with no extra text.  It seems like you are still showing the "1 Hostname " + Field Level Help icon

ipaddressinfo

**Comment by serenamarie125** [comment]
Oops @AllenBW after read the text more carefully, I guess you are handling that 💃 
Please make one more adjustment - my earlier mock showed "Hosts" but we really want "Hostnames" as noted in my previous comment.

Otherwise looks 👌💯

**Comment by serenamarie125** [comment]
@miq-bot remove_labels ux/review

**Comment by serenamarie125** [comment]
@miq_bot add_labels ux/approved

**Comment by chriskacerguis** [comment]
Per https://github.com/ManageIQ/manageiq-ui-service/pull/910#issuecomment-337757321 should have added ux/approved label, but didn't.  Manaully adding.

**Comment by AllenBW** [comment]
@serenamarie125 updated as per your request!  also, jah, the 1 host name was for demonstration purposes, check out the ss below, found one with two (and one with one)
screen shot 2017-10-19 at 7 34 21 am
screen shot 2017-10-19 at 7 32 35 am

**Comment by chriskacerguis** [comment]
Going to merge, since we have 100% coverage on what was done.

**Pull request merged**
