### PR TITLE
Remove unnused 'blocks' modules

### PR DESCRIPTION
**Pull request by jjlangholtz**
Remove several modules that are being loaded/bundled but actually being
used anywhere.

### CODE REVIEW

**Comment by jjlangholtz** [comment]
@miq-bot add_label euwe/no, refactoring

**Comment by chriskacerguis** [comment]
@jjlangholtz story?

**Comment by jjlangholtz** [comment]
No story, I noticed it while working on https://github.com/ManageIQ/manageiq-ui-service/pull/439. Pulling it out because it is independent. Do I need to make a new story for deleting dead code?

**Comment by chriskacerguis** [comment]
@jjlangholtz yes please I'd just call it a BUG.

**Comment by jjlangholtz** [comment]
https://www.pivotaltracker.com/story/show/137889337

**Pull request merged**
