### PR TITLE
Fix for Issue #105: Tag Control fields not working in SSUI

### PR DESCRIPTION
**Pull request by dtaylor113**
Now able to see Tab Control dropdown in SUI:

tagcontrol

@chriskacerguis @serenamarie125

### CODE REVIEW

**Comment by serenamarie125** [comment]
LGTM from a UI perspective @dtaylor113 Thanks!

**Comment by chessbyte** [comment]
Euwe Backport details:
```sh
$ git log -1
commit a8c7e8a8c8fd30d3e28ff02065ddf91bbe7c4065
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Oct 18 14:37:05 2016 -0500

    Merge pull request #264 from dtaylor113/master
    
    Fix for Issue #105: Tag Control fields not working in SSUI
    (cherry picked from commit 76cd81dff3af3f3c9335e67e09e79fcc8e893660)
```

**Comment by gmcculloug** [comment]
Marking for backport to Darga as it partially resolves https://bugzilla.redhat.com/show_bug.cgi?id=1371291.

The missing functionality is being able to multi-select tags.  Note: Tag categories define if they allow multiple or single tag values.  The dialog field has an optional override to force multi-tag categories to act as single.

cc @eclarizio

**Comment by gmcculloug** [comment]
@chessbyte Let me know if you need anything else to get this back ported.

**Comment by chessbyte** [comment]
Darga Backport details:
```sh
$ git log -1
commit b4cb0d3c117bbf8729470026d1a5daaa37182343
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Oct 18 14:37:05 2016 -0500

    Merge pull request #264 from dtaylor113/master
    
    Fix for Issue #105: Tag Control fields not working in SSUI
    (cherry picked from commit 76cd81dff3af3f3c9335e67e09e79fcc8e893660)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1376519
```

**Pull request merged**
