### PR TITLE
Updated RBAC and product features to support new structure

### PR DESCRIPTION
**Pull request by chalettu**
GH Issue https://github.com/ManageIQ/manageiq-ui-service/issues/1054

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label enhancement

**Comment by chalettu** [comment]
This PR is dependent on https://github.com/ManageIQ/manageiq/pull/16212 getting merged first.

**Comment by chalettu** [comment]
@miq-bot add_label fine/no

**Comment by AllenBW** [comment]
Adding unmergable because of dependency on other pr  ManageIQ/manageiq#16212

**Comment by chalettu** [comment]
@miq-bot remove_label unmergeable

**Pull request merged**
