### PR TITLE
BZ#142772825 - snapshottimeline

### PR DESCRIPTION
**Pull request by AllenBW**
This work is following the mock here: https://www.pivotaltracker.com/story/show/142772825

This pr adds the reusable (and rather well executed) timeline component to the sui in addition to the timeline in the snapshots components.

### Mock
snapshotsview 1

### Where we're at
timeline

### CODE REVIEW

**Comment by AllenBW** [comment]
looks like something is still up wth status... travis passed :-/ https://travis-ci.org/ManageIQ/manageiq-ui-service/jobs/255020128

**Comment by AllenBW** [comment]
@Loicavenel @serenamarie125 @chriskacerguis for your 👁 and 👂 -  🌮 💃

**Comment by Loicavenel** [comment]
@AllenBW this look very promising, can you add a screenshot when you mouse over the Camera on the timeline, please?
Also, @serenamarie125 to decide here, but could we remove the "Snaphot Timeline" text on the left? it is using a lot of place while we know what we are looking at...

**Comment by AllenBW** [comment]
@Loicavenel the second image shows what happens when you mouse over a camera, camera gets a little larger. In lieu of guidance I followed default behavior of [patternfly-timeline](https://rawgit.com/patternfly/patternfly-timeline/master-dist/demo/)

**Comment by serenamarie125** [comment]
Looking good so far! I'd like to get some visual input on this before it is approved, as integrating a timeline view and list view on the same page is something new.

Additionally, the tooltip should have a bit more information.  Check out the specs here: https://docs.google.com/document/d/1YBi1rk5qBHqyTVrx1uN4f_JLRbAUZ27uUngwgsqP7mE/

Unfortunately the design doc hasn't made it to the GH repo yet.  Let's review at the SUI Sync this week to be sure we are all on the same page

**Comment by serenamarie125** [comment]
@chriskacerguis i think should should have a ux/review tag on it

**Comment by AllenBW** [comment]
@serenamarie125 thanks for the guidance! will do 🙇‍♀️

**Comment by AllenBW** [comment]
@serenamarie125 @Loicavenel updated pr to include event tooltips that activate on hover

**Comment by Loicavenel** [comment]
@AllenBW Tool tip is great.. but can we make timeline span across the whole windows.? Can we remove the title on the left?

**Comment by AllenBW** [comment]
@Loicavenel as requested, no more left title, larger graph, and for free, you'll get a responsive graph as well 😽

**Comment by serenamarie125** [comment]
@AllenBW looking good.  I'd like to have a white panel ( similar to a card ) behind the timeline.  A low fi mockup is here:
snapshotsview

Would you like to get a high fidelity so you can see specifically what I'm referring to?

Additionally, I see some probs with the sm/x-sm responsive state the timeline should span the entire width.  I tried to take a screenshot from your animated gif to show you what i meant:
screen shot 2017-07-26 at 8 30 14 am

**Comment by AllenBW** [comment]
@serenamarie125 can put it in a well, no additional fidelity required, timeline **does** span the entire width, the ss you posted the timeline resizing mid-flight (while its being adjusted), please see the attached ss for a tiny timeline
screen shot 2017-07-26 at 8 58 53 am

**Comment by AllenBW** [comment]
@serenamarie125 is this in line with what you were thinking for a white card? 
screen shot 2017-07-26 at 9 12 26 am

**Comment by Loicavenel** [comment]
@serenamarie125 @AllenBW Do you not thinkg the Camera can be bigger?

**Comment by AllenBW** [comment]
@Loicavenel the camera increase in size when hovered over

**Comment by serenamarie125** [comment]
I'm actually calling in a visual designer, to make sure that I give you the proper suggestions.  I think we some additional tweaks this will look even better.  I'm chatting with her now and will get back to ya @AllenBW

**Comment by serenamarie125** [comment]
@AllenBW i hope you will appreciate, this piece of 🎨 from Jenny:



Jenny's comments: 

The page background would be white down until the list view. I think it's helpful to have the grey underneath the list view. It helps to bring more clarity to the hierarchy.  The list view recedes, while the timeline is in the forefront. there will be just a simple 1px grey line separating the timeline and list view.

Note this also suggests making the breadcrumb bar white ( should i create an Issue for this across SUI? )

**Comment by serenamarie125** [comment]
timelinemockup

hmmm ^^^ @AllenBW

**Comment by chriskacerguis** [comment]
@serenamarie125 SOOOO PRETTY!!!  Does Jenny have a GitHub username, we can add her to the project?

**Comment by AllenBW** [comment]
@serenamarie125 so add a horizontal rule and remove timeline from a card give it a white background? would that mean we could  merge this pr???

yeah if we wanta change breadcrumb everywhere, thats a task that extraordinarily exceeds the scope of this pr, correct, new issue

**Comment by AllenBW** [comment]
screen shot 2017-07-26 at 2 52 33 pm
@serenamarie125

**Comment by serenamarie125** [comment]
@AllenBW 👏 

1 - can you make the amount of space between the new horizontal rule & the top of the filter component equal to the amount of space between the bottom of the filter component and the next "line"?
2 - can you make the new "line" have the same visuals as the one below the filter component?
3 - is it possible to have the "view context" (blue box) on the timeline below be the last 7 days?  Although I'd like @Loicavenel to confirm that makes sense.  This would give the ability to see a visualization of the last 7 days but still be able to zoom in/out to more!

**Comment by AllenBW** [comment]
@serenamarie125 not entirely sure i understand, but is this closer? 

screen shot 2017-07-26 at 4 16 19 pm

presently, default zoom spans the entirety of context of results, can't pre-set some subset 🙍

**Comment by chriskacerguis** [comment]
@AllenBW let me know when you make the icons bigger, and I will merge.  Good work on this.

**Comment by chriskacerguis** [comment]
@AllenBW it's a pretty big coverage drop (1.9%)...within our "tolerance" level for a green...do you think that you can do a bit to bring it up?

**Comment by Loicavenel** [comment]
I am the only one who think the camera icon looks really tiny in the middle of timeline bar?

**Comment by AllenBW** [comment]
@Loicavenel @serenamarie125 @chriskacerguis bigger icons

screen shot 2017-07-26 at 5 34 49 pm

@chriskacerguis added more tests, if they don't do much, can add some stuff to other places in another pr

**Comment by Loicavenel** [comment]
@AllenBW good, size look better.. but I am scared you then removed the Zoom in effect?

**Comment by AllenBW** [comment]
@Loicavenel on hover no longer changes the icon size, is that what you mean by zoom effect?

**Comment by AllenBW** [comment]
screen shot 2017-07-26 at 6 00 51 pm

@Loicavenel can add it back if ya want

**Comment by Loicavenel** [comment]
really cool @serenamarie125 Approve please :)

**Comment by serenamarie125** [comment]
i already approved, thanks for all the rework @AllenBW looks awesome !

**Comment by AllenBW** [comment]
Yay! go team! 🌮 💃

**Comment by chriskacerguis** [comment]
BZ - https://bugzilla.redhat.com/show_bug.cgi?id=1502318

**Pull request merged**
