### PR TITLE
Updated Breadcrumbs and routing

### PR DESCRIPTION
**Pull request by chalettu**
This is to upgrade breadcrumbs and routing.  Pivotal Ticket https://www.pivotaltracker.com/story/show/138278145

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label wip
@miq-bot add_label enhancement
@miq-bot add_label euwe/no

**Comment by chalettu** [comment]
@AllenBW for routing updates, should we change urls to look like
request-explorer/10000000000181 to requests/10000000000181
service-explorer/10000000000405 to services/10000000000405
Thoughts?

**Comment by AllenBW** [comment]
@chalettu yeah! down

**Comment by chalettu** [comment]
@miq-bot remove_label wip

**Pull request merged**
