### PR TITLE
Add a security test that runs yarn npm audit

### PR DESCRIPTION
**Pull request by Fryguy**
Similar to https://github.com/ManageIQ/manageiq/pull/23098

### CODE REVIEW

**Review by jrafanie — APPROVED** [review]
LGTM

**Comment by jrafanie** [comment]
Kicking whitesource test to see if it will pass

**Comment by jrafanie** [comment]
@Fryguy do you know what's up with the whitesource check?  at a quick glance, this is the last commit on master that seems to have passed all checks: https://github.com/ManageIQ/manageiq-ui-service/commit/81673f2deec09d9deb9ecaae06377e808dc4a79f

**Comment by Fryguy** [comment]
I'm not sure but it keeps just straight failing

**Comment by jrafanie** [comment]
Merging for now.  We've contacted whitesource and since it's been happening for a while, it's unlikely related to this PR.

**Review by jrafanie — APPROVED** [review]

**Pull request merged**
