### PR TITLE
BZ#1446408 -filter tooltip overflow

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1446408
https://github.com/patternfly/angular-patternfly/pull/456
https://www.pivotaltracker.com/story/show/144523025

Screenshots are in the patternfly pr

### CODE REVIEW

**Comment by chriskacerguis** [comment]
just a dependency update, merging.

**Comment by serenamarie125** [comment]
LGTM.  Have you guys already bumped your version of Angular PF?  I think it was just released on 5/10th (https://github.com/patternfly/angular-patternfly/releases/tag/v3.24.0)

**Comment by chriskacerguis** [comment]
Yup, it was bumped as part of this PR.

**Comment by chriskacerguis** [comment]
@serenamarie125 could you please add your approval?

**Comment by simaishi** [comment]
@AllenBW there is a conflict backporting to Fine branch. Please confirm `^3.24.0` is what we'd like for Fine branch.

```diff
++<<<<<<< HEAD
 +    "angular-patternfly": "3.23.2",
++=======
+     "angular-patternfly": "^3.24.0",
++>>>>>>> af8b601... Merge pull request #753 from AllenBW/BZ/#1446408-filtertooltipoverflow
```

**Comment by AllenBW** [comment]
@simaishi yep! `^3.24.0` is what we want, ( or probably more like `3.24.0` without ^) the release docs [here](https://github.com/patternfly/angular-patternfly/releases/tag/v3.24.0) indicate the desired fix is incedlud

**Comment by simaishi** [comment]
@AllenBW so just `3.24.0` (without `^`) for `angular-patternfly`, and keep `~` for `patternfly` and `bootstrap-switch` ?

**Comment by simaishi** [comment]
Removed `fine/yes` as this is no longer needed as per BZ.

**Pull request merged**
