### PR TITLE
[Fixes #149678945] The VM status shows "retired" for all VM's , retired or not

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label fine/yes
@miq-bot add_label my services

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu ^

**Comment by chalettu** [comment]
retired
Retired.

**Comment by chalettu** [comment]
not_retired
Not retired

**Comment by chalettu** [comment]
@AllenBW , take a look at the SS

**Comment by simaishi** [comment]
@chalettu Is there a BZ for this?  Can you please create if it doesn't exist?

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit a6af7c36a87e423beda561169bc7a7cbed0ffbff
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Jul 31 11:33:03 2017 -0500

    Merge pull request #856 from chalettu/retired-vm-status
    
    [Fixes #149678945] The VM status shows "retired" for all VM's , retired or not
    (cherry picked from commit 066a9a0ccbba683aaedb31c4c9935111a595a3a2)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1484608
```

**Pull request merged**
