### PR TITLE
Chore/prune depreciate request code

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/150680543

Includes removing unused code, cleanup of depreciated states,  renaming misleading files, ensuring everything works as it did previously.

The other thing we did here @serenamarie125 was restore the requests list in the order details screen (was pulled because it was also being used for requests explorer https://github.com/ManageIQ/manageiq-ui-service/pull/709 ).  Find attached below a ss with the list restored, please note, nothing has changed from the original design, just restored what was accidentally pulled.

screen shot 2017-08-30 at 12 56 16 pm

### CODE REVIEW

**Comment by AllenBW** [comment]
working on coverage

**Comment by AllenBW** [comment]
@chriskacerguis coveralls is 😀

**Comment by chriskacerguis** [comment]
No UX changes, just code removal.

**Comment by chriskacerguis** [comment]
@serenamarie125 if we need to change, just let us know...but, as @AllenBW said this was something that was previous there (which I thought was approved...could be wrong); that through a bug disappeared.

**Pull request merged**
