### PR TITLE
Fixed issue with custom button groups

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
This fix is related to https://github.com/ManageIQ/manageiq-ui-service/pull/1254.

**Comment by chalettu** [comment]
Before. before_button

**Comment by chalettu** [comment]
After - 
fixed

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 749f5edcabb48bcae4ec7aa508c3080cf73f7ecc
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Fri Dec 8 11:38:22 2017 -0500

    Merge pull request #1334 from chalettu/custom-button-groups
    
    Fixed issue with custom button groups
    (cherry picked from commit 053683a715e900dddc49172eea07a208ad009393)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1524718
```

**Pull request merged**
