### PR TITLE
Added tests for shopping cart service

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/145296897

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/no
@miq-bot add_label test
@miq-bot add_label technical debt

**Comment by chalettu** [comment]
No UX changes. Just tests

**Comment by chalettu** [comment]
@AllenBW if you wonder why I rolled back the version of the chai-as-promised package its because the newer version is written in es6 and causes our setup to tank when trying to run tests.

**Comment by AllenBW** [comment]
@chalettu we gotta document that, not just in the pr message, but in a separate commit, something that'll show up when someone does git blame/ annotate

**Comment by AllenBW** [comment]
@chalettu but ya know this also raises a good question... maybe we should have a running list of why some deps  are pegged at a version...

**Pull request closed without merging**
