### PR TITLE
BUG#1171-Resource and menu action buttons on the same row

### LINKED ISSUE #1171: When looking at a service, the Resource action buttons should be on the same "row" as the rest of the information
Description of problem:
When looking at a service, the Resource action buttons should be on the same "row" as the rest of the information

See the attached screenshot with issue:
screen shot 2017-10-26 at 11 05 50 am

@Loicavenel @AllenBW as discussed in our meeting on 2017-Oct-26

### PR DESCRIPTION
**Pull request by AllenBW**
closes #1171 

pf-list-view has provisions for both menu (kebab) and action buttons, opting for our proven in place solution for fear the pf implementation will be a regression in terms of customizability

[These two classes create an experience identical to the component ](http://www.patternfly.org/angular-patternfly/#/api/patternfly.views.component:pfListView)options without sacrificing functioning in place code

screen shot 2017-10-27 at 12 19 03 pm
screen shot 2017-10-27 at 12 19 17 pm

### CODE REVIEW

**Comment by chriskacerguis** [comment]
LGTM, waiting for UXD review from @serenamarie125

**Comment by chriskacerguis** [comment]
@serenamarie125 does this match what was discussed at the meeting?

**Comment by chriskacerguis** [comment]
@Loicavenel this work for you?

**Comment by Loicavenel** [comment]
yes, this is what was in 4.5, back to normal

**Comment by chriskacerguis** [comment]
Awesome, thanks @Loicavenel just waiting for @serenamarie125 sign off.

**Comment by serenamarie125** [comment]
Spacing looks off, but I can open an issue re: spacing

**Comment by serenamarie125** [comment]
@miq-bot add_labels ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_labels ux/review

**Pull request merged**
