### PR TITLE
[WIP] Mock API updates

### PR DESCRIPTION
**Pull request by chalettu**

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu can you please take a look at the errors?  Also, in your Mock data can you swap out the "cloudforms" name with "ManageIQ".  It's a silly change, but the BOT keeps getting upset.

**Comment by chalettu** [comment]
ill fix the cloudforms text but I looked and the tests are not failing because of a change I made.   I believe these tests are currently failing for everyone

**Comment by chriskacerguis** [comment]
@jjlangholtz @AllenBW any thoughts on the Travis fails?

**Comment by jjlangholtz** [comment]
Tests are passing locally for me and passed on my last push. @chalettu do you see the same failure locally?

**Comment by chriskacerguis** [comment]
FWIW - I have restarted the build

**Comment by chriskacerguis** [comment]
@chalettu I think you need to do a rebase

**Comment by chriskacerguis** [comment]
hmmm...looks like the build passed.  Odd. /shrug

**Comment by chalettu** [comment]
Yeah, his changes came along after I had already submitted my PR.  I rebased and it looks to be working.

**Comment by chriskacerguis** [comment]
Is this still a WIP?

**Comment by chalettu** [comment]
Yes.  I am writing up the documentation and I still have two more services to add.

**Comment by chriskacerguis** [comment]
@chalettu this isn't rebased correctly.  I should only see your changes, not others.

**Pull request closed without merging**
