### PR TITLE
[EUWE] Fix for issue with provisioning sending in an integer when it should be a string

### PR DESCRIPTION
**Pull request by eclarizio**
This will only attempt to coerce the default value into an integers if the data_type is integer.

https://bugzilla.redhat.com/show_bug.cgi?id=1478367

Note this fix will also need to be applied to the fine branch, but only the line from 104 as the line from 81 does not exist on fine.

@chriskacerguis Tagging for visibility, will be watching for travis success :)

@miq-bot assign @chriskacerguis 
@miq-bot add_label bug

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Node Security Failure is ok.

**Comment by chriskacerguis** [comment]
@simaishi ready for your merge!

**Comment by simaishi** [comment]
@eclarizio since you didn't mention about 'master' branch, I assume this isn't a problem there.  For future reference, please add a link to master PR if it was fixed in other PR.

**Comment by simaishi** [comment]
5.7.z/Euwe BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1480018

**Comment by eclarizio** [comment]
@simaishi You are correct, the problem does not exist on master.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit a402325fea562e81d48af290c1f1b835fe958cc0
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Wed Aug 9 20:02:17 2017 -0400

    Merge pull request #868 from eclarizio/BZ1478367
    
    [EUWE] Fix for issue with provisioning sending in an integer when it should be a string
    (cherry picked from commit ec533b56791b043003a25ce89942d53060a86869)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1478367
```

**Pull request merged**
