### PR TITLE
Adds create snapshot button on service details page

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/n/projects/1914499

Button obeys rbac
[Follows mocks specified here](https://docs.google.com/document/d/1YBi1rk5qBHqyTVrx1uN4f_JLRbAUZ27uUngwgsqP7mE/edit)

### Wat it lookz like, you'll notice this now follows mocks
snapshotcreate

### CODE REVIEW

**Comment by AllenBW** [comment]
@Loicavenel @serenamarie125 💃 🇰🇿 🌘

**Comment by Loicavenel** [comment]
looks good for me.. we need final signe off from @serenamarie125

**Comment by chriskacerguis** [comment]
@AllenBW travis fail.

**Comment by chriskacerguis** [comment]
@AllenBW also, test coverage drops (not a massive drop, but maybe we can do something to improve it?)

**Comment by AllenBW** [comment]
@chriskacerguis hmm... well we already have a spec for the component

**Pull request merged**
