### PR TITLE
 Add support for WebMKS remote consoles via a custom template

### PR DESCRIPTION
**Pull request by skateman**
This is the very last piece of the puzzle for having WebMKS support in the SUI...

@miq-bot add_reviewer @himdel 
@miq-bot add_label enhancement, hammer/no

Resolves https://github.com/ManageIQ/manageiq-ui-service/issues/1520
Depends on https://github.com/ManageIQ/manageiq-ui-service/pull/1553 https://github.com/ManageIQ/manageiq-api/pull/621 https://github.com/ManageIQ/manageiq/pull/18927
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1532720

### CODE REVIEW

**Comment by skateman** [comment]
@himdel @AllenBW somehow the remote console file isn't accessible through `/ui/service` in development. Neither in this PR and in the master. However, I assume this thingie worked before I toughed anything and it will work in production as it should. I manually dropped the `/ui/service` prefix from the URL after opening the console popup and it worked.

**Comment by himdel** [comment]
> the remote console file isn't accessible through /ui/service in development

Yeah, the current consoles have the same problem. There is no directory to serve those files from, before you build it. And webpack-dev-server only supports proxying, not custom data routes.

Testing should still be possible by running `yarn run build`, running ops ui, and going to http://localhost:3000/ui/service

**Comment by himdel** [comment]
@skateman you want to add `/* eslint comma-dangle: 0 */` on the first line of the file.

**Comment by AllenBW** [comment]
> @skateman you want to add `/* eslint comma-dangle: 0 */` on the first line of the file.

Should we just turn it off in the eslint config? we already turn this off in 4 other places 🤔

**Comment by himdel** [comment]
Oh, @AllenBW I was under the impression that standardjs is involved and disabling globally would be non-trivial. If that's not so, yeah, by all means let's switch that off :)

**Comment by AllenBW** [comment]
Ah that's right, we could rework linting to extend standard, have all the benefits of with the ability to edit easily 🤔  https://github.com/standard/eslint-config-standard

**Comment by skateman** [comment]
This is ready for review, the test and the noVNC dependency is still relevant, the old consoles should work as before.

**Comment by himdel** [comment]
LGTM, I've seen this work :)
(Waiting for core)

**Pull request merged**
