### PR TITLE
PT#142772933 -  power buttons vm details

### PR DESCRIPTION
**Pull request by AllenBW**
Refactors vmdetails state to be vmdetails component
Refactors instance rbac to align with product types
Relocates retireVM power operations to appropriate service

Adds power operatios to vmDetails component
- obeys rbac
- obeys power state
- observes polling at same rate as serviceDetails

there have been visual changes in this pr...
* bottom of vmdetails now has a bottom margin, is no longer smushed against the bottom of the screen
* power operations now available on machine (upper right hand)
image

## just because we're here, we also added padding to catalog card view, bye bye being smushed
image

### CODE REVIEW

**Comment by chriskacerguis** [comment]
UX change.  UXD review needed.

@ManageIQ/core-ux please review.

**Comment by serenamarie125** [comment]
Thanks for requesting review @AllenBW @chriskacerguis. I'd like to be able to verify icons before giving approval.  I can do that on Friday ( we are currently going through an exercise to make VM actions and status icons consistent between RHV & Ops UI, so SUI should use the same).

**Comment by chriskacerguis** [comment]
@ManageIQ/core-ux reminder per your request :)

**Comment by AllenBW** [comment]
Hi friends, working on resolving this conflict, any way we can merge this and go back and fix it once a decision has been made?  A pr sitting out there this long makes me nervous... @chriskacerguis @serenamarie125

**Comment by chriskacerguis** [comment]
Can't merge without UXD review or override from John.

**Comment by serenamarie125** [comment]
@AllenBW we are trying to come up with a proposal for common VM icons.  That being said, the proposal isn't complete so this PR shouldn't be blocked.  I don't think the bed should be used for retirement.  Could you use what is currently being used in Ops UI for now?

**Comment by AllenBW** [comment]
@serenamarie125 totally would have used opsui as the guide, but unfortunately it hasn't set the precedent yet for retire icons (see screen shot below) 
image

thoughts on how to proceed without ops as guidance?

**Comment by AllenBW** [comment]
@serenamarie125 updated the icon to be the clock as seen here
image


we good to merge this?

**Comment by chriskacerguis** [comment]
@AllenBW Travis no like you.  UXD approved, so as soon as you fix that, I'll merge.

**Comment by AllenBW** [comment]
Travis just needs a few kicks, the commence 😗!

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 69519f8d22d827abed15c676b003ee8fc0d165d2
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Apr 10 10:21:33 2017 -0500

    Merge pull request #635 from AllenBW/enhancement/142772933-power-buttons-vm-details
    
    PT#142772933 -  power buttons vm details
    (cherry picked from commit a5661fb438a8ea2ea6437ffe404225d5748b8567)
```

**Pull request merged**
