### PR TITLE
login - add spinner to Log In button

### LINKED ISSUE #1620: No visual indication after clicking Login
On login screen,
after filling out username and clicking login,
nothing seems to happen until the server responds.

Which is a problem beacuse the server doesn't always respond that fast, leading the user to believe nothing happened.

We should add a spinner, same as ui-classic.

### PR DESCRIPTION
**Pull request by himdel**
Adds a spinner to the Log In button...

before (and when idle):
login

after, after pressing the button:
20200130183354 mp4

(minus the gif artifacts)

Fixes #1620

~~@epwinchell Does this make sense? I'm.. not so sure about the CSS I'm adding here.., it works, but that's the best thing I can say about it :)~~
(Without *some* css fix, the spinner just blows the button up to a huge size because `.spinner-sm` 18px x 18px becomes ~25px when rotating.)
Thanks @epwinchell for much better CSS :).

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_reviewer @epwinchell

**Comment by epwinchell** [comment]
@himdel That's a unique solution... :) How about hooking it to the container div rather than the button?

**Comment by himdel** [comment]
We don't have a full screen spinner in SUI, so I was hoping to use the patternfly spinner instead of copying the ui-classic solution.

But if you prefer that, I'll just add `spin.js` and use it as in ui-classic :)

(But IMO the solution is not *so* unique, putting the spinner in a button we're waiting for is defintely something I've seen before :).)

**Comment by himdel** [comment]
@miq-bot remove_label wip

**Pull request merged**
