### PR TITLE
[EUWE] Update breadcrumbs throughout SUI per UXD designs

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
@chriskacerguis @chessbyte 

Euwe Backport of of #281

This PR updates the breadcrumbs to the design given by UXD.

Jira story: https://patternfly.atlassian.net/browse/CFUX-109

@miq-bot add_label euwe/yes, bug

### CODE REVIEW

**Comment by serenamarie125** [comment]
Great thanks @jeff-phillips-18 .  This addresses the issue of inconsistent and "bad" breadcrumbs

**Comment by chessbyte** [comment]
@jeff-phillips-18 can you look into Travis failure?

**Comment by jeff-phillips-18** [comment]
@chessbyte Travis build fixed.

**Comment by serenamarie125** [comment]
@chessbyte, @jeff-phillips-18 took care of the travis failure already.  This is a fix for inconsistent and "bad" breadcrumbs.  It would be a win for UX from a consistency perspective.  Please consider for euwe.

**Pull request merged**
