### PR TITLE
Added new component for detail reveal and updated vm details screen

### PR DESCRIPTION
**Pull request by chalettu**
This is a PR for Pivotal Issue https://www.pivotaltracker.com/story/show/135697909.

### CODE REVIEW

**Comment by chalettu** [comment]
miq-bot add_label wip

**Comment by chalettu** [comment]
current view

Here is a copy of what the current view of this component looks like.  I am needing help to figure out how to get each alternating row to be striped with an alternating color.

**Comment by chalettu** [comment]
css_fu
Updated view of the styling of the component.  Some changes that are worthy of note.  
1. On hovering over a row, there is a color change for the row
2. If any extra details have been included the arrow on that row turns black, otherwise it will turn light grey.  
3. If extra data exists the whole row switches over to cursor hand and accepts onclick event.

**Comment by chalettu** [comment]
@miq-bot remove_label wip

**Comment by chriskacerguis** [comment]
removing WIP label since the bot seems to be having issues.

**Comment by chriskacerguis** [comment]
Waiting for Travis...

**Pull request merged**
