### PR TITLE
[FINE] BZ#1451374-Displays service resources when type is serviceansibleplaybook

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1451374
https://www.pivotaltracker.com/story/show/145637025

Only shows tabs of orchestration templates that have names, Provision etc

###  Look an ansible service that also has resources!! this is what we waaaaaaantttt
screen shot 2017-05-17 at 3 19 17 pm

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@ManageIQ/core-ux UX changed, UXD team review needed.

**Comment by AllenBW** [comment]
So the only thing that changed ux wise, is now we show resources and the ansible playbook stuff, no new views were created

**Comment by serenamarie125** [comment]
@AllenBW what design did you follow here?  wondering if you duplicated what is in Ops UI or referenced what is in the design repo?

**Comment by chrispy1** [comment]
@miq-bot add_label fine/yes

**Comment by AllenBW** [comment]
Hi @serenamarie125 @chriskacerguis if you recall this pr, https://github.com/ManageIQ/manageiq-ui-service/pull/501 you'll see we followed the designs specified [here](https://github.com/ManageIQ/manageiq-design/blob/master/UX/ui-service/MyServices/design.md) specifically this one:
services-ansibledetailview

Again, this pr doesn't touch the design, same stuff that's always been there, it just ensures all the right stuff is there at the correct time.

**Comment by simaishi** [comment]
@AllenBW is this not a problem in 'master' branch?

**Comment by chriskacerguis** [comment]
@simaishi We have PR https://github.com/ManageIQ/manageiq-ui-service/pull/776 to fix master.  We are just getting ahead of a merge conflict.

**Comment by serenamarie125** [comment]
Ok, I was going to question why we are using the label "successful" rather than using the green check for plays.  If this is a blocker, we can address this at a later time.  I'm not sure I reviewed any prior PRs related to viewing ansible details.

**Comment by chriskacerguis** [comment]
Thanks @serenamarie125 we will address any issues you put in ASAP.

**Comment by chriskacerguis** [comment]
@simaishi this is good to go!

**Pull request merged**
