### PR TITLE
Updated detail-reveal component template and css based on UI team feedback

### PR DESCRIPTION
**Pull request by chalettu**

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label enhancement

**Comment by chriskacerguis** [comment]
@chalettu can you please add screenshots?

**Comment by jeff-phillips-18** [comment]
Please run 'gulp vet' to catch sass lint issues.

**Comment by chalettu** [comment]
closed_stateClosed State. 
Changes Implemented: Only show arrows and arrow cell border if a row has more details.  
open_state
Open State .  Changes implemented.  Grey background on row when row selected.  Close Button X implemented.  
Implemented indent of content inside of detail component

**Comment by chriskacerguis** [comment]
@serenamarie125 thoughts?

**Comment by serenamarie125** [comment]
@chalettu thanks for making the changes!  Couple of nits ...

- is it possible to add borders around the expanded panel as shown here http://www.patternfly.org/pattern-library/content-views/list-view/#/_design?
- is there any way to have the width of the first column in the wider so that the headings aren't wrapping?
- I'm assuming the ".." and "..." is fake data ?

**Comment by chalettu** [comment]
sample screenshot
@serenamarie125 I added more of a pronounced border to when the component is expanded.  The content that was in the other sample image is actually not part of this PR and was just mock data.   The content that goes inside this component can be changed to fit whatever is needed inside it.  I will be sure when we do start doing PR's for detail content that we do have the tabular data more stretched out appropriately.

**Comment by chriskacerguis** [comment]
@cshinn Could you please review?

**Comment by cshinn** [comment]
@chalettu I don't know that the drop shadow etc. is necessary. In our current implementations of expandable lists, the border is still just a simple 1px solid border, but it is changed to blue as seen here. Similar styling in this case would lead to more consistency within our products. 
screen shot 2016-12-16 at 12 39 46 pm

**Comment by chalettu** [comment]
Ok, I can work on doing a blue border.  The link Serena sent, I looked at the sample and it had a shadow on the border on the bottom so I just tried to mimick that.  I'll put in a blue border and add another snapshot.

**Comment by cshinn** [comment]
@chalettu Gotcha, in this case, there's an inconsistency between the design and implementation pages for the pattern. At the moment, I'd say that conforming to the current implementation is more important. I'll look into getting that inconsistency resolved.

**Comment by chalettu** [comment]
sample blue border
@cshinn Here is the updated view to support a blue border around the active revealed component.  I color matched the code that patternfly is using for the listview as well.

**Comment by cshinn** [comment]
@chalettu Border looks great! The expanded section could use some more left padding to make it appear subordinate to the main row. Should be about 20px indented from the "name" in this case.

**Comment by chalettu** [comment]
final
@cshinn Does this work?

**Comment by cshinn** [comment]
Spectacular! Looks great

**Pull request merged**
