### PR TITLE
BZ#1518056-Ensured tooltips do not show when drop downs are open

### PR DESCRIPTION
**Pull request by chalettu**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1518056
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
Before Screenshot 
before_tooltip

**Comment by chalettu** [comment]
After Screenshot
after_tooltip

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 4943b4fbf7b394a6dd64333a60097be0a883b236
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Fri Dec 15 15:54:02 2017 -0500

    Merge pull request #1345 from chalettu/menu-tooltip-issue
    
    BZ#1518056-Ensured tooltips do not show when drop downs are open
    (cherry picked from commit 61db90ef9f07dd33ba1ce6a00f43af8e90788e32)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1527578
```

**Comment by chalettu** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 0dde1bb5dffec799ff3c76c882ec2390a05ec9f3
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Fri Dec 15 15:54:02 2017 -0500

    Merge pull request #1345 from chalettu/menu-tooltip-issue
    
    BZ#1518056-Ensured tooltips do not show when drop downs are open
    (cherry picked from commit 61db90ef9f07dd33ba1ce6a00f43af8e90788e32)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1536684
```

**Comment by simaishi** [comment]
@chalettu Travis is failing in Fine branch:

```
/home/travis/build/ManageIQ/manageiq-ui-service/client/app/shared/custom-dropdown/custom-dropdown.component.js
  25:20  error  Missing trailing comma  comma-dangle
```

Guess the trailing comma isn't required in master/gaprindashvili, but required in fine branch? Can you please create a PR to fix it?

**Pull request merged**
