### PR TITLE
Disable known failing tests

### PR DESCRIPTION
**Pull request by AllenBW**
Add yarn test explicitly to travis
Remove precision that occasionally fails service details test

### CODE REVIEW

**Comment by simaishi** [comment]
@chriskacerguis There is no `yarn` in Euwe branch, so I don't think this PR should be backported as is. If you need a part of this PR in Euwe branch, please create a separate Euwe specific PR.

**Comment by simaishi** [comment]
@AllenBW @chriskacerguis ping ^

**Comment by chriskacerguis** [comment]
@simaishi thanks for pointing that out :)

**Comment by AllenBW** [comment]
hokay, this will be fixxxxxxxxedddddddd

**Comment by AllenBW** [comment]
@simaishi @chriskacerguis I don't believe this to be applicable to euwe (none of the files are present), is there any reason why we're trying to backport this to euwe?

**Comment by chriskacerguis** [comment]
@AllenBW I removed the euwe/yes tag, so there is no need to back port.

**Pull request merged**
