### PR TITLE
BZ#1517075-Move actioncable subcription creation to login promise chain

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1517075

Eliminates ERROR -- : Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket) (a result of creating subscription prior to ws_token cookie being set)

### look, no more error!
screen shot 2017-12-06 at 11 07 21 am

### and notifications still show up!!
screen shot 2017-12-06 at 11 07 34 am

### CODE REVIEW

**Comment by AllenBW** [comment]
Oh @skateman you make me smile so, thank you 😍 🙇‍♀️ 🌺

**Comment by himdel** [comment]
> and notifications still show up

Only after you login ;) Once you reload, they don't.

You'll need a similar piece of code in the code path that runs `Language.onReload` instead of `Language.onLogin`. So most likely `changeStart` in `client/app/core/authorization.config.js`?

**Comment by AllenBW** [comment]
your initial edit was spot on!  we'll wanta do it after we sync the session, thanks for the 👀 @himdel 🙇 💘

**Comment by himdel** [comment]
Just one more think I think...

```
client/app/core/server-info.service.js
12:        asyncNotify: data.settings.asynchronous_notifications

client/app/core/appliance-info.service.spec.js
44:      'asyncNotify': true

client/app/core/appliance-info.service.js
13:      asyncNotify: false
29:      asyncNotify: data.settings.asynchronous_notifications
```

Looks like that `asyncNotify` is now dead code .. is it still useful or should we remove it here?

**Comment by AllenBW** [comment]
@himdel great catch!  yeah lets kill that dead code!  Added another commit

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
 $ git log -1
commit 889b9f55fbdbc1fece2ea993c7ef5845f38fb9e5
Author: Martin Hradil <himdel@seznam.cz>
Date:   Tue Dec 12 15:32:32 2017 +0000

    Merge pull request #1314 from AllenBW/bug/master/#1517075-ws-error
    
    BZ#1517075-Move actioncable subcription creation to login promise chain
    (cherry picked from commit 73526fa43f9ee91dd88540cf0c519a5bd4d0af5d)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1525115
```

**Comment by skateman** [comment]
Well, no more error, but notifications no longer work :rofl: going to fix it :rofl:

**Pull request merged**
