### PR TITLE
BZ#1471158-Adds support for supports_vnc_console decorator

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1471158

Waiting for this to make it in: https://github.com/ManageIQ/manageiq-api/pull/167

This pr does **NOT** fix: https://bugzilla.redhat.com/show_bug.cgi?id=1505546 a separate pr will be required for this

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW looks like ManageIQ/manageiq-api#167 is merged, I restarted the build on this (Node 6 failed...thinking it is just Travis being Travis).  Can this be merged?

**Comment by AllenBW** [comment]
This is good to go! @chriskacerguis

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 2d576999f64558929d9e6da437124a7e91219a2f
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Nov 6 07:47:46 2017 -0600

    Merge pull request #1195 from AllenBW/BZ/#1471158-add-supports-vnc-console-flag
    
    BZ#1471158-Adds support for supports_vnc_console decorator
    (cherry picked from commit 3745df59512d1e45cab8dac27836cd58547398e0)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1510131
```

**Comment by simaishi** [comment]
@AllenBW Please create a separate PR for Fine branch - none of the files are clean cherry-pick...

**Comment by AllenBW** [comment]
@simaishi ok don't wantcha to think i forgot about this, so looks like this work isn't enough to get the fix we want, what WILL BE (should be) the end of all this  is #1280 *so* from that, we'll make a fine and euwe branch so it all gets in alrite alrite

**Comment by simaishi** [comment]
@AllenBW https://github.com/ManageIQ/manageiq-ui-service/pull/1280 was backported to Fine via https://github.com/ManageIQ/manageiq-ui-service/pull/1282. Is this PR still needed for Fine branch?

**Comment by AllenBW** [comment]
@simaishi Nope!! This pr ended up not being a fix, no need to backport  it.

**Pull request merged**
