### PR TITLE
clear user name field on failed login

### PR DESCRIPTION
**Pull request by ohadlevy**
based on discussion on a similar PR on the ops UI (https://github.com/ManageIQ/manageiq-ui-classic/pull/2514#issuecomment-339520635)
I'm suggesting we align across the two.

I would also appericiate help in how to test the fact
the field is actually empty.

### CODE REVIEW

**Comment by AllenBW** [comment]
I expressed this same sentiment in this comment here, https://github.com/ManageIQ/manageiq-ui-service/pull/1142#discussion_r146620941

Defer to @chriskacerguis on this

**Comment by chriskacerguis** [comment]
I think that alignment is good.  That said, the RFE was for the password only.  Perhaps in the future, we should be aligned in the BZ/RFE before code starts?

**Comment by ohadlevy** [comment]
thanks @chriskacerguis - as a follow up - what is the correct way to write a test for this? (as a user i would expect the form user field to be empty)?

**Comment by chriskacerguis** [comment]
@ohadlevy I think for a solid test for this, we need to turn Sauce Labs back on.  We turned it off b/c the free version we were using took too long to run.

**Pull request merged**
