### PR TITLE
PT#141308069-ansible plays sdoutput

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/n/projects/1914499

Adds
* additional details fields, plays, sdtout
* rbac for ansible details
* mock api for ansible service

## 👁 
screen shot 2017-03-15 at 3 13 22 pm
screen shot 2017-03-15 at 3 13 16 pm

image
☝️ changes made to template editor to take advantage of pretty print json

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Waiting for this to be merged: https://github.com/ManageIQ/manageiq/pull/14273

**Comment by AllenBW** [comment]
Waiting for this to be merged: https://github.com/ManageIQ/manageiq/pull/14331

**Comment by chalettu** [comment]
@AllenBW , I never enabled the pretty print json functionality in templates because templates come in YML and other formats.  Does this have any negative effects on YML templates????

**Comment by AllenBW** [comment]
@chalettu oh? didn't see anything in the commit logs about that.. what other formats should we expect?

**Comment by chalettu** [comment]
So far as I know, I think json and yaml but I don't know for sure.  We should ask in the miq room what format openstack templates and vmware templates are written in.

**Comment by AllenBW** [comment]
Updated ss shows stdout, this api endpoint is not yet finalized and continues to be a blocker on this pr

**Comment by AllenBW** [comment]
No api for you today :( maybe tomorrow 🤞

**Comment by AllenBW** [comment]
OH TWO SHAKES THEN WE CAN MERGE!!! promise

**Comment by AllenBW** [comment]
https://github.com/ManageIQ/manageiq/issues/14390 is the pr that brings raw_stdoutput as the virtual attribute we need!!! this pr has been crafted to work with the aforementioned pr

**Pull request merged**
