### PR TITLE
Updated UI components version to remedy dialog select issue

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
@himdel , could you review this one for me?  This is to mirror the update that was made in ui-components

**Comment by AllenBW** [comment]
@chalettu is this a blocker?  I didn't see a bz attached 🤔

**Comment by chalettu** [comment]
This is our mirror fix for https://bugzilla.redhat.com/show_bug.cgi?id=1531316

**Comment by AllenBW** [comment]
soooo yep, blocker!  awesome, thanks for linking!

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 53e1d03bbbd3fd443988a4387ad52044e18df5d9
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Tue Feb 13 07:57:38 2018 -0500

    Merge pull request #1383 from chalettu/dialog-select-ui-components
    
    Updated UI components version to remedy dialog select issue
    (cherry picked from commit 2ee001eb3df3a646666126e14595fba8d471c782)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1531316
```

**Pull request merged**
