### PR TITLE
Created ability to copy Orchestration Template

### PR DESCRIPTION
**Pull request by chalettu**
PV Ticket https://www.pivotaltracker.com/story/show/135004141. 

Added ability to copy orchestration templates

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label euwe/no
@miq-bot add_label templates
@miq-bot add_label enhancement

**Comment by AllenBW** [comment]
@chalettu cc issues :sob:

**Comment by chalettu** [comment]
@AllenBW I looked at this and once again this is how we setup almost every page state in the SUI.  @chriskacerguis we might need a CC override on this PR

**Comment by AllenBW** [comment]
@chalettu wouldya couldya post some ss or a gif of the new feature?

**Comment by chalettu** [comment]
copy

**Comment by AllenBW** [comment]
@chalettu it looks like copy is duplicating the functionality of edit, why introduce a new state rather than re purposing the existing one?

**Pull request merged**
