### PR TITLE
DialogUser - use DialogData.outputConversion before submit and refresh

### PR DESCRIPTION
**Pull request by himdel**
Depends on https://github.com/ManageIQ/ui-components/pull/422

Right now, when submitting a service dialog,
we simply take the dialogData object, convert to JSON and send to the API.

To allow for output conversions, adding a DialogData.outputConversion method,
which should return the dialogData in a suitable format.

(Right now, all this really means is that it converts Dates to strings before JSON stringification.)

And the same needs to happen in refreshField for dynamic fields.

https://bugzilla.redhat.com/show_bug.cgi?id=1744413

@miq-bot add_label bug, ivanchuk/yes

### CODE REVIEW

**Comment by himdel** [comment]
@miq-bot remove_label wip

(still depends on ui-components though)

**Comment by himdel** [comment]
(rebased on top of https://github.com/ManageIQ/manageiq-ui-service/pull/1597, should be mergable)

**Comment by himdel** [comment]
(for ivanchuk, depends on https://github.com/ManageIQ/manageiq-ui-service/pull/1605)

**Comment by simaishi** [comment]
@himdel ivanchuk yarn.lock doesn't meet `object.values@~1.1.0` so yarn.lock needs to be updated differently (along with missing dependency `define-properties ^1.1.3`). Can you please create a separate PR?

**Comment by himdel** [comment]
Aah, forgot about `yarn.lock` .. theoretically, `yarn add object.values` should resolve the conflict.
But I'll do the PR just to make sure :)

**Comment by himdel** [comment]
@simaishi ivanchuk version is in https://github.com/ManageIQ/manageiq-ui-service/pull/1606

**Comment by simaishi** [comment]
Backported to ivanchuk via https://github.com/ManageIQ/manageiq-ui-service/pull/1606

**Comment by simaishi** [comment]
@himdel Do we need a separate PR for `hammer` branch, or can the ivanchuk PR be backported?

**Comment by himdel** [comment]
Yup, we need a hammer version, with a bit more changes than for ivanchuk - https://github.com/ManageIQ/manageiq-ui-service/pull/1609

**Comment by simaishi** [comment]
Backported to Hammer via https://github.com/ManageIQ/manageiq-ui-service/pull/1609

**Pull request merged**
