### PR TITLE
Fix sprintf syntax to enable string extraction

### PR DESCRIPTION
**Pull request by AparnaKarve**
Fixed `sprintf` to enable string extraction of the below `Power Operation` related strings.

### CODE REVIEW

**Comment by AparnaKarve** [comment]
@miq-bot add_label internationalization

**Comment by AparnaKarve** [comment]
@mzazrivec I noticed that some of the newer Power Operation related strings did not get extracted here: https://github.com/ManageIQ/manageiq-ui-service/pull/339, probably because of the incorrect usage of `sprintf`.
(No action required from your end. Just a FYI)

**Comment by AparnaKarve** [comment]
This should be `euwe/yes` since the Power Operations feature is part of Euwe.
Flipping the flag `euwe/no` to `euwe/yes`...

@miq-bot remove_label euwe/no
@miq-bot add_label euwe/yes

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 588c13dccca29975eb9d3758d5c78c182d9f5e37
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Nov 16 15:43:20 2016 -0600

    Merge pull request #346 from AparnaKarve/i18n_fix_sprintf
    
    Fix sprintf syntax to enable string extraction
    (cherry picked from commit cc9e5c1c2e0c69cbfd44d39eddaca91c05c7e004)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1396576
```

**Pull request merged**
