### PR TITLE
[Fixes #150935614] Added more detail when a order request fails

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label orders
@miq-bot add_label fine/no

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@chalettu needs before / after screenshot

**Comment by chalettu** [comment]
Before
orders_before

**Comment by chalettu** [comment]
After 
after

**Comment by chriskacerguis** [comment]
@chalettu please fix code coverage.

**Comment by chriskacerguis** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1483973

**Pull request merged**
