### PR TITLE
Fixes for issue where default values not being selected for dialogs

### PR DESCRIPTION
**Pull request by chalettu**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1471923

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label fine/yes
@miq-bot add_label euwe/yes

**Comment by chalettu** [comment]
@miq-bot add_label catalogs / dialogs

**Comment by simaishi** [comment]
Euwe backport details:

```
$ git log -1
commit 1b3901bb44a420972b2d9bc47e803656ed71e2c3
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Jul 18 19:06:14 2017 -0400

    Merge pull request #849 from chalettu/bz-1471923
    
    Fixes for issue where default values not being selected for dialogs
    (cherry picked from commit ecf6d753bca0b1f07326204f5dc1f20d1c30e4ba)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1475031
```

**Comment by simaishi** [comment]
@chalettu Can you please take a look at Travis failure for Euwe branch? https://travis-ci.org/ManageIQ/manageiq-ui-service/builds/258562682

**Comment by simaishi** [comment]
Travis failure fixed in https://github.com/ManageIQ/manageiq-ui-service/pull/860

**Comment by simaishi** [comment]
@chalettu backporting to Fine branch conflicts in `yarn.lock`. Since I'm not sure which version to take for each package, can you please create a Fine PR?

**Comment by simaishi** [comment]
@chalettu the 5.8 clone of the referenced BZ is already closed. Does this PR still need to go to Fine branch?

**Pull request merged**
