### PR TITLE
Improved test coverage for catalog state service

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/145300045

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/no
@miq-bot add_label test

**Comment by chriskacerguis** [comment]
just tests, no UX.

**Comment by AllenBW** [comment]
I don't want to be a stickler for detail, but this doesn't appear to improve the code coverage, cc rating remains the same?

**Comment by chalettu** [comment]
Where are you looking @AllenBW ?  The cc stuff only changes on merges to master.  I am watching cc in the next few to see if it improves.

**Comment by chriskacerguis** [comment]
Yeah, that's what we were checking

**Comment by AllenBW** [comment]
Mmmmm but this.... https://codeclimate.com/github/ManageIQ/manageiq-ui-service/coverage/5914c3bdf773b200010856c3

Red lines are da stuff it doesn't hit... 🤔

**Pull request merged**
