### PR TITLE
Updated support for launching cockpit and console

### PR DESCRIPTION
**Pull request by chalettu**
@miq-bot add_label bug
@miq-bot add_label fine/no
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1471158

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot remove_label fine/no
@miq-bot add_label fine/yes

**Comment by chrispy1** [comment]
@miq-bot add_label blocker

**Comment by simaishi** [comment]
@chalettu This can be backported to Euwe branch?

**Comment by chriskacerguis** [comment]
for the record, no this cannot be backported to Euwe.  I'll make a PR to the Euwe branch.

**Comment by simaishi** [comment]
Can you confirm Fine should uses `supports_cockpit` (not `supports_launch_cockpit`)? I know there were lots of discussion around what version uses what... so I want to make sure I can resolve conflicts by just moving `supports_cockpit` from attributes to decorators.

**Comment by AllenBW** [comment]
Okie dokie @simaishi https://github.com/ManageIQ/manageiq-ui-service/pull/1282 is the one that fixes this for fine

**Comment by simaishi** [comment]
Removed `fine/yes` label.

**Pull request merged**
