### PR TITLE
[EUWE] Service Dialog - Element visibility on condition is not working in Self-Service portal 

### PR DESCRIPTION
**Pull request by chalettu**
Fix for PV https://www.pivotaltracker.com/story/show/141443927.  This is a EUWE specific PR 

Backport of https://github.com/ManageIQ/manageiq-ui-service/pull/574

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label euwe/yes
@miq-bot add_label bug

**Comment by AllenBW** [comment]
Not sure to restart node security @chriskacerguis ?

**Comment by jjlangholtz** [comment]
It looks like that check fails on every PR to Euwe

**Comment by chriskacerguis** [comment]
@simaishi this is good to go.  FYI - the node security scanner will not validate for EWUE right now; there is not a problem with it, it's just a lack of config file in EUWE

**Comment by chriskacerguis** [comment]
@jjlangholtz can you please investigate what the issue with EUWE is that NSP always fails?  I suspect that it is a lack of a needed config file.

**Pull request merged**
