### PR TITLE
BUG#1167-Restores rbac permissiosn and camera eventicon

### LINKED ISSUE #1167: Snapshot View, missing camera and create/delete functionality
mismatched rbac permissions and missing timeline event shape need to be addressed

cc @Loicavenel @serenamarie125

### PR DESCRIPTION
**Pull request by AllenBW**
closes #1167 

Look camera icon is back!  also we have create in the main dropdown and delete in the row kebab

screen shot 2017-10-26 at 12 29 22 pm
screen shot 2017-10-26 at 12 29 13 pm

@Loicavenel @serenamarie125 did i miss anything on this page?

### CODE REVIEW

**Comment by serenamarie125** [comment]
@Loicavenel shouldn't the button group be called "Snapshots"?  I think that's what it is called when on the VM level.

screen shot 2017-10-26 at 8 14 39 pm

If the name of the command button group is Snapshots, you should be able to change the menu item labels to be: 
- Create
- Delete All

regardless, we need to make sure these are consistent when in the Snapshot View versus the VM Details view.  Can you include screenies of both of the button group menu items?

**Comment by Loicavenel** [comment]
@serenamarie125, Button has to be contextual.
- VM details: Button Snapshots: View & Create
- Service Level:  on resource line:  Button Snapshots: View & Create
- Snapshot view: I don't think we should call the button SnapShot anymore.. we are in...  BUT in place to call it Configuration: we should show the 2 Buttons: Create and Delete All, we have enough place for it.. we save one click  :)

And don't forget in Snapshot view we should offer per Snapshot with Kebab menu: Delete (always) and Revert (where it does apply)

**Comment by AllenBW** [comment]
Great discussion!  Gonna play parent and suggest that we merge this pr, open an issue to continue the discussion as whats being discussed exceeds the scope of this work. @Loicavenel @serenamarie125 ?

**Comment by chriskacerguis** [comment]
@serenamarie125 and @Loicavenel thoughts on @AllenBW 's suggestion?

**Comment by Loicavenel** [comment]
looks good for me... We should re-discuss the "Configuration" button later.. I think when there is only 2 buttons, it may be better to show them both than have to click on configuration

**Comment by serenamarie125** [comment]
This is the tough part with PRs which cover multiples.  Approving as not to block progress.

**Comment by serenamarie125** [comment]
@miq-bot add_labels ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_labels ux/review

**Pull request merged**
