### PR TITLE
Show default service png for catalogs

### PR DESCRIPTION
**Pull request by jjlangholtz**
Fixes missing image logos for catalogs created without uploading a new
image.

Also update `.nvmrc` to use the same node version as travis.

https://www.pivotaltracker.com/story/show/138143341

@miq-bot add_label euwe/no, bug

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@jjlangholtz needs rebase

**Comment by jjlangholtz** [comment]
@chriskacerguis I'm a bit confused as to why this needs a rebase when there are no conflicts.

**Comment by chriskacerguis** [comment]
@jjlangholtz it says it is out of date.

**Comment by jjlangholtz** [comment]
I think the way it is set up every time a PR is merged it will make every other PR out of date.

So instead of requiring a rebase only when there are conflicts, we need to rebase every time a change is merged, conflict or not.

**Comment by chriskacerguis** [comment]
@jjlangholtz that's not the usual behavior I see.

**Comment by jjlangholtz** [comment]
@chriskacerguis I just noticed this morning. I rebased this PR once and then when another one got merged (with no conflicts) I saw this one become out-of-date again.

**Pull request merged**
