### PR TITLE
BZ 1467569- in the self service portal after a little time displaying a vm, data changes to garbage data

### PR DESCRIPTION
**Pull request by chalettu**
No UX changes.  This fixes an issue with polling causing issues with data not rendering properly

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label services
@miq-bot add_label fine/yes

**Comment by chalettu** [comment]
@miq-bot add_label my services

**Comment by simaishi** [comment]
@chalettu There are conflicts backporting in `vm-details.html`, but it looks like I can just change `ng-if` to `dislay-field` in bunch of `details-reveal`. I have to skip one or two because `ng-if` isn't used for it in Fine branch. Please confirm that's ok (or you can create a PR for Fine branch if you'd prefer that way).

**Comment by simaishi** [comment]
@chalettu Thanks for the confirmation on gitter... please double-check the changes backported.

Fine backport details:

```
$ git log -1
commit 18c8e0db1c5a983b47a7eb27b67a0fc9272794a2
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed Jul 12 13:24:07 2017 -0400

    Merge pull request #842 from chalettu/vm-details-bug
    
    BZ 1467569- in the self service portal after a little time displaying a vm, data changes to garbage data
    (cherry picked from commit 2604c93bcc7bcf4972c7e20b53c959e6e97728a3)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1470774
```

**Pull request merged**
