### PR TITLE
Cascading auto refresh for dialog fields

### PR DESCRIPTION
**Pull request by eclarizio**
This is very similar to https://github.com/ManageIQ/manageiq-ui-classic/pull/264, except for the service UI.

https://www.pivotaltracker.com/story/show/139224685

/cc @gmcculloug I'm not sure who is best to review this on the service UI side of things, please advise 😄

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@eclarizio could you please add the appropriate labels?

**Comment by eclarizio** [comment]
@miq-bot add_label dialogs, enhancement

I think those are the correct labels, but I'm not 100% clear on if we need to backport just yet...

@gmcculloug Do we want to backport this to Euwe and Darga or do we think most people running into the issue that the cascading was meant to fix were using OpsUI and this is strictly an enhancement for the Service UI?

**Comment by gmcculloug** [comment]
This was being worked on for BZ https://bugzilla.redhat.com/show_bug.cgi?id=1411541 which is for Darga.  So this should be backported to both Ewue and Darga.

**Comment by eclarizio** [comment]
@miq-bot add_label euwe/yes, darga/yes

**Comment by chriskacerguis** [comment]
@eclarizio also, to answer your question that would be me 😄

**Comment by simaishi** [comment]
@eclarizio looks like there was some refactoring in 'master' and I won't be able to backport this PR to Euwe/Darga as is. Can you create a separate PR?

**Comment by simaishi** [comment]
Backported to Euwe via https://github.com/ManageIQ/manageiq-ui-service/issues/512

**Comment by simaishi** [comment]
Backported to Darga via https://github.com/ManageIQ/manageiq-ui-service/pull/513

**Pull request merged**
