### PR TITLE
BUG#1242 - Cleanup login state, notifications fill full viewport

### LINKED ISSUE #1242: Inline notifications used on the login screen should match PatternFly
Description of problem:
The visualization of the inline notification used on the login screen don't match PatternFly.  The screenshot below is from CloudForms Self Service 4.5:

How reproducible:
Every time

Steps to Reproduce:
1. Enter invalid username/password combination

Actual results:
screen shot 2017-11-15 at 4 05 36 pm

Expected results:
The PatternFly design can be found here: 
http://www.patternfly.org/pattern-library/application-framework/login-page/#/design

### PR DESCRIPTION
**Pull request by AllenBW**
closes #1242
BEM was negating a great deal of patternfly styles we were missing here, pulled it!

### what we look like now
screen shot 2017-11-16 at 7 57 28 am

### CODE REVIEW

**Comment by AllenBW** [comment]
cc @serenamarie125 
(I know this doesn't look exactly pf login, but we can discuss, open other issues for those changes)

**Comment by serenamarie125** [comment]
@AllenBW The major issue with the inline notification was the color ... 
screen shot 2017-11-15 at 11 24 32 pm

I wouldn't have thought the inline notification should span the whole width.  In the PF case, it is because there is more content on the screen.

**Comment by AllenBW** [comment]
So the notification style change you are requesting is better taken up with the patternfly-sass people, as styles from there are what is overriding the traditional notification alert [(these lines specifically)](https://github.com/patternfly/patternfly-sass/blob/master/assets/stylesheets/patternfly/_login.scss#L52-L55)

We can of course override locally until a time when the repo is updated
screen shot 2017-11-16 at 7 27 32 am

I suspect this issue likely plagues ops as well, so changing the patternfly-sass class would benefit both UIs  @chriskacerguis @serenamarie125 @ohadlevy thoughts?

**Comment by AllenBW** [comment]
Initial comment update to reflect requested changes ☝️

**Comment by ohadlevy** [comment]
ACK - this seems to be related to pf-sass - it was also fixed on foreman at
https://github.com/theforeman/foreman/pull/4947

**Comment by AllenBW** [comment]
@ohadlevy yeah in my previous previous comment i point out the specific offending lines, foreman/us same approach to fix, temporary overrides

**Comment by AllenBW** [comment]
@chriskacerguis @serenamarie125 so is this goooood to get in?

**Comment by chriskacerguis** [comment]
@AllenBW I'm good with it.  I think @serenamarie125 is in a workshop all week; so we'll just wait.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 52994cb8c8c4ce906dde749fa9198dd3afec7ffb
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Nov 28 13:10:31 2017 -0600

    Merge pull request #1245 from AllenBW/bug/master/#1242-login-notification
    
    BUG#1242 - Cleanup login state, notifications fill full viewport
    (cherry picked from commit 5f96bb103a2a2de189103dd2ca6d787ee8b3e98a)
```

**Pull request merged**
