### PR TITLE
Pt#147640893 - redesign vm details

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/147640893

Brings service details closer to the mock mentioned in the pt. 

In ops rows occasionally link to other views, **this task was NOT done as part of this pr**.  

RBAC implemented where applicable. 

There are a few icons/tiny images yet to do on this pr, but wanted to get the bulk of this out there

### Da gooooooodddzzzzzzzz

vmdetails

shout out to @jntullo for api 🛍 ⛑ 

Odds and end this fixes: 
- fixes color names `app_colors` rather than `colors`
- scroll overflow for detail rows whose content extends space
- ensures vm-details error feedback is meaningful
- updates filters (formatBytes) to provide additional precision
- other minor stuff, check commit messages

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@ManageIQ/core-ux for your review

/cc @Loicavenel

**Comment by chriskacerguis** [comment]
@AllenBW this is good 🍣

**Comment by chriskacerguis** [comment]
@AllenBW can you please address the travis fail?

**Comment by AllenBW** [comment]
Yeah that's odd, not failing locally 🤔

**Comment by AllenBW** [comment]
@chriskacerguis yeah that should feel better 🌮 😋

**Comment by chriskacerguis** [comment]
@ManageIQ/core-ux for your review

/cc @Loicavenel

**Comment by Loicavenel** [comment]
First comment is about Smart Tags.. at Service level it is different... we should remain consistent..

**Comment by AllenBW** [comment]
@Loicavenel Dont quite follow, a different level?

**Comment by Loicavenel** [comment]
@AllenBW the way we represent Tags at Service level (blue boxes) is different at the VM level (a table)

**Comment by AllenBW** [comment]
Ah @Loicavenel the inconsistency below:
screen shot 2017-07-06 at 10 12 30 am

A few comments on the comment:
- no unifying ux guidance has been provided, this pr follows outstanding guidance
- parity, this pattern matches opsui

**Comment by Loicavenel** [comment]
@AllenBW yes, this is what I am talking about.. So, we introduced this blue box concept (I like it) which does not exist in OpsUI (Or I never saw it) but in VMS, we do as Ops UI.... This is inconsistent for me... Now, I understand this require some guidance

**Comment by serenamarie125** [comment]
These mocks were provided a ways back, and had no input from PM.  Let's discuss

**Comment by serenamarie125** [comment]
I think that this goes back to the thought that we were introducing new elements into the SUI that would be later brought into the Ops UI.  This is not the only place that we are showing tags this way in the SUI.  If i remember right, chris hale or josh worked on a component with colleen on this a ways back.

**Comment by beanh66** [comment]
@serenamarie125 Correct, Josh and I worked on a common design pattern for Tags that we were looking to first implement throughout the SUI and add follow up stories to implement in the Ops UI. The design can be found [HERE](https://manageiq.github.io/manageiq-design/UX/common/Tags/design) on the design repo under the Common Components section.

**Comment by Loicavenel** [comment]
@serenamarie125 this was my point we should use the same pattern for all SUI when is about Tags :)

**Comment by AllenBW** [comment]
So we have a meet setup to talk about the tags, thinking adjusting falls outta scope of the original ask of this pr, which was to make vm-details look like the mocks we presently had.

Given ☝️ @Loicavenel @serenamarie125 @chriskacerguis, I propose we merge this and do the additional work in a future pr.

**Comment by chriskacerguis** [comment]
@serenamarie125 @Loicavenel so, I setup a meeting to discuss, regardless of the outcome of that meeting it would be a separate PR to address the look / feel of the tags.  Can we agree that this can go in (as it does fit the current UX design) and once we have consensus we will address the tag look and feel?

/cc @chessbyte

**Comment by Loicavenel** [comment]
@chriskacerguis Ok, can we have a screenshot from other type of VM... Windows on wmware, Amazon instance for example

**Comment by chriskacerguis** [comment]
@allewbw could you help with that?

**Comment by AllenBW** [comment]
yeah! i'll get on that monday... 5 prs in a day is enough for me 😩 🤘

**Comment by AllenBW** [comment]
Here are a few more fotos of different provider types, (all i have in my db) @chriskacerguis @Loicavenel 
screen shot 2017-07-10 at 9 29 41 am
screen shot 2017-07-10 at 9 29 47 am
screen shot 2017-07-10 at 9 30 38 am
screen shot 2017-07-10 at 9 30 58 am
screen shot 2017-07-10 at 9 28 46 am
screen shot 2017-07-10 at 9 28 37 am
screen shot 2017-07-10 at 9 28 29 am

**Comment by chriskacerguis** [comment]
Added new UX to the story.  Closing this PR.

**Comment by AllenBW** [comment]
le sigh. 831, I will not forget you

**Pull request closed without merging**
