### PR TITLE
[EUWE] Cockpit icon tooltip gets in the way of button click

### PR DESCRIPTION
**Pull request by chalettu**
PV Ticket https://www.pivotaltracker.com/story/show/143207021
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1439319

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label euwe/yes
@miq-bot add_label bug
@miq-bot add_label services

**Comment by chriskacerguis** [comment]
This seems more like a "hack"...not really a fix.  Perhaps I'm wrong.  Thoughts?

**Comment by chalettu** [comment]
I took a look and I had a few thoughts on why I went this route.  These buttons no longer exist in our master branch and the bigger reason why I trimmed up the text is because of how the list clips overflow on the y axis.  The tooltips get very much cut off if left as is.

**Comment by chriskacerguis** [comment]
Ok, that makes sense to me.  Thanks!

**Comment by chriskacerguis** [comment]
Sorry @simaishi merged by force of habit.  BIG apologies.

**Comment by simaishi** [comment]
@chalettu Which PR removed the buttons in the 'master' branch?

**Pull request merged**
