### PR TITLE
Update service details view for common and generic services.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This PR updates the service details page per UXD design at: 
https://github.com/ManageIQ/manageiq-design/blob/master/UX/ui-service/MyServices/design.md

This includes the Service Details -Summary View for Legacy Services, the Ansible view in NYI. Only the Compute resources are listed, the network and storage resources are not yet available.

image

Finishes #133840615

@chriskacerguis @beanh66 @serenamarie125 

@miq-bot add_label enhancement
@miq-bot add-label euwe/no
@miq-bot add-label ux

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 can you please address the Code Climate issues?

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 also, can you please include some tests for this (unit and integration)?

**Comment by chriskacerguis** [comment]
@jeff-phillips-18 could you please provide an update here?

/cc @serenamarie125

**Comment by jeff-phillips-18** [comment]
@chriskacerguis Working on unit tests (bitten by angular-router code interference) and code climate issues (some code is difficult to make different or create utilities for). Also running into rebase issues with refactoring change from PR #450

**Comment by jeff-phillips-18** [comment]
@chriskacerguis All issues fixed, unit tests added.

**Pull request merged**
