### PR TITLE
PT#14636890 - Update deps

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/146368969

Nothing changes with this, cept a lil bitta pruning deps we don't use

### CODE REVIEW

**Comment by chalettu** [comment]
I am going to request we halt this PR until we fix unit testing.  I need to review some of your proposed changes but do not remove any of the stuff around promises for unit testing.  I added those and tests will fail if you remove it.  The tests aren't failing right now because of that other issue with our tests not running.

**Comment by chriskacerguis** [comment]
@AllenBW can you rebase this with the latest code that has the undo merge in it to make sure all is good?

**Comment by AllenBW** [comment]
@chriskacerguis yep doing presently!

**Comment by AllenBW** [comment]
So the karma-chai-as-promised dep can be updated, but we gotta reconfigure the way webpack runs tests, something for a future update, not today, that aside, @chalettu we good to go here?

**Pull request merged**
