### PR TITLE
Updated menu title for Orders

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/144790949

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label bug
@miq-bot add_label catalogs
@miq-bot add_label fine/no

**Comment by chalettu** [comment]
@miq-bot add_label fine/yes

**Comment by simaishi** [comment]
@chalettu @chriskacerguis I assume this should be `fine/yes` ? Is there a BZ?

**Comment by chriskacerguis** [comment]
@simaishi it should be fine/yes

There was no BZ for this.

**Comment by simaishi** [comment]
@chalettu @chriskacerguis A BZ is needed to backport to Fine branch.

**Comment by chriskacerguis** [comment]
@simaishi BZ added

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 5356c4052b6a9ffdea88ba4a9f47d9d1338e46d3
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed May 3 11:00:16 2017 -0500

    Merge pull request #736 from chalettu/my-orders
    
    Updated menu title for Orders
    (cherry picked from commit 7bf66a5a54649df99b448bde3574bc93485b775f)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1509024
```

**Pull request merged**
