### PR TITLE
PT#144065339-Remove requests functionality from sui

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/144065339
Includes explorers, states, services, navigation

screenshot from 2017-04-24 14-14-39

## requests removed from dashboard, to be replaced by orders in another pr
screenshot from 2017-04-24 14-50-16

ignore colors, gnome is on drugs

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW looks like travis failed.

**Comment by AllenBW** [comment]
@chriskacerguis  on it, that should fix us

**Comment by chriskacerguis** [comment]
@AllenBW negative.

**Comment by AllenBW** [comment]
@chriskacerguis leave me aloooooneeeeee I'm tireeeedddddd (now it'll work my bad from before ;-P )

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 824d3ef550a953a5add23de53d5b2c244a16ad01
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Tue Apr 25 07:47:38 2017 -0500

    Merge pull request #709 from AllenBW/BZ/#144065339-remove-requets
    
    PT#144065339-Remove requests functionality from sui
    (cherry picked from commit a99e49bd819444e42604765b7a10324159cbef5f)
```

**Pull request merged**
