### PR TITLE
[EUWE] Resolves blocker bz 1409959

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1409959

@chriskacerguis

### CODE REVIEW

**Comment by AllenBW** [comment]
@miq-bot add_label euwe/yes, blocker

**Comment by chriskacerguis** [comment]
Removing "blocker" tag, as it is not a blocker in BZ.

**Comment by chriskacerguis** [comment]
@AllenBW do we need this in master as well?

**Comment by AllenBW** [comment]
@chriskacerguis nope, already there we're all 🤘

**Comment by simaishi** [comment]
@AllenBW how was this fixed for 'master' branch?

**Comment by AllenBW** [comment]
@simaishi this same change was implemented a while ago in master (api call had the `=` removed)

**Comment by simaishi** [comment]
@AllenBW Can you please reference the PR that fixed this in 'master'?

**Comment by simaishi** [comment]
Shouldn't we backporting https://github.com/ManageIQ/manageiq-ui-service/pull/353 instead of having a separate PR for Euwe?

**Comment by simaishi** [comment]
So this will be a back port of https://github.com/ManageIQ/manageiq-ui-service/pull/353, but need a separate Euwe specific PR, right?

**Comment by AllenBW** [comment]
? this is a specific Euwe pr, doesn't backport 353

**Comment by simaishi** [comment]
Right... but isn't he change same as https://github.com/ManageIQ/manageiq-ui-service/pull/353?  So https://github.com/ManageIQ/manageiq-ui-service/pull/353 will be 'backported' via this PR.

**Comment by AllenBW** [comment]
Not the same, there were additional changes to the dashboard test in master that 353 include that don't apply to euwe

**Comment by simaishi** [comment]
Had a side discussion with @AllenBW We're on the same page now 😄 

@chessbyte ready for merge.  Euwe BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1410516

**Comment by AllenBW** [comment]
📖 💃 👍

**Pull request merged**
