### PR TITLE
Fixed issue with toolbar not disabling after change in service selection

### PR DESCRIPTION
**Pull request by chalettu**
PV Ticket https://www.pivotaltracker.com/story/show/142867467.

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/no
@miq-bot add_label bug
@miq-bot add_label services

**Comment by AllenBW** [comment]
i think this should be fine yes... no? @chalettu

**Comment by simaishi** [comment]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1438043

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 7553dc4ee4cc1f88d3253cac2728f9088df66d67
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Fri Mar 31 14:21:13 2017 -0500

    Merge pull request #622 from chalettu/disable-services-toolbar
    
    Fixed issue with toolbar not disabling after change in service selection
    (cherry picked from commit e76a7852591c42bcefe334d1f36dec2ecd7ecec8)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1438075
```

**Pull request merged**
