### PR TITLE
Reconfigure custering of events to occur at 1  min interval

### LINKED ISSUE #1181: Resource Details power timeline events need to be clustered over an interval
Presently, resource details power events timeline does not cluster events, reconfigureing this to mirror OpsUI (seen below)
screen shot 2017-10-30 at 12 04 19 pm

cc @Loicavenel

### PR DESCRIPTION
**Pull request by AllenBW**
closes #1181

clustering behavior mirrors OpsUI
## but ya know you wanta see a video
timeline

### CODE REVIEW

**Comment by chriskacerguis** [comment]
How does this look @serenamarie125

**Comment by chriskacerguis** [comment]
How does this look @Loicavenel

**Comment by serenamarie125** [comment]
LGTM for this release.

We should look into this further re: scale.  I thought that we were going to drill in with zoom/slider to get more details of each individual item.

**Comment by serenamarie125** [comment]
@miq-bot add_labels ux/approved

**Comment by serenamarie125** [comment]
@miq-bot remove_labels ux/review

**Pull request merged**
