### PR TITLE
Fixed issue with dialogs not loading on reconfigure

### PR DESCRIPTION
**Pull request by chalettu**
Fix for BZ #1633453
https://bugzilla.redhat.com/show_bug.cgi?id=1633453
@miq-bot add_label bug
@miq-bot add_label gaprindashvili/yes

### CODE REVIEW

**Comment by chalettu** [comment]
SS Before 
failing

SS After
working

**Comment by AllenBW** [comment]
@chalettu does need hammer/yes?

**Comment by chalettu** [comment]
ah, yes.  Forgot to add. 
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 3efa65064bfcfa469c0f6a92020facea6e8adc65
Author: Allen Wight <allen.b.wight@gmail.com>
Date:   Thu Sep 27 15:16:24 2018 -0400

    Merge pull request #1478 from chalettu/reconfigure_dialogs
    
    Fixed issue with dialogs not loading on reconfigure
    
    (cherry picked from commit cb7c805f4d1808ec755efba563bc958523fe48ac)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1635034
```

**Pull request merged**
