### PR TITLE
Show all custom actions vs collapsing to single dropdown

### PR DESCRIPTION
**Pull request by jjlangholtz**
Add labels to custom dropdown action items. Flatten the single custom
action dropdowns into discrete custom buttons and custom button groups.

Support for custom button images will follow in a future PR, along with
responsive action bar layouts.

https://www.pivotaltracker.com/story/show/143578959

@miq-bot add_label fine/yes, ux/review, services, enhancement

screen shot 2017-04-12 at 9 33 54 am

### CODE REVIEW

**Comment by chriskacerguis** [comment]
UX review needed -> @ManageIQ/core-ux

**Comment by cshinn** [comment]
Is a name required, or could one of these possibly be a label-less grey rectangle?

**Comment by jjlangholtz** [comment]
@cshinn The name for custom buttons is required as well as custom hover text and button images. 

The screenshot doesn't show it but the hover text is displayed as a tooltip placed above each button on the main bar. For custom buttons in the dropdown menus, the hover text drops to the left.

**Comment by cshinn** [comment]
@jjlangholtz looks good to me

**Comment by serenamarie125** [comment]
Looks good @jjlangholtz !  If i'm reading your comment correctly, there will be a follow on PR to address responsive layout?

**Comment by jjlangholtz** [comment]
@serenamarie125 That's correct, currently working on the responsive layout changes which I will submit in a separate PR. Later on I will submit a PR to add the missing custom image support (we still need the custom images to be extracted to a repo shared by all UIs).

**Comment by chriskacerguis** [comment]
Thanks @serenamarie125 !!!

@jjlangholtz travis no like you.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 5deb1f6d0243b7a24b2027cb9b8f488231af265a
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu Apr 13 14:41:30 2017 -0500

    Merge pull request #669 from jjlangholtz/flatten-custom-actions-dropdown
    
    Show all custom actions vs collapsing to single dropdown
    (cherry picked from commit 7dd4f73644c145605a3357157cc25db0501c83e2)
```

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 5deb1f6d0243b7a24b2027cb9b8f488231af265a
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Thu Apr 13 14:41:30 2017 -0500

    Merge pull request #669 from jjlangholtz/flatten-custom-actions-dropdown
    
    Show all custom actions vs collapsing to single dropdown
    (cherry picked from commit 7dd4f73644c145605a3357157cc25db0501c83e2)
```

**Pull request merged**
