### PR TITLE
PT#139493225 vm snapshot lists

### PR DESCRIPTION
**Pull request by AllenBW**
https://www.pivotaltracker.com/story/show/139493225 

Left to do:
- [x] ensure mock data is present
- [x] write some tests

~~Right now, querying `/api/vms?expand=snapshots` does not yield snapshot actions, once this bug is fixed we'll be sitting pretty (not yet a blocker, but might be soonish, saul good tho api friends are aware of the issue) :dancer: :taco:~~ gonna hit `/api/vms/{{vmid}}/snapshots instead, proper explorer functionality

## Present State
image
image
image
image
image

### CODE REVIEW

**Comment by chriskacerguis** [comment]
@AllenBW good first pass.  Please be sure to incorporate any design assets that Serena provides.

**Comment by chriskacerguis** [comment]
@AllenBW regarding "/api/vms?expand=snapshots" do you have a BZ, PT, or GH issue you can link to?  If not, can you please create one and link to it so we have a record?

**Comment by AllenBW** [comment]
@chriskacerguis none at the moment, gonna pivot and do something a little different so its not required anyways, updated pr to reflect this

**Comment by AllenBW** [comment]
@chriskacerguis Updated service details page to include snapshot data

**Comment by chriskacerguis** [comment]
@AllenBW can you take a look some tests are failing.

**Comment by AllenBW** [comment]
@chriskacerguis not sure what to tell ya, they pass locally without issue...

**Comment by AllenBW** [comment]
@chriskacerguis at an impasse as to why tests are failing for travis, @chalettu any thoughts?

**Comment by chriskacerguis** [comment]
@AllenBW looks like it is almost there.

**Comment by AllenBW** [comment]
@chriskacerguis it might look like one test but something is seriously wack with the timings across the board... tests pass, this passes locally, but not for travis... I wish it was a fight to write the right test, sadly its not, rather its the fight to time all the tests correctly :(

**Comment by chriskacerguis** [comment]
@AllenBW so, how would do you think we should handle it?  I'm slightly inclined to remove the test (*shudder*) and we can revisit when we tackle Angular2?

**Comment by AllenBW** [comment]
@chriskacerguis not outta ideas yet, just outta hope, i would hate to burn a day trying to figure this out, at this point not sure how it ought to be handled... will think deeply on the matter and report back...

**Comment by chriskacerguis** [comment]
@AllenBW I would agree we have burned a lot of hours on this already.

**Pull request merged**
