### PR TITLE
[WIP] - Temp. fix for 'Browse Entry Point' treeview

### PR DESCRIPTION
**Pull request by dtaylor113**
This PR restores a working 'browse entry point auto-magically expanding' treeview, which broke due to recent changes in 'patternfly-bootstrap-treeview'.  

image

This PR changes SUI dependency to the core 'jonmiles/bootstrap-treeview' until the 'patternfly-bootstrap-treeview' fork is fixed.  The 'patternfly-bootstrap-treeview' issues are tracked [here](https://github.com/patternfly/patternfly-bootstrap-treeview/issues/14).

This allows continued integration with the MiQ Automate RESTFul API while 'patternfly-bootstrap-treeview' is being worked on.  Once fixed, we will switch back to 'patternfly-bootstrap-treeview'.

@serenamarie125 , @bleathem , @skateman, @priley86

JIRA Story: [SUI: Fix treeview in Browse Automate Entry Point Dialog](https://patternfly.atlassian.net/browse/CFUX-218)

### CODE REVIEW

**Comment by dtaylor113** [comment]
@miq-bot add_label euwe/no

**Comment by dtaylor113** [comment]
@miq-bot add_label wip

**Comment by dtaylor113** [comment]
Hmm...looks like 'bootstrap-treeview' requires bower, which isn't part of SUI anymore.  Is this PR a no-go then?  Probably not worth re-introducing Bower for a temp. fix.  Unless we want to fork 'bootstrap-treeview' and make it work sans-bower, but again, probably not worth it.

**Comment by AllenBW** [comment]
@dtaylor113  thanks fo da holla! is below the repo for the dependency? 
https://github.com/jonmiles/bootstrap-treeview

If not, and the dependency isn't published on npm, we'll have to manually add it to the `package.json` by the repo name.

If so, lets go with that, install it using yarn, and don't forget: https://github.com/ManageIQ/manageiq-ui-service/blob/master/docs/code_tour.md#adding-dependencies (though this apparently needs formatting) 🌮 

adding in bower is 🙅‍♂️, we'll find another way

**Comment by dtaylor113** [comment]
Hi @AllenBW, thanks for the reply.  Yes, that is the dependency and it is published on npm.  I did update the package.json file.  If all builds and runs great locally, but TravisCI is barfing because in '/node_modules/bootstrap-treeview/package.json' there is an install script: 
```
"scripts": {
    "install": "bower install",
```
I don't know how to have yarn ignore it.  There is a yarn.config '--ignore-scripts' but I don't think we want that for all SUI dependencies.  Looking for a way to just not do the install script for this one dependency.  -thanks!

**Comment by AllenBW** [comment]
@dtaylor113 AH!! I understand now, looking presently 💃

**Comment by dtaylor113** [comment]
Thanks @AllenBW , but don't spend too much time.  This is just an attempt to continue development while the real fix is being worked on.  It we can't get it to play nicely with SUI, I can just punt this PR and wait for the real fix.  :smile:  -thanks

**Comment by AllenBW** [comment]
@dtaylor113 so I thought it might have been our version of yarn, the latest proved that this is not the case.  Given the only one requiring and whining about bower is travis and that it in no way is being added to the build process, I'm ok adding `bower` to travis script so this can go forward for the time being.

thoughts @chriskacerguis  ❓

**Comment by dtaylor113** [comment]
Hi @AllenBW , @chriskacerguis , no, I wouldn't pollute SUI just for this temp fix.  I've been working with @bleathem and he got me to a point where I know how to get what I need from pf-bootstrap-treeview.  So, I'm going to close this PR and try to get the PF bootstrap treeview fork working.
Thanks for the help!!!! :+1:

**Pull request closed without merging**
