### PR TITLE
[EUWE] Pull power_status directly from the virtual column

### PR DESCRIPTION
**Pull request by syncrou**
Pull power_status directly from the virtual column
(cherry picked from commit 1f495cc700606eaba877face30bbc745aa808595)

https://bugzilla.redhat.com/show_bug.cgi?id=1402995

### CODE REVIEW

**Comment by syncrou** [comment]
@miq-bot assign @AparnaKarve

**Comment by AparnaKarve** [comment]
@syncrou I tested this in the UI and this is good to go. 👍 

/cc @chriskacerguis

**Comment by chriskacerguis** [comment]
@AllenBW this is on the EWUE branch, why it is euwe/no?

**Comment by simaishi** [comment]
FYI, no 'euwe/yes' label needed when PR is a direct commit to Euwe branch.

**Comment by AllenBW** [comment]
:bowing_woman: lottza learning today :fireworks:

**Comment by chriskacerguis** [comment]
@simaishi need anything further from us on this?

**Comment by simaishi** [comment]
@chriskacerguis No, it's all good. I'll merge when the window opens again, we're currently taking blockers only.

**Comment by chriskacerguis** [comment]
@simaishi cool.  just wanted to makes sure you weren't waiting on us for something.  Thanks for all you do!

**Pull request merged**
