### PR TITLE
BZ#1438665PT#143722297-filter catalog by name

### PR DESCRIPTION
**Pull request by AllenBW**
https://bugzilla.redhat.com/show_bug.cgi?id=1438665
https://www.pivotaltracker.com/story/show/143722297

@serenamarie125 Restored catalog name to service catalog card view (as per mocks in the pt)

### you'll notice the catalog name under the service template name
image
### the list of catalogs on which to filter by, kinda looks like the list view
image

### CODE REVIEW

**Comment by chriskacerguis** [comment]
Looks like CC is stuck, and refreshing as been unable to work.  Approving.

**Comment by chriskacerguis** [comment]
Despite by best efforts I can't get CC unstuck.

**Comment by chriskacerguis** [comment]
merging.

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit f8632fc040d90325d0bcdd915444076e524ab4c3
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Mon Apr 17 12:51:43 2017 -0500

    Merge pull request #672 from AllenBW/enhancement/143722297-filter-catalog-by-name
    
    BZ#1438665PT#143722297-filter catalog by name
    (cherry picked from commit d3e58372f15a98d38ee620def22b4be1966fab26)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1442902
```

**Pull request merged**
