### PR TITLE
Moved action button to the bottom of the form

### PR DESCRIPTION
**Pull request by romanblanco**
Fixes: https://github.com/ManageIQ/manageiq-ui-service/issues/1377

http://www.patternfly.org/pattern-library/forms-and-controls/buttons-on-forms/#overview
https://rawgit.com/patternfly/patternfly/master-dist/dist/tests/forms.html

### CODE REVIEW

**Comment by AllenBW** [comment]
@romanblanco is this still a wip?

**Comment by romanblanco** [comment]
@AllenBW Forgot about this, but yes, I still need to add the 'Cancel' button (https://github.com/ManageIQ/manageiq-ui-service/issues/1377#issuecomment-362273139)

**Comment by romanblanco** [comment]
@AllenBW ready for review. I'm not sure if `ui-sref` is the right thing to use, but looks like it works OK

**Comment by AllenBW** [comment]
@romanblanco any way we can get a gif of this in action? or some screen shots?   Is there a bz that this goes with, or does it need one?

**Comment by romanblanco** [comment]
@AllenBW gif (after changes):

screencast from 2018-03-12 16-45-20

No BZ :-)

**Comment by serenamarie125** [comment]
@romanblanco it would be great to have a fixed button bar on the bottom ( similar to how paging works. ), so that the buttons are always viewable

**Comment by AllenBW** [comment]
Something like what the wizard has? 
screen shot 2018-03-12 at 1 27 21 pm

http://www.patternfly.org/pattern-library/communication/wizard/

**Comment by serenamarie125** [comment]
yes @AllenBW but after just chatting with you, I think that I'm 👍 this !

**Comment by serenamarie125** [comment]
@miq-bot add_label ux/approved
@miq-bot remove_label ux/review

**Pull request merged**
