### PR TITLE
Enabled session timeout on pages that poll

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/143874847

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label fine/yes
@ManageIQ/bots add_label blocker

**Comment by chalettu** [comment]
@miq-bot add_label bug

**Comment by chriskacerguis** [comment]
No UX changes.

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1443166

**Comment by simaishi** [comment]
Fine backport details:

```
$ git log -1
commit 6b46ee169568eef0b65cded5bc42c1abf69fc265
Author: Chris Kacerguis <chriskacerguis@users.noreply.github.com>
Date:   Wed May 17 13:09:16 2017 -0500

    Merge pull request #773 from chalettu/session-timeout-polling
    
    Enabled session timeout on pages that poll
    (cherry picked from commit 7925f9c9008e4ae0ceca076c45e42c0f4fa73296)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1443166
```

**Pull request merged**
