### PR TITLE
Changed code climate runtime to only run on builds to master

### PR DESCRIPTION
**Pull request by chalettu**
PV https://www.pivotaltracker.com/story/show/146306965

### CODE REVIEW

**Comment by chalettu** [comment]
@miq-bot add_label housekeeping
@miq-bot add_label fine/no

**Comment by chalettu** [comment]
@chriskacerguis the only big gotcha with this one is the fact that it won't take effect onto our other branches unless those branches have this change applied to the travis.yml file on those branches.

**Comment by chalettu** [comment]
@chriskacerguis Please advise if you would like me to look into creating PR's for certain prior releases to ensure this gets supported universally.  Please specify which releases as well.

**Comment by Fryguy** [comment]
@jrafanie @chessbyte I wonder if we are having this issue elsewhere?

**Pull request merged**
